### ISSUE TITLE
MultipleAccess token for same user and application

### ISSUE THREAD

**Issue by mtangoo** [thephpleague/oauth2-server#1001]
Hi,
I am re-writting the library that works on the top of this library for Oauth2 server and have found little confusing thing here. If I for example create access token from Auth Code grant two times for the same app, I get two valid tokens. Form what I understand, once app request for the new toke, they always discard the older and don't care anymore. So logical way would be to remove old token and its respective refresh token.

I know that the library does not care about how you store things, and that is not my concern.  I want to hear the reason many Oauth2 library don't revoke all existing access token with same app_id, user_id and scopes.

Here is a sample token for passport, Laravel library database rows for two tokens 
```
id	user_id	client_id	name	scopes	revoked	created_at	updated_at	expires_at
24dc5aa38e067afc40ffea922c3bc2294c28c41109ae9346d9929a3a16cb29abe8729eaffbe097b0	1	4	NULL	[]	0	2019-03-09 17:31:48	2019-03-09 17:31:48	2020-03-09 17:31:48
9084ddc26a55c2fed6f7392c2d9f9d4e18c8f9f9287933c05aee582d31b656ee8557ba824c34479e	1	4	NULL	[]	0	2019-03-09 17:59:11	2019-03-09 17:59:11	2020-03-09 17:59:11
```

**Comment by Sephster** [comment]
Are you using the same auth code or multiple auth codes to request the access token?

**Comment by mtangoo** [comment]
@Sephster multiple of course!

**Comment by Sephster** [comment]
There isn't really anything that I can find in the OAuth 2 spec that says a client can't possess multiple access tokens. I also can't think of a reason why this would be a problem. I suppose the access tokens could have differing scopes and the client could use each one for different scenarios but it would be easier to just ask for the union of scopes across both tickets.

Ultimately, as this isn't in the spec, we haven't covered this scenario. If it is an issue for implementers, I would expect this to be resolved in their implementation as I don't imagine this will affect/concern most people.

**Comment by mtangoo** [comment]
>Ultimately, as this isn't in the spec, we haven't covered this scenario. If it is an issue for implementers, I would expect this to be resolved in their implementation as I don't imagine this will affect/concern most people.

@Sephster I understand that. My concern was that if two tokens have exact same permission and client. I wanted just to get opinions here of what others do. My default setting have been to leave them as they are, but as am refactoring different things I though I should re-visit this too.

My first though was check if token with equal scenario, client and user exists and zap it off before saving new one. But then I wanted to gather opinions let I shoot myself!

**Comment by mtangoo** [comment]
Sorry if I wasn't clear of what am asking. Asking is a difficult art :)

**Comment by Sephster** [comment]
Ahh I see. Ultimately it really depends on you. If you feel these extra tokens are unnecessary/a security concern, I would go with your suggested scenario of removing an identical access token before saving a new one.

If I were implementing the system though, I wouldn't be too concerned with this scenario. Instead, I would be asking why the client has requested an identical token when it already has a valid one. It seems more of a client issue than a server to me.

**Comment by mtangoo** [comment]
>If I were implementing the system though, I wouldn't be too concerned with this scenario. Instead, I would be asking why the client has requested an identical token when it already has a valid one. It seems more of a client issue than a server to me.

You are correct. But sometimes its hard to control clients for such things as this. Some app (may be due to incompetent of its developers or just ignorance of Oauth2) requests new token at each user visit. They don't care of refresh token at all.

I think I will stick to standards and let such user shoot their leg and help them heal (kidding)
Thanks for your valuable input!
