### ISSUE TITLE
Authorization Code Grant seems to require client_secret?

### ISSUE THREAD

**Issue by grEvenX** [thephpleague/oauth2-server#1004]
I'm trying to authorize a mobile app using the authorisation code grant, but I came up short because it seems like oauth2-server currently requires the client_secret to be passed when exchanging the code for tokens.
From my research it seems that one of the main use cases of this grant are mobile apps that can't (and thus shouldn't) keep secrets and I wonder if it's a bug in the implementation?

Quoting Aaron Parecki:
> Note: Previously, it was recommended that mobile and native apps use the Implicit grant. In the time since the spec was originally written, the industry best practice has changed to recommend using the authorization code flow with no secret for native apps. There are some additional recommendations for native apps that are worth reading as well.
I've seen it specified in a lot of different sources, but this is one of the more trustworthy ones.

The quote is taken from this article: https://aaronparecki.com/oauth-2-simplified/#mobile-apps
This comment https://github.com/thephpleague/oauth2-server/issues/881#issuecomment-379227024 also indicates that it's supposed to work without a client_secret.

The culprit is in `League\OAuth2\Server\Grant\AuthCodeGrant`'s `respondToAccessTokenRequest()` implementation.
The first line calls `$this->validateClient($request)` (which is implemented in AbstractGrant).
That method again has the following code:
```
$client = $this->clientRepository->getClientEntity(
            $clientId,
            $this->getIdentifier(),
            $clientSecret,
            true
);
```
The last parameter to `getClientEntity` is `$mustValidateSecret`, which in this case is true.
If I set that one to false, I'm able to exchange the code with the access/refresh tokens.

**Comment by sg3s** [comment]
You can work around the issue by approving the validation without a valid secret in the appropriate step. This is how we do it currently.

This behaviour was improved in PR #938 however, and the changes should be present in the future v8 version as it required backwards incompatible changes (v8 is still in development). 

The PRs main goal was to improves how PKCE is activated and enforced so that should fit better with standards too, from then on.

**Comment by grEvenX** [comment]
@sg3s Thanks for the update, will be looking forward to when this lands in the next release :) I guess this issue can be closed then.

**Comment by Sephster** [comment]
Thanks for responding here @sg3s. Marking as closed as no further actions required.
