### ISSUE TITLE
Where or how to login?

### ISSUE THREAD

**Issue by wk-done** [thephpleague/oauth2-server#1020]
Hi,
I have more a question than an issue.

I'm about to implement a single page application. Other apps should be able to access the resources from other apps/pages in the future too.
These resources has to be secured, so I need authorization and authentication.
I never used OAuth or OIDC so please pardon me if I ask dumb questions. ;-)

I would like to use the **authorization code grant**. I read through the [description on project page](https://oauth2.thephpleague.com/authorization-server/auth-code-grant/). In part one of the flow it is written:
>The user will then be asked to login to the authorization server and approve the client.

Also in the example in github, the file [auth_code.php](https://github.com/thephpleague/oauth2-server/blob/master/examples/public/auth_code.php) there is a part in the implementation of `/authorize` whith the following comment:
```php
// Once the user has logged in set the user on the AuthorizationRequest
$authRequest->setUser(new UserEntity());
```

I know that authorization and authentication are different things. But with these comments I'm not sure If there are already mechanisms/functions for logging in, or being redirected to an authentication page... Or in short: How to log in?

Thanks a lot.

**Comment by Sephster** [comment]
Your SPA will be accessing a protected resource which will usually be a collection of API endpoints that the user will have access to. For example, if a user wanted to give access to their Facebook data, they will typically already have an account in Facebook and Facebook will provide an OAuth compliant login.

This server doesn't deal with the login to the protected resource. It just passes the client (typically a browser) to a login location on the protected resource and it is that resource that handles the actual logging in.

It might be worth looking at https://aaronparecki.com/oauth-2-simplified as a good example of how the auth code grant works.

I hope this helps but please feel free to shout out if you have further questions!

**Comment by wk-done** [comment]
Ok, thanks for the explanation. That's what I thought that I'll need to take care of the login.
What was confusing me is the comment in the [example (auth_code.php)](https://github.com/thephpleague/oauth2-server/blob/master/examples/public/auth_code.php). There is an endpoint "/authorize". And in there, there is the following block:

```php
// Once the user has logged in set the user on the AuthorizationRequest
$authRequest->setUser(new UserEntity());
```

1. What should happen before this step? Should the user be redirected to the page where he can log-in?

2. Or should he login first and then call the "/authorize" endpoint? I think this whouldn't be correct. Imagine we have a few applications that have to access the same secured resource. Alle of them would have to take care about the login.

I think it would be good if the comment "Once the user has logged in..." tells a little more what should happen here.

**Comment by Sephster** [comment]
Thanks @wk-done for the feedback. I think many of these questions are answered through the OAuth2 spec so would be best answered there. 

I note however, that we don't have a link to any easy to read spec for OAuth2 in our docs so it is probably worth us adding something in on the intro page. I will get this sorted so that users of the library have more guidance. Thanks for your feedback.
