### ISSUE TITLE
The 'Which Grant' docs are outdated and don't reflect best practices

### ISSUE THREAD

**Issue by matt-allan** [thephpleague/oauth2-server#1038]
The ['Which Grant?'](https://oauth2.thephpleague.com/authorization-server/which-grant/) page of the documentation is outdated and the recommendations don't match up with current best practices. Specifically:

- The password grant is recommended for first party clients, but the [OAuth 2.0 for Browser-Based Apps IETF draft recommends the authorization code grant](https://tools.ietf.org/html/draft-parecki-oauth-browser-based-apps-02#section-5).
- The implicit grant is recommended for third party clients but the [IETF recommends the authorization code flow](https://tools.ietf.org/html/draft-parecki-oauth-browser-based-apps-02#section-9.8.5).

I'm not sure if I can edit the flowchart without a Mac with Sketch installed. If not it might be a good idea to save a SVG that can be edited with Inkscape next time it's edited. :grinning:

**Comment by Sephster** [comment]
Thanks for pointing this out Matt. Unfortunately I don't have access to the old file so it would be the case of creating a new file to facilitate this.

I think it is going to need to be remade. I have flagged this as documentation and will see if I can get round to it at some point (although creating diagrams is not my strong point, especially on Linux)

**Comment by matt-allan** [comment]
It looks like the sketch file is in the repo. I can try to install a sketch demo on my MacBook when I get home from Laracon.

**Comment by Sephster** [comment]
Thank you. If there is a way to convert to an SVG that would be great as well. Hope you're having a good time at Laracon

**Comment by Sephster** [comment]
Marking this as closed as updates by @matt-allan have now been merged into the documentation. Thanks again
