### ISSUE TITLE
Private key permissions inside docker

### ISSUE THREAD

**Issue by rafaelmiti** [thephpleague/oauth2-server#1040]
I had to set a read permission for other users (604) in my private key to the php function `is_readable()` pass.

I guess the problem is related to the use of docker.

I'm using this image: yiisoftware/yii2-php:7.3-apache
Creating this volume: ~/.ssh/app:/app/config/keys:delegated

It would be a security problem add the 604 permission to this line?
https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L54

**Comment by Sephster** [comment]
Unfortunately it would. The key should be restricted to its owner or group but never exposed to the world. Ideally you should add the other users to the group that this key belongs to instead.

I hope this resolves your issue but if you have further comments, please do get in touch.
