### ISSUE TITLE
Codeigniter integration

### ISSUE THREAD

**Issue by samedney** [thephpleague/oauth2-server#105]
I'm currently porting this in to CodeIgniter. Going quite well so far, so will upload something soon. I couldn't find anything out there but knowing who is on this team - has this already been done?

Also - from a beginners perspective - it would be good to have this available as a working project, with some sample data (users, scopes etc) and html login page.

Again - if this is out there, could someone point me in the right direction?

Many thanks.

**Comment by rahendz** [comment]
is there anyone could give my step by step to integrate this oauth libs on codeigniter 2?
