### ISSUE TITLE
Default Scopes Broken?

### ISSUE THREAD

**Issue by contiverosrx** [thephpleague/oauth2-server#1052]
I'm using Laravel Passport with default scope options, but I am getting an error stating that my default scope is invalid. Upon further inspection, it appears that the default scope is not added to the scopeRepository under the AbstractGrant.php file. I see that there is a variable called defaultScope, but nowhere in this file is the default scope set in the scopeRepository nor checked when validating the scopes. 

When debugging, I can see my default scope assigned in Passport make it to the marked line below, but then it fails because it's not in the scopeRepository, which returns null.

AbstractGrant.php line 258
```  php
    public function validateScopes($scopes, $redirectUri = null)
    {
        if (!\is_array($scopes)) {
            $scopes = $this->convertScopesQueryStringToArray($scopes);
        }

        $validScopes = [];

        foreach ($scopes as $scopeItem) {
            ***** $scope = $this->scopeRepository->getScopeEntityByIdentifier($scopeItem); *****

            if ($scope instanceof ScopeEntityInterface === false) {
                throw OAuthServerException::invalidScope($scopeItem, $redirectUri);
            }

            $validScopes[] = $scope;
        }

        return $validScopes;
    }

```

Edited: Added php to markdown.

**Comment by simonhamp** [comment]
@contiverosrx Please can you paste the Passport config where you define your available scopes *and* your sample request for an access token with those scopes?

**Comment by contiverosrx** [comment]
After trying a few things, I found that adding a scope description in the Passport config resolved this issue. 

Currently, adding a scope description is optional; that is, I don't get any error messages that they are required. It would be good to require scopes to have descriptions and have a nice error message for it OR add logic to handle scopes without descriptions.

Passport Config
``` php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;
use Laravel\Passport\Passport;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        // 'App\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        Passport::tokensCan([
            'view-videos' => 'Can view videos', 
            'edit-videos' => 'Can edit videos', 
            'view-dashboard' => 'Can view dashboard',      // To trigger the error, remove the scope description.
        ]);
            
        Passport::setDefaultScope([
            'view-dashboard',
        ]);

        // This is going to add routes specifically for issuing and revoking tokens.
        Passport::routes(null, ['prefix'=> 'v1/oauth']);

        // Other potential config options for my tokens
        Passport::tokensExpireIn(now()->addHours(1));       
    }
}
```

Request - This is for a local test env.  so I don't care about exposing the creds.
``` curl
curl -X POST \
  http://apitut.test/v1/oauth/token \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 680' \
  -H 'Content-Type: multipart/form-data; boundary=--------------------------730668279670734171378302' \
  -H 'Host: apitut.test' \
  -H 'Postman-Token: 5c64ad0b-bac4-4386-8e31-7871bfc9c024,37d51385-506c-40e8-94a2-58ddb258987d' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F username=brenna.harvey@gibson.org \
  -F password=password \
  -F grant_type=password \
  -F client_id=1 \
  -F client_secret=uYBhwgp2cqU3FFXO6plSp63jzSpH9KP8pljWf7AO

```

Error Response:
{
    "error": "invalid_scope",
    "error_description": "The requested scope is invalid, unknown, or malformed",
    "hint": "Check the `view-dashboard` scope",
    "message": "The requested scope is invalid, unknown, or malformed"
}

**Comment by Sephster** [comment]
I think this is likely to be a Passport specific issue as we don't have scope descriptions in the library. Closing this issue but if you feel there is something directly related to the library please shout and we will be happy to reopen it.
