### ISSUE TITLE
Add "fragment" response_mode support for Auth Code grants.

### ISSUE THREAD

**Issue by SlvrEagle23** [thephpleague/oauth2-server#1053]
With the big important folks who write the OAuth standards (I forget what they're called...OWASP?) shifting over to recommending an unauthenticated auth-code flow with PKCE as a replacement for the implicit flow, a number of JS libraries out there that implement this new auth-code flow (in particular, [okta-auth-js](https://github.com/okta/okta-auth-js), which isn't built for League OAuth server but supports OAuth/OIDC servers and PKCE) are sending over `response_mode=fragment` for the auth code response just as they would expect an implicit grant to have.

The Implicit grant code in this repo can handle this and change the response (though instead of taking the `response_mode` parameter into account, it's a constructor argument in the class itself), but the Auth Code grant can't, and is hard-locked into using the `query` response type because there is no `queryDelimiter` variable set. Overriding this requires overriding the full implementation of the fairly complex "complete authorization request" function, which isn't very pleasant for updates or picking up bug/security fixes.

If it makes sense for the OAuth-Server package to support the `fragment` response_mode parameter on Auth Code grants, I would be happy to PR in an implementation that supports this. The code changes needed in the application code would be quite minimal, and would largely just mirror how the Implicit grant already functions.

**Comment by sg3s** [comment]
The response mode parameter and returning auth codes in the fragment part of a URL is part of the OIDC Multiple Response Type Encoding Practices specification.
https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html

The OIDC standards are currently not implemented by this library.

**Comment by Sephster** [comment]
@sg3s is right. Until OIDC is supported we will not look to implement this. Closing for now. Thanks
