### ISSUE TITLE
Usage of invalid_grant for password grant

### ISSUE THREAD

**Issue by ThisIsAreku** [thephpleague/oauth2-server#1059]
In case of an authentication failure in password grant, the returned error is a `invalid_grant` (400)
https://github.com/thephpleague/oauth2-server/blob/07bb5e0aece3207e868c706bec10301551a99b68/src/Grant/PasswordGrant.php#L97-L108

I can't find any informations in RFC about `invalid_credentials` but thinks it's a more appropriate error in this case, and it's already defined in `OAuthServerException`
https://github.com/thephpleague/oauth2-server/blob/07bb5e0aece3207e868c706bec10301551a99b68/src/Exception/OAuthServerException.php#L185-L193

Or maybe I should throw it myself in my implementation of `UserRepositoryInterface` ?

**Comment by Sephster** [comment]
We returned `invalid_credentials` in version 7 but found this did not comply with the OAuth 2 RFC. Unless stated, servers should return a 400 response. The `invalid_grant` response should be returned if client_authentication fails. Details for this change can be found [here](https://tools.ietf.org/html/rfc6749#section-5.2).

I hope this clarifies matters but if you'd like to discuss further please feel free to respond. Marking this as closed unless further information comes to light.
