### ISSUE TITLE
User authentication/authorisation: is this the correct flow?

### ISSUE THREAD

**Issue by nickw1** [thephpleague/oauth2-server#1061]
`Hi,`

Related to issue #1020:

I've read through the docs, examples and general articles on the flow of an OAuth2 application and I *think*  I've got the flow correct, in the /authorize endpoint, for redirecting the user to a login form and the user authorising access to the client app.

The logic I use in my /authorize endpoint is as follows:
Call AuthorizationServer::validateAuthorizationRequest()
If a session exists indicating the user has authorised access
- Set authorisation approved
- Complete authorisation request

Else

- Redirect the user to the login form and pass all the GET data sent to the authorisation server (so the auth server can read it back again later)
 - Once user has logged in and authorised, set a session indicating that this user has authorised access
-  Redirect back to /authorize endpoint, with the same GET data originally sent to /authorize the first time

End if

Is this about right?
I do get an auth token passed back to the client when I do this, so I presume so. 

Thanks,
Nick

**Comment by Sephster** [comment]
Hi Nick. Yep, that seems about right to me!

**Comment by nickw1** [comment]
Thanks! What I'll probably do then is to publish a minimal working client/server example on gitlab soon, I think that will help people get started. When I do feel free to raise any corrections/improvements as issues!

**Comment by Sephster** [comment]
Thanks @nickw1 -  I will mark this issue as closed but if you have any further comments please feel free to shout

**Comment by nickw1** [comment]
Hi,

As promised  I have produced a full, minimal, OAuth2 client/server example using the League client and server libraries - including user authentication and authorisation and a (one-endpoint) API.

I thought this would be useful to others wishing to code an OAuth2 server.

Do NOTE these important caveat! It's a quick and dirty job; basically it's the 'simplest possible thing that works'.

Also please note that it is my first attempt at coding an OAuth2 server and therefore it is NOT GUARANTEED to be fully correct, or secure. I have just implemented it according to my understanding of the documentation on the libraries and on OAuth2 in general.

Do feel free to raise any issues regarding omissions or improvements.

It's at
https://gitlab.com/nickw1/oauth2-example

Thanks,
Nick
