### ISSUE TITLE
Full OAuth2 client/server example

### ISSUE THREAD

**Issue by nickw1** [thephpleague/oauth2-server#1063]
Hi,

As promised in issue #1061 I have produced a full, minimal, OAuth2 client/server example using the League client and server libraries - including user authentication and authorisation and a (one-endpoint) API.

I thought this would be useful to others wishing to code an OAuth2 server.

Do NOTE these important caveat! It's a quick and dirty job; basically it's the 'simplest possible thing that works'. 

Also please note that it is my first attempt at coding an OAuth2 server and therefore it is NOT GUARANTEED to be fully correct, or secure. I have just implemented it according to my understanding of the documentation on the libraries and on OAuth2 in general. 

Do feel free to raise any issues regarding omissions or improvements.

It's at
https://gitlab.com/nickw1/oauth2-example

Thanks,
Nick

**Comment by Sephster** [comment]
Thanks @nickw1 for the update. If possible, could you add this to the original issue so all discussions are contained to that thread? Thanks again for providing an update.

**Comment by nickw1** [comment]
@Sephster OK have added to original issue (#1061).
