### ISSUE TITLE
How can save de token in database? 

### ISSUE THREAD

**Issue by joseL02** [thephpleague/oauth2-server#1065]
How can save de token in database?  Which is the parameter ti return de access token?

**Comment by Sephster** [comment]
In the case of the authcode, you implement the `persistNewAuthCode()` method which is documented in the _AuthCodeRepositoryInterface_.

For the access token, you similarly use the `persistNewAccessToken()` method which is documented in the _AccessTokenRepositoryInterface_.

**Comment by Sephster** [comment]
Closing this issue due to a lack of activity. If you have follow up comments please feel free to post here and I will be happy to take another look.
