### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ClientRepository' not found

### ISSUE THREAD

**Issue by A2DNEW** [thephpleague/oauth2-server#1067]
I use this code:

```
require_once __DIR__."/vendor/autoload.php";

use League\OAuth2\Server\AuthorizationServer;
use League\OAuth2\Server\Exception\OAuthServerException;
use League\OAuth2\Server\Grant\PasswordGrant;
use League\OAuth2\Server\Repositories\ClientRepositoryInterface;

$clientRepository = new ClientRepository();
```

But I get error :

> Fatal error: Uncaught Error: Class 'ClientRepository' not found in /home/a/public_html/app/oauth2.php:23 Stack trace: #0 {main} thrown in /home/a/public_html/app/oauth2.php on line 23

**Comment by Sephster** [comment]
Have you create a ClientRepository class? It is not provided by the server as we don't know what underlying DB you will be using. You need to create a ClientRepository class that implements all of the methods in the ClientRepositoryInterface.

Hope this helps!

**Comment by A2DNEW** [comment]
I only intsall oauth2 with composer
How where create ClientRepository class?

**Comment by Sephster** [comment]
It is up to you where you create it. It will depend on your project structure. If you want an example, take a look in the examples folder which should hopefully point you in the right direction: https://github.com/thephpleague/oauth2-server/tree/master/examples/src/Repositories

**Comment by Sephster** [comment]
Closing this issue due to a lack of activity. If you still have questions please feel free to respond and I will reopen this for further discussions. Thanks
