### ISSUE TITLE
How to deal with CryptKey permission

### ISSUE THREAD

**Issue by kpn13** [thephpleague/oauth2-server#1070]
Hi,

Sorry to put on the table again a question many times discuss here but it is still not clear for me. 

The crypt key is owned by the webserver with 600 permission. So it cause a problem when in dev environment we launch phpunit tests with an other user.

What should we do to avoid this problem ? 

Thank you for your help.

**Comment by Sephster** [comment]
Hello. Sorry for my delay in replying to this. What are you testing in this scenario? Could you also detail why you can't run your tests as the same user? Cheers.

**Comment by kpn13** [comment]
Hi,

Here is the scenario : 

1 - First time I go to my application with my browser, the crypt key does not exist, so it's created and owner by my web server user (www-data) with permission 600.
2 - Then I want to launch my test suit using Phpunit. It failed because the user executing tests is not www-data (obviously) and my user does not have permission to use the crypt key.

`LogicException: Key path "file:///tmp/xxx.key" does not exist or is not readable`

Same thing with the reverse scenario : if I launch my test suit before the crypt key is created, it will be created for a user different than www-data and when I try to go to my app using my browser, It failed.

For now, I used to launch my test as www-data  `sudo -u www-data vendor/bin/phpunit` but I think it is not a good practice.

Do you have a better solution ?

Thanks !

**Comment by Sephster** [comment]
In our own tests, we create a stub key and chmod the file to 0600 at run time which solves any issues. This would probably be your cleanest option. I've included the relevant section of code in the test for reference.

https://github.com/thephpleague/oauth2-server/blob/b1582d052063397edccd1b09e49d8906ea20af10/tests/AuthorizationServerTest.php#L34-L40

Please do let me know if this is what you were looking for. Cheers

**Comment by kpn13** [comment]
Hi @Sephster ,

Thank you for your answer, it's exactly what I need !

Thank you for taking time for my question !
