### ISSUE TITLE
Support hash instead of query string for authorization response

### ISSUE THREAD

**Issue by matt-allan** [thephpleague/oauth2-server#1077]
Hello,

I was building a demo with the [AppAuth](https://appauth.io/) JS library and learned that the AppAuth library returns the authorization response code and state params in the URL hash instead of the query string.

I [opened an issue](https://github.com/openid/AppAuth-JS/issues/137) to ask why it doesn't conform to the spec and learned they are doing this to avoid the code and state params being leaked in `Referer` headers.

This isn't [one of the official countermeasures](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-13#section-4.2.4) but it might be worth supporting in this library if the most popular OAuth 2.0 client requires it?

I'm imagining we would add a configuration option to choose between query string and hash, defaulting to query string for backwards compatibility. The option would only apply to the authorization code grant since the implicit grant should always use hash.

**Comment by Sephster** [comment]
Hi Matt. Thanks for the investigation and background on this. Do you know of any other server implementations supporting this? Usually if a behaviour isn't in the spec, we won't implement it but I'd be keen to see how widespread this is. Thanks!

**Comment by matt-allan** [comment]
I looked around and didn't see any other implementations doing this. Google seems to still be using the implicit grant so I couldn't even find an example of them doing this.

I was thinking about this some more and with PKCE it doesn't seem like a huge benefit from a security standpoint - PKCE already protects the token from interception.

I'm going to go ahead and close this for now, thanks for the input!
