### ISSUE TITLE
invalid_grant Error When Credentials are Incorrect

### ISSUE THREAD

**Issue by Imboga** [thephpleague/oauth2-server#1093]
I'm using the native oatuh2-serve included in Laravel 6.2.
In the previous version of oauth2-server, I used to face a 400 error when credentials were missing and 401 error when credentials were wrong.
This is not happening since this [PR #967](https://github.com/thephpleague/oauth2-server/pull/967/commits/2b4974b697ca937d37f407c429d792c467af7ec5).

Is this the way you handle returning errors now? How can I know about missing or wrong credentials?

Sorry if this question does not belong here, but not sure where to post it.

**Comment by Sephster** [comment]
Hi @Imboga - yep, we changed this because the old response wasn't conforming to the OAuth 2 specs properly. You could possibly leverage the event to track an invalid credentials attempt

**Comment by Imboga** [comment]
Perfect! Thanks for your fast reply. I will try to find a way to handle this.

**Comment by lk77** [comment]
Hello,

is there a way to restore the old behaviour ?

**Comment by Sephster** [comment]
The only way would be to downgrade to an older version of the library. I would recommend that if you need to track this, you should leverage the events systems instead. 

We won't be reverting this change as the previous implementation didn't conform to the OAuth 2 spec unfortunately.

**Comment by siarheipashkevich** [comment]
@Imboga did you find the solution for your problem?

**Comment by meyer59** [comment]
@Sephster can you provide an example how to handle events to return different status code ?

**Comment by Sephster** [comment]
@meyer59 If you are using the server middleware, you could maybe intercept the exception and change the response to whatever you want it to be. I wouldn't recommend this though as the responses given by the server are valid OAuth responses. Hope this helps
