### ISSUE TITLE
Authorization Code flow and PKCE

### ISSUE THREAD

**Issue by nivv** [thephpleague/oauth2-server#1099]
I'm having some trouble with oauth and the Authorization Code flow and PKCE. How can I get a refresh token? 

The refresh token flow requires a `client_secret`, but PKCE prohibits `client_secret`. Is refresh token a no go?

Am I missing something? I've searched around on the obvious places, but all I can find is that `client_secret` is required for the `refresh_token`-grant.

**Comment by Sephster** [comment]
Sorry I'm in work just now. If you are right, and we are explicitly requiring a client_secret, we will need to change this as it is not complying with the spec. We should only request this from confidential clients.

**Comment by nivv** [comment]
@Sephster I left the `client_secret` blank like below:

```
{
  grant_type: 'refresh_token',
  refresh_token: 'the refresh token',
  client_id: 'fec7a881-b7c9-4f7f-b472-ce1a11018f5b',
  client_secret: '',
  scope: '',
}
```

It's stored as empty string in the DB as well. So I guess it works as intended!
