### ISSUE TITLE
Refresh a token from a different client

### ISSUE THREAD

**Issue by alterphp** [thephpleague/oauth2-server#1101]
This is not an issue but a question about implementation.

I have many webapps, each using its own subdomain. Each webapp is an OAuth client. When I'm logged on a webapp, I'm also logged on the other ones, so that I can browse between my webapps without authenticating against each one.

Problem: base implementation of RefreshTokenGrant disallows refreshing a token from a different client (cf. https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/RefreshTokenGrant.php#L105). Is it something I should not change ?

**Comment by Sephster** [comment]
If you want to stick with the OAuth spec, then you shouldn't change this. If a different client uses a refresh token, how is the spec to know that the token hasn't been leaked? It's a security measure to prevent attacks.

Hope this helps!
