### ISSUE TITLE
OAuthServerException: Unauthorized instead of Internal Server Error

### ISSUE THREAD

**Issue by TheNodi** [thephpleague/oauth2-server#1106]
(This issue comes from Laravel Passport, but it is applicable to every token repository that can throw a generic error.)

I'm using MySQL as storage for Access Tokens (default Laravel Passport implementation). When a request comes in, `BearerTokenValidator::validateAuthorization` is called to validate the parameters. 
If MySQL is not available (e.g. `Too Many Connections`), every authenticated request will respond with 401 status code instead of 500.

During the validation, the access token repository is called to determine whether the token has been revoked:
https://github.com/thephpleague/oauth2-server/blob/d48d8480f13057f0717105be0638997ba83b97f6/src/AuthorizationValidators/BearerTokenValidator.php#L87-L90

Because it connects to MySQL, a [PDOException](https://www.php.net/PDOException) is thrown.
The exception is caught at the end of the function, and wrapped in a `OAuthServerException::accessDenied`, which reports a status code of 401 instead of 500:
https://github.com/thephpleague/oauth2-server/blob/d48d8480f13057f0717105be0638997ba83b97f6/src/AuthorizationValidators/BearerTokenValidator.php#L101-L104

I believe that catch is there to validate for possible JWT errors, but it is overly catching database errors. 

My suggested solutions is to move [L87-L97](https://github.com/thephpleague/oauth2-server/blob/d48d8480f13057f0717105be0638997ba83b97f6/src/AuthorizationValidators/BearerTokenValidator.php#L87-L97) after the try-catch. Hence all exceptions coming from the access token repository will be thrown correctly.

I have a doubt on the `$token->getClaim('..')` methods, whether they should be inside the try catch or not. They can throw `OutOfBoundsException`, but it would mean that a JWT token has been issued with a wrong format.
A new try catch can be added to wrap only `OutOfBoundsException` with `OAuthServerException::accessDenied()`, but it might catch other unrelated exceptions inside the token repository again.

**Comment by Sephster** [comment]
Thanks for spotting this. Because this is a PDO error and in general, this library is storage agnostic, I think it is right we don't specifically capture this error. Happy to implement your suggest of just moving the code lines.

Have created PR #1107 to address this. Thanks for reporting
