### ISSUE TITLE
Put and Delete

### ISSUE THREAD

**Issue by sicsol** [thephpleague/oauth2-server#111]
I get the following errors when trying to use both a PUT and DELETE request.

Call to undefined method League\OAuth2\Server\Util\Request::DELETE()
Call to undefined method League\OAuth2\Server\Util\Request::PUT()

This happens if i pass the access_token as a parameter.

If it's an authorization header it's fine.

**Comment by andreikun** [comment]
If you want to access secured paths using access_tokens as query string informations below might help you:

Check here: https://github.com/thephpleague/oauth2-server/blob/master/src/ResourceServer.php#L146

It shouldn't be $this->getRequest()->request->get($this->tokenKey). Instead it should be $this->getRequest()->get($this->tokenKey).

That;s why it does not work. I already adjusted my code, it would be nice if someone from phpleague will adjust too.

It works now with both POST and GET having access_token in query string like ?access_token= mQ77AR4vzpTdn81Sc4os7FdRYWd3UJJjQ1GBJ3Us
