### ISSUE TITLE
The access token return is wrong or I am doing something wrong.

### ISSUE THREAD

**Issue by jerfeson** [thephpleague/oauth2-server#1115]
I am using version "8.1.0". In previous versions, the BearerTokenResponse class generated the access token based on JWT, now the accessToken object defined in the AbstractResponseType class is needed, the setAccessToken method is converted to a string, but it turns out that in this case it is unable to cast

**AbstractGrant**

```php
 protected function issueAccessToken(
        DateInterval $accessTokenTTL,
        ClientEntityInterface $client,
        $userIdentifier,
        array $scopes = []
    ) {
        $maxGenerationAttempts = self::MAX_RANDOM_TOKEN_GENERATION_ATTEMPTS;

        $accessToken = $this->accessTokenRepository->getNewToken($client, $scopes, $userIdentifier);
        $accessToken->setExpiryDateTime((new DateTimeImmutable())->add($accessTokenTTL));
        $accessToken->setPrivateKey($this->privateKey);

        while ($maxGenerationAttempts-- > 0) {
            $accessToken->setIdentifier($this->generateUniqueIdentifier());
...
```

**AbstractResponseType**
```php
    /**
     * {@inheritdoc}
     */
    public function setAccessToken(AccessTokenEntityInterface $accessToken)
    {
        $this->accessToken = $accessToken;
    }
```
**BearerTokenResponse**

```php
        $responseParams = [
            'token_type'   => 'Bearer',
            'expires_in'   => $expireDateTime - \time(),
            'access_token' => (string) $this->accessToken,
        ];
```
**Result**

```json 
{
    "token_type": "Bearer",
    "expires_in": 3598,
    "access_token": "[]"
}
```
Stack
Slim framework 4
Slim Psr 7
oauth2-server 8.1.0

**Comment by jerfeson** [comment]
Sorry I found my mistake, it was between the chair and the keyboard. the convertToJwt function was replaced by the magic __toString method, it was in the documentation in the update area.

https://oauth2.thephpleague.com/upgrade-guide/#access-tokens

**Comment by Sephster** [comment]
No worries :) Good luck on your install.
