### ISSUE TITLE
Usage of Custom Claims

### ISSUE THREAD

**Issue by skroczek** [thephpleague/oauth2-server#1120]
First of all thank you for this great library and for all the work that went into it. And of course congratulations to @Sephster on the new human fork. :partying_face: 

So what I'm currently trying to implement are custom claims.  What I actually want is relatively simple. I want an equivalent to this:

```
<php
// File: src/Entities/Traits/AccessTokenTrait.php
// [...]
trait AccessTokenTrait
{
// [...]
    /**
     * Generate a JWT from the access token
     *
     * @param CryptKey $privateKey
     *
     * @return Token
     */
    private function convertToJWT(CryptKey $privateKey)
    {
        return (new Builder())
            ->permittedFor($this->getClient()->getIdentifier())
            ->identifiedBy($this->getIdentifier())
            ->issuedAt(\time())
            ->canOnlyBeUsedAfter(\time())
            ->expiresAt($this->getExpiryDateTime()->getTimestamp())
            ->relatedTo((string) $this->getUserIdentifier())
            ->withClaim('scopes', $this->getScopes())

             // I want to add addiditonal information here:
             ->withClaim('custom', 'Custome DATA')

            ->getToken(new Sha256(), new Key($privateKey->getKeyPath(), $privateKey->getPassPhrase()));
    }
// [...]
}
```

-> I would like to add additional information to the JWT.
However, I don't see how I can do this without implementing a custom Grant, with TokenRepository etc. I'm aware that there are a few PR's out there on this topic, but none of them really seem to solve this. So my question is, is there an easier way to handle this?

**Comment by Sephster** [comment]
Hi @skroczek - thank you so much for the well wishes. I think I'm over the worst of the sleepless nights now. Thanks for your kind words regarding the package.

I've seen in Passport that there are some calls to add custom claims to the JWT so this is something we definitely want to look at. You are right though, that unfortunately at this stage, there is no way to do this out of the box. It would require a custom BearerTokenResponse and AccessTokenTrait in order to achieve this.

You can add custom fields to the response but not the JWT which is what a lot of people are looking for. It is something I would like to get into the library in due course though. Unfortunately, the only way to do it at this time is to write your own implementations. Sorry this probably isn't the answer you are looking for.

**Comment by skroczek** [comment]
Thanks for your quick response. Of course, it would be nice if it would already work, but I was already expecting this answer. It rather makes me feel better that I didn't miss anything obvious and it is also a chance to contribute to this library
I have therefore created a fork (https://github.com/skroczek/oauth2-server/tree/wip/private-claims) to help me to evaluate what is needed. I haven't tested the code yet, I'll do that tomorrow, but that's what I'm thinking about. It would be great if you could find the time to take a look at it and give me some feedback. Especially with the implementation in the grants, I'm still unsure if this doesn't violate any rfc or could be a security problem. Maybe there is more testing necessary. 
Cheers

**Comment by Pchelolo** [comment]
We (Wikimedia Foundation) are currently using this library in production for OAuth support in Wikipedia and its sister projects and are very happy with it, thank you a lot for building and maintaining this project.

We are very interested in supporting private claims for one of our infrastructure projects, so we would be happy to help with getting the pull request by @skroczek accepted. We are going to build some prototypes using the pull request to test it and perhaps come up with improvement suggestions. We would be happy to help testing the feature, implementing enhancements, writing unit tests, and documentation. Anything needed we can help doing.

We would like to avoid running a fork of this library, so we are seeking guidance on the best approach to get the implementation accepted upstream, or in case there’s no interest in integrating a feature in the near future, please let us know and we will adjust our plans accordingly.

**Comment by Sephster** [comment]
Hi @Pchelolo - thank you for the kind words regarding the project. The PR is definitely something I'd be keen on integrating into the system but I haven't had time to do a full review yet as I welcomed my first child into the world a few months back. Things are easing up now so I'm hoping to dedicate more time to this.

If you have time to perform a review of the PR that would be welcome. @skroczek mentioned there were a number of gaps in the PR he'd like guidance with.

To be merged the main thing I would be look for is for the changes to be non-breaking. If they were we'd need to commit against the next major version. I'd also need to ensure that the code is spec compliant and has adequate test coverage. If it satisfies all of these I can't see any reason not to merge.

I would welcome any time you have to review this and find if there are any gaps in spec compliance we'd need to address. Thank you for your offer of assistance.

**Comment by skroczek** [comment]
Hi @Sephster and @Pchelolo , I would be very happy if someone would review the pull request. Here is a short summary of the current status: As far as I can tell, the pull request should not have any back compatibility breaks. This is best verified again, since the pull request has become a bit more extensive. However, it has been made sure that the changes are optional. The tests have been adapted to cover the added code and run without errors. In my opinion, there are still two points open apart from the review. One is the question if the testing is sufficient, since no explicit new tests have been added and the other is that the new feature still needs to be documented. Suggestions of any kind are very welcome and I will be happy to implement them.

**Comment by MJTheOne** [comment]
Why is this closed? The PR hasn't been merged yet
