### ISSUE TITLE
I can Add milti account feature

### ISSUE THREAD

**Issue by RanjeetSingh00** [thephpleague/oauth2-server#1131]

**Comment by Sephster** [comment]
Please can you provide a bit more details about what you mean? Thank you.

**Comment by RanjeetSingh00** [comment]
I want to make a oauth authentication system with multi accounts like google or others.

**Comment by Sephster** [comment]
Connecting to accounts like Google sounds more like a client task. Many of these oauth providers are already integrated into https://github.com/thephpleague/oauth2-client - I would take a look there to see if this suits your requirements. Thanks
