### ISSUE TITLE
Notice: Undefined offset at AuthCodeGrant when redirect uri not defined

### ISSUE THREAD

**Issue by pszalko** [thephpleague/oauth2-server#1133]
Case related to #1125:

Client:
* no default redirect URI specified -> returns empty array on `getRedirectUri()`

AuthCodeGrant:
* expects array returned from `$client->getClientUri()` has at least one element
* defined client returns an empty array

Result:
* PHP Notice: Undefined offset: 0 at /src/Grant/AuthCodeGrant.php (line 271)

```
<?php
//...

namespace League\OAuth2\Server\Grant;

//...

class AuthCodeGrant extends AbstractAuthorizeGrant
{

//...

    public function validateAuthorizationRequest(ServerRequestInterface $request)
    {

//...

        $defaultClientRedirectUri = \is_array($client->getRedirectUri())
            ? $client->getRedirectUri()[0]
            : $client->getRedirectUri();

        $scopes = $this->validateScopes(
            $this->getQueryStringParameter('scope', $request, $this->defaultScope),
            $defaultClientRedirectUri
        );

//...
```

**Comment by Sephster** [comment]
Thanks for spotting this. I will aim to get a fix out today. It looks like we aren't properly detecting invalid clients that have no redirect URI associated with them.
