### ISSUE TITLE
"Implementation" for Authorization Code Grant seems incomplete

### ISSUE THREAD

**Issue by ppritcha** [thephpleague/oauth2-server#1136]
I'm new to the library and trying to use the example code in the "Implementation" section for the Authorization Code Grant.  Within the code for /authorize, I see:

// The auth request object can be serialized and saved into a user's session.
// You will probably want to redirect the user at this point to a login endpoint.

How would I go about doing that from within this function?  The example seems to be partial or incomplete.  Is there a complete, working example for using the Slim framework to implement a server that I can follow?

**Comment by Sephster** [comment]
I'm not aware of any complete implementation that is out there for the Slim Framework. The purpose of the examples is to get you going but you will need to fill in some of the gaps with knowledge about the Slim Framework or adapt the example to whichever other framework you might be using.

To serialize an object, you would use the `serialize()` function which returns a string that you can then store in a user session. Something like the following:

```
$authRequest = $server->validateAuthorizationRequest($request);
$authRequest->setUser(new UserEntity());
$authRequest->setAuthorizationApproved(true);

$serializedAuthRequest = serialize($authRequest);

$_SESSION['authRequest'] = $serializedAuthRequest;
```

Something along those lines. Of course, you should have some kind of middleware set up in Slim to start and end the session.

For redirection, with Slim 3 you'd be using something along the lines of:

```
return $response->withRedirect('/foo');
```

I hope this is of some help.

**Comment by ppritcha** [comment]
Thanks for the response.  I was able to find a different oauth2 library with more complete documentation and examples that should get me going faster.  Wishing you all the best with your ongoing development of this library.
