### ISSUE TITLE
Question about migrating from v4 non-JWT access tokens

### ISSUE THREAD

**Issue by spronkey** [thephpleague/oauth2-server#1139]
I'm updating an implementation using v4 of this package to v8, moving to Laravel\Passport and looking at how to provide a migration path for clients that have non-JWT tokens.

I have existing clients using access and refresh tokens that are simply strings that match up to strings in the database. The current implementation of the Bearer Token Validator seems to be specifically targeted at JWTs, and doesn't seem to have any kind of fallback mechanism or hook to allow me to use simple db-backed string tokens.

Has anyone else implemented a fallback technique? i.e. try JWT parse, if it fails, try finding token by string in the database and verifying that way? My current thoughts are to implement an alternative BearerTokenValidator and extend the AccessTokenRepository but not sure whether there's a better way?

**Comment by Sephster** [comment]
The rewrite for version 5 was quite extensive. I am not aware of people writing fallback mechanisms but I assume people have done this. 

I think you would be best writing an alternative BearerTokenValidator as you have mentioned which lifts logic from version 4 until you can weed the old tokens out of your system. 

Sorry I can't be of further help with this by providing examples etc.
