### ISSUE TITLE
Question: how server create identifier ?

### ISSUE THREAD

**Issue by pigochu** [thephpleague/oauth2-server#1143]
I think identifier is too long ,  is is possible let us choose 36 base identifier ?  ex.  base_conver( $identifier , ? , 36)

**Comment by Sephster** [comment]
Are you talking about the function `generateUniqueIdentifier`? You should be able to pass a length to this function to change the length of the identifier if you wish.

**Comment by pigochu** [comment]
Thanks
I will overrwrite it convert to to base 36, the length will be shorter.
