### ISSUE TITLE
Per token expiration time

### ISSUE THREAD

**Issue by KieronWiltshire** [thephpleague/oauth2-server#1144]
Why is it not possible to specify per token expiration time? I'm using Laravel Passport, please see my issue here which explains my trouble.

https://github.com/laravel/passport/issues/1356

**Comment by Sephster** [comment]
Typically the expiration time is a security consideration that is taken by the server owner as they will be tasked with protecting the data. We could maybe link this to specific client's but this would add in complexity which is unlikely to benefit most users. 

You mention in the support call that you would like to set the expiration time for longer than a year. However, I wouldn't recommend this from a security standpoint.

**Comment by KieronWiltshire** [comment]
I guess it depends on the use case as I am using personal access tokens as API keys too. I guess what I’m really asking for is just the ability for the user to specify their own expiration time, for example if I have a customer on my system who wants to create an API key, I would prefer to do so through the auth mechanism I already have instead of building another system just to authorise API keys too. Thoughts?

**Comment by Sephster** [comment]
I don't think this is something we would include in the server at this time due to the security implications. If you can find examples of other popular servers that use this mechanism then I'd be happy to look at this again. Sorry we aren't going to go forward with this at this time.
