### ISSUE TITLE
Call to undefined method League\\OAuth2\\Server\\AuthorizationServer::setEncryptionKey()

### ISSUE THREAD

**Issue by Moriuks** [thephpleague/oauth2-server#1147]
I'm trying to authenticate suiteCRM after installing/doing the steps in [SuiteCRM API](https://docs.suitecrm.com/developer/api/developer-setup-guide/json-api/#_before_you_start_calling_endpoints) and double checking in [Oauth2 installation ](https://oauth2.thephpleague.com/installation/).

When i tried to reach the endpoint {suitecrm.url}/Api/Acces_token i get a 505 error and the apache error logs show the following:

`Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method League\\OAuth2\\Server\\AuthorizationServer::setEncryptionKey()`

Any suggestion on how to fix this?, this is the my first time setting up a Oauth server and i have double checked and retried the steps mention in the documentation but i get to the same error.

My set up:
system: Linux Debian 4.19.152-1
suitecrm Version 7.11.15
composer.lock
`          "name": "league/oauth2-server",
            "version": "6.1.1",
            "source": {
                "type": "git",
                "url": "https://github.com/thephpleague/oauth2-server.git",
                "reference": "a0cabb573c7cd5ee01803daec992d6ee3677c4ae"
             },
`

**Comment by Sephster** [comment]
I would recommend you use a later version that 6.1.1 if possible. Have you got any code that is explicitly calling the setEncryptionKey method? This is usually handled by the AuthorizationServer and should be called on a grant type.

My suspicion is that you have some custom code somewhere which is calling this function incorrectly. Without seeing your entire repository I can't provide any better information than that but I hope this helps.

Let me know how you get on.

**Comment by Moriuks** [comment]
Thanks for the response Sephster, 
I am not sure what the issue was but it has to do with the bitnami configuration so i just installed suiteCRM without bitnami and now i am able to authenticate to the server, it responds with the token and refresh token.
