### ISSUE TITLE
Change oauth2-server version 

### ISSUE THREAD

**Issue by elironkryeziu** [thephpleague/oauth2-server#1157]
I want to change the version of league/oauth2-server package from 8.1.1 to 8.1.0. The problem is that laravel/passport package requires it and I don't have it in my composer.json file.

How can I change the version?

**Comment by dcyou** [comment]
`
composer require lcobucci/jwt:3.3.3 && composer update
`
https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709
https://github.com/thephpleague/oauth2-server/pull/1146

**Comment by FatlumGjinofci** [comment]
@dcyou you saved us from HELL ;)
