### ISSUE TITLE
Dependency JWT ^3.3.1 will be updated to 3.4.0 

### ISSUE THREAD

**Issue by yulei745** [thephpleague/oauth2-server#1160]
Deprecated: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.

**Comment by Sephster** [comment]
Please update to the latest version of the server which uses v3.4 minimum.

If you are having issues on production please ensure error notifications are not turned on in your php.ini file 👍

**Comment by yulei745** [comment]
@Sephster ok tks
