### ISSUE TITLE
How to support multiple redirect_uri for oauth2 client?

### ISSUE THREAD

**Issue by Gelembjuk** [thephpleague/oauth2-server#1177]
Is there any workaround to support more than one valid redirect_uri for oauth2 client?

I see in the code validateAuthorizationCode function requires a redirect_uri to be string and equal to provided url.

Maybe there is some trick to support more than one vale url? 
Maybe inside ClientRepository i can somehow to read requested url and set "correct" url to a client entity?

**Comment by Sephster** [comment]
The getRedirectUri function can also return an array. If you have multiple redirect uris return the in an array from this function on your client 👍

**Comment by Sephster** [comment]
Marking as closed due to lack of activity. If you have any follow up questions please do let me know and I will be happy to reopen this.
