### ISSUE TITLE
User deprecated function: Implicit conversion of keys from strings is deprecated

### ISSUE THREAD

**Issue by ABGEO** [thephpleague/oauth2-server#1182]
Hello there,

I am using  `league/oauth2-server8.1.1` with `lcobucci/jwt:3.4.2` and am getting the following deprecation message:

> User deprecated function: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. in Lcobucci\JWT\Signer\BaseSigner->getKey() (line 57 vendor/lcobucci/jwt/src/Signer/BaseSigner.php).

I suggest using `LocalFileReference` in `BearerTokenValidator`. I will provide the PR shortly.

**Comment by ABGEO** [comment]
Oh, I see you don't support `8.1.x` and this issue has already been fixed in `8.2.x`, right?

**Comment by Sephster** [comment]
That's correct. If you upgrade this issue should be resolved. Thanks
