### ISSUE TITLE
Custumize request attributes in BearerTokenValidator

### ISSUE THREAD

**Issue by 2618094** [thephpleague/oauth2-server#1183]
Hello! I'm looking for a way to add custom request attributes for token.
The problem is here:
https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationValidators/BearerTokenValidator.php#L120
There is no option to add attributes except for write my own implementation of validator.

**Comment by Sephster** [comment]
At the moment this is the only way sorry. Hoping to get custom claims added in soon though.
