### ISSUE TITLE
PASETO instead of JWT?

### ISSUE THREAD

**Issue by Extarys** [thephpleague/oauth2-server#1185]
I found #873 but I didn't find any follow-up or any other information online.

Is there a way to use PASETO tokens instead of JWT?

This looks like an awesome library though, I hope I'll get to use it.

**Comment by Sephster** [comment]
There is no implementation for PASETO in the library yet. I was wIting for an Ietf RFC to be finalised. Last time I checked a draft version had been submitted but I'm not aware of it going any further.

This isn't to say it is a blocker at all but would probably make us implement quicker. Cheers

**Comment by Extarys** [comment]
Hey @Sephster, thanks for your reply. I'm not a OAuth specialist so I thank you for your explanation.

> This isn't to say it is a blocker at all but would probably make us implement quicker. Cheers

I share the feeling.

**Comment by oojacoboo** [comment]
Would be great to see PASETO support.  Is there any middleware where a custom implementation for PASETO support can be added?
