### ISSUE TITLE
Redirection URI validation and rfc8252

### ISSUE THREAD

**Issue by exeba** [thephpleague/oauth2-server#1188]
As far as I understand the current implementation requires a perfect match between the registered redirection URI and the URI specified in the authorization request.

However, section 8.4 of rfc8252 states:

Authorization servers MUST require clients to register their complete
redirect URI (including the path component) and reject authorization
requests that specify a redirect URI that doesn't exactly match the
one that was registered; **_the exception is loopback redirects, where
an exact match is required except for the port URI component._**

**Comment by Nikita128** [comment]
Yeah, we've encountered the same exact issue recently. I've created [a separate post](https://github.com/laravel/passport/issues/1406) about this.

**Comment by Sephster** [comment]
Thanks both. Happy to accept a PR but this looks like something we should resolve. I will flag it for a future update.
