### ISSUE TITLE
Enable non-constant port for http://localhost redirect URLs for Native App clients

### ISSUE THREAD

**Issue by Nikita128** [thephpleague/oauth2-server#1190]
Native App client is using loopback interface (listens on http:localhost:<random_port>) to accept an authorization code sent via redirect URL from an authorization endpoint. But OAuth 2.0 server seems not to support random ports for localhost redirect URLs if a client is a Native App, but it's stated in [the specification](https://tools.ietf.org/html/rfc8252#section-7.3) that the authorization server must support this feature.

> The authorization server MUST allow any port to be specified at the
> time of the request for loopback IP redirect URIs, to accommodate
> clients that obtain an available ephemeral port from the operating
> system at the time of the request.

So it would be great if you would add this feature to new iterations of your product (or if it's possible to do this with some existing versions it would be great to know).

Looking forward to your response!

**Comment by Nikita128** [comment]
I've noticed in your documentation that you haven't yet implemented RFC 8252.
Does it mean that this feature will come with full RFC 8252 support or is it possible to implement somehow separate from it?

**Comment by Sephster** [comment]
Apologies for the delay in responding @Nikita128 - this is something we'd be happy to support. If you want to submit a PR we'd be happy to take a look at it.

I'm going to close this in favour of #1188 as it was open first. Thanks
