### ISSUE TITLE
refresh token ttl after generating the token

### ISSUE THREAD

**Issue by ceresaconsultoria** [thephpleague/oauth2-server#1218]
```JSON
{
      "token_type": "Bearer",
      "expires_in": 3600,
      "access_token": "[...]",
      "refresh_token": "[...]"
}
```

how to send the ttl of the refresh token?

only comes the token expire_in.

**Comment by eugene-borovov** [comment]
This information is encoded in the [refresh token](https://github.com/thephpleague/oauth2-server/blob/a60313319786ca17973791dab6cf99f13b43d976/src/ResponseTypes/BearerTokenResponse.php#L41).

**Comment by ceresaconsultoria** [comment]
Don't have a way to send this data with json?
--



Em sex., 23 de abr. de 2021 às 00:55, Eugene Borovov <
***@***.***> escreveu:

**Comment by Sephster** [comment]
The refreshTokenGrant has a function `setRefreshTokenTTL` which you can use to change the default TTL. Hope this helps!

**Comment by eugene-borovov** [comment]
> Don't have a way to send this data with json? 

```php
$tokenData = json_decode(base64_decode(strtr(explode('.', $refreshToken['refresh_token'], 3)[1], '-_', '+/')), true)
```
