### ISSUE TITLE
I got this issue when upgrade to 8.3.0 "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed"

### ISSUE THREAD

**Issue by hungcrush** [thephpleague/oauth2-server#1232]
Hi, Please help me how to fix this issue:

"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed"

When I downgrade to 8.2.4 it works well.. 

I'm using Laravel Passport

Sorry for my english not well..
Thank you

**Comment by exception0x876** [comment]
It breaks because of the changed condition here

src/Grant/AbstractGrant.php line 241
if (\is_string($clientId))

Laravel Passport uses integers for $clientId

Previously the condition was checking is_null so it worked just fine.

**Comment by hungcrush** [comment]
> It breaks because of the changed condition here
> 
> src/Grant/AbstractGrant.php line 241
> if (\is_string($clientId))
> 
> Laravel Passport uses integers for $clientId
> 
> Previously the condition was checking is_null so it worked just fine.

Thank you so much. I got it

**Comment by Sephster** [comment]
Reverted the offending check 👍
