### ISSUE TITLE
FATAL: Trying to include an un existing class

### ISSUE THREAD

**Issue by itay-moav** [thephpleague/oauth2-server#1244]
In file src/AuthorizationValidators/BearerTokenValidator.php
You have the following code 
```
        $this->jwtConfiguration->setValidationConstraints(
            \class_exists(StrictValidAt::class)
                ? new StrictValidAt(new SystemClock(new DateTimeZone(\date_default_timezone_get())))
                : new ValidAt(new SystemClock(new DateTimeZone(\date_default_timezone_get()))),
            new SignedWith(
                new Sha256(),
                InMemory::plainText($this->publicKey->getKeyContents(), $this->publicKey->getPassPhrase() ?? '')
            )
        );
```

Notice the \class_exists condition which is done on ```StrictValidAt::class``` This can not work. You need the class **StrictValidAt** to exist for this to work.... which would make this condition moot. 
You must use a simple string syntax there. Autoloader will try to include and fail at that line

**[Wed Aug 18 12:24:56.175459 2021] [php7:warn] [pid 5674:tid 140327830636288] [client 127.0.0.1:41668] PHP Warning:  include_once(Lcobucci/JWT/Validation/Constraint/StrictValidAt.php): failed to open stream: No such file or directory in **

**Comment by eugene-borovov** [comment]
Could you describe your setup? I cannot reproduce this issue. Do you use custom class autoloading?

**Comment by itay-moav** [comment]
I just include the composer autoloader.
But....Check the code itself.
It is pretty clear this is a bug. U are using a class constand to check if
the class exists.
For PHP to know what the class constant is (MyClass::class), It needs to
include said class ... catch 22

**Comment by eugene-borovov** [comment]
Class constant works with unknown class https://3v4l.org/kEpZH
`\class_exists` has second parameter for control autoloading. I tested this code with PHP 7.2 and error reporting E_ALL and I didn`t get  the warning.

**Comment by itay-moav** [comment]
hmmm... maybe I have an autoloader hidden somewhere.
If that is the case, this code will sometimes break, sometimes not.
Try with an autoloader that replaces both \ and _  to / and includes that
file, on top of the vendor autoloader.
include this : str_replace(['\','_'],'/',$class_name) . '.php'

**Comment by eugene-borovov** [comment]
I suggest to use [PSR-0 autoloading](https://getcomposer.org/doc/04-schema.md#psr-0) for legacy code.

**Comment by itay-moav** [comment]
A good idea, but maybe give a facility for other users who might encounter
this issue in the future.
