### ISSUE TITLE
Question: Next step in the authorization server flow: extracting and validating the JWT token?

### ISSUE THREAD

**Issue by tomelsj** [thephpleague/oauth2-server#1261]
Hello, when you have the JWT from the oauth authorization server, what should I do next? I am not very familiar with the oauth, but I feel that I missing some step. Suppose that I want to post some data from the client to the server by the API using the JWT token, how do I validate the token on the server? How do I extract it and identify who sent the request?

**Comment by Sephster** [comment]
You should use the resource server class to intercept and verify that the JWT the client has is valid. Please see [this section of the docs](https://oauth2.thephpleague.com/resource-server/securing-your-api/) for further information. Thanks
