### ISSUE TITLE
any way to customize redirect uri validator?

### ISSUE THREAD

**Issue by yunwuxin** [thephpleague/oauth2-server#1264]
https://github.com/thephpleague/oauth2-server/blob/19dc5e47c465bc9f1804859660b7efe456a40713/src/Grant/AbstractGrant.php#L282-L292

**Comment by Sephster** [comment]
Not at the moment. We haven't opened this up, primarily because the way it functions is specified in the OAuth 2 specs and we try to be spec compliant. Is there something you can't do with the current set up?

**Comment by yunwuxin** [comment]
In my project, i only want to check domain name only，not the whole redirect uri
