### ISSUE TITLE
"league/event": "^2.2" dependency incompatibility with "league/event": "3.0.0"

### ISSUE THREAD

**Issue by caballero03** [thephpleague/oauth2-server#1277]
I had been using "league/event": "^3.0.0" in part of my project but when I installed oauth2-server Composer downgraded Event to v2.2 which has had several name changes into v3.0.0. This breaks existing v3.0.0 code. 

See here: https://event.thephpleague.com/3.0/upgrade-from-2-to-3/

I don't know if this is a issue or maybe I did something wrong when I installed it, but it would appear to me that this may be an oversight.

I have disabled the offending code in my project to continue using Oauth2-server. I may not need to use Event in the future. I just wanted to point this out. Any suggestions or advice would be more than welcome.

**Comment by Sephster** [comment]
Yes at this time we are still on league/event 2.2. We won't upgrade to 3.0 until we release a new major version as I think this will incur breaking changes. Sorry about that and hope it doesn't cause you too many issues
