### ISSUE TITLE
Remove anemic entities

### ISSUE THREAD

**Issue by sylfabre** [thephpleague/oauth2-server#1280]
Hello

While working on leveling up my phpstan config to level 7, I noticed that the interfaces provided by your package lead to anemic entities.

For instance, I have implemented `OAuthAccessToken`  as a Doctrine entity with the following code:

```
/**
 * @ORM\Column
 */
protected \DateTimeImmutable $expiryDateTime;

public function getExpiryDateTime(): \DateTimeImmutable
{
	return $this->expiryDateTime;
}

public function setExpiryDateTime(\DateTimeImmutable $dateTime): self
{
	$this->expiryDateTime = $dateTime;

	return $this;
}
```

I noticed the following issues:
* It is possible to call `getExpiryDateTime()` while no expiration date had been previously set
* All tokens have an expiration date while this data isn't part of the constructor (DDD best practice)

I think that all methods like `setIdentifier()`, `setExpiryDateTime()`, `setUserIdentifier()`, `setClient()`, and `addScope()` should be removed, and the `AccessTokenRepositoryInterface` should be updated to require more arguments while building an object.

Then method [`AbstractGrant::issueAccessToken()`](https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AbstractGrant.php#L449) could be refactored to:
```
$maxGenerationAttempts = self::MAX_RANDOM_TOKEN_GENERATION_ATTEMPTS;

while ($maxGenerationAttempts-- > 0) {
	$accessToken = $this->accessTokenRepository->getNewToken(
		$client,
		$scopes,
		$userIdentifier,
		(new DateTimeImmutable())->add($accessTokenTTL),
		$this->privateKey,
		$this->generateUniqueIdentifier()
	);
	try {
		$this->accessTokenRepository->persistNewAccessToken($accessToken);

		return $accessToken;
	} catch (UniqueTokenIdentifierConstraintViolationException $e) {
		if ($maxGenerationAttempts === 0) {
			throw $e;
		}
	}
}
```

PHPStan has a blog article about that: https://phpstan.org/blog/detecting-unused-private-properties-methods-constants#one-more-thing

What do you think?

_Obviously this a BC breaking change so a PR addressing it should target the v9.0.0_

And thank you for this super useful package 💪

**Comment by Sephster** [comment]
This sounds good in principle! I can't think of any immediate issues and targeting the v9 branch makes sense. My main concern would be that there is a good reason we are using setters that we haven't thought of here. I might be wrong but something is niggling in the back of my head that there is a reason it is set up this way. I might be entirely wrong on that and if I am, would welcome a PR to see how things work. 

Thanks again for the kind words.

I will close this issue for now just to keep the repo reasonably tidy but please feel free to reference if you submit a PR. Thanks so much

**Comment by sylfabre** [comment]
@Sephster OK I'll work on a PR.

What is the timing around the release of version 9? So I know when I should work on such a PR.

**Comment by Sephster** [comment]
I honestly couldn't say at this stage but there is still quite a bit of work to do so I wouldn't expect it to be ready for at least a month. Hope that is helpful and thanks again
