### ISSUE TITLE
Does not enforce key lengths required by RFC 7518

### ISSUE THREAD

**Issue by asgeirn** [thephpleague/oauth2-server#1286]
JWA section [3.3](https://www.rfc-editor.org/rfc/rfc7518#section-3.3) states:

>   This section defines the use of the RSASSA-PKCS1-v1_5 digital signature algorithm as defined in [Section 8.2 of RFC 3447](https://www.rfc-editor.org/rfc/rfc3447#section-8.2) [[RFC3447](https://www.rfc-editor.org/rfc/rfc3447)]  (commonly known as PKCS #1), using SHA-2 [[SHS](https://www.rfc-editor.org/rfc/rfc7518#ref-SHS)] hash functions.
>
>   A key of size 2048 bits or larger MUST be used with these algorithms.

JWA is stated as an implementation requirement in RFC 7519, section 8.

As a consequence, standards-compliant JWT libraries like JOSE refuse to validate access tokens issued using this library.

**Comment by Sephster** [comment]
The JWTs we issue aren't encrypted. They are just signed so I don't think we need to comply with that section of the RFC:

>Support for encrypted JWTs is OPTIONAL.  If an implementation
   provides encryption capabilities, of the encryption algorithms
   specified in [[JWA](https://datatracker.ietf.org/doc/html/rfc7519#ref-JWA)], only RSAES-PKCS1-v1_5 with 2048-bit keys
   ("RSA1_5"), AES Key Wrap with 128- and 256-bit keys ("A128KW" and
   "A256KW"), and the composite authenticated encryption algorithm using
   AES-CBC and HMAC SHA-2 ("A128CBC-HS256" and "A256CBC-HS512") MUST be
   implemented by conforming implementations.  It is RECOMMENDED that
   implementations also support using Elliptic Curve Diffie-Hellman
   Ephemeral Static (ECDH-ES) to agree upon a key used to wrap the
   Content Encryption Key ("ECDH-ES+A128KW" and "ECDH-ES+A256KW") and
   AES in Galois/Counter Mode (GCM) with 128- and 256-bit keys
   ("A128GCM" and "A256GCM").  Support for other algorithms and key
   sizes is OPTIONAL.

I don't think the JWT library we use currently supports JWE but should this change, I will of course take a second look at this. Happy to discuss further if you have further comments. Thank you for getting in touch regarding this

**Comment by asgeirn** [comment]
This issue is related to **JWS**, not JWE.  The RS256, RS384 and RS512 signature algorithms all require an RSA key with modulus length at least 2048 bits.

**Comment by lcobucci** [comment]
@asgeirn I believe this is something for the underlying library. We realised we missed the minimum key size for HMAC algorithms and as I was about to release 4.2.0 I saw this.

More info in: https://github.com/lcobucci/jwt/issues/854

**Comment by lcobucci** [comment]
@Sephster @alexbilbie the implementation will be similar to https://github.com/lcobucci/jwt/pull/835, so an exception will be raised when receiving short keys.

**Comment by Sephster** [comment]
Thanks. Will revisit this shortly. Cheers for the heads up

**Comment by lcobucci** [comment]
Implemented in https://github.com/lcobucci/jwt/pull/855 and going to be released in 4.2.0 :+1:
