### ISSUE TITLE
How do I get a token by $tokenId

### ISSUE THREAD

**Issue by t3touch** [thephpleague/oauth2-server#1294]
I'm struggling with the revokeRefreshToken($tokenId) method inside my RefreshTokenRepository. Which is the right way to get the refresh token by $tokenId and how can I revoke/invalidate the token?

**Comment by eugene-borovov** [comment]
This [example](https://github.com/thephpleague/oauth2-server/blob/master/examples/public/refresh_token.php) is a good start.

**Comment by t3touch** [comment]
Thanks. But it does not show how to identify or revoke an existing refresh token by $tokenId.

**Comment by eugene-borovov** [comment]
Just remove the token from a storage. It may be hard or soft delete.
There is an [example](https://github.com/mezzio/mezzio-authentication-oauth2/blob/2.5.x/src/Repository/Pdo/RefreshTokenRepository.php) with soft delete.

**Comment by t3touch** [comment]
Ahhh. Ok, I misunderstood some things ;-) 
Thanks
