### ISSUE TITLE
How to persist tokens in mysql

### ISSUE THREAD

**Issue by t3touch** [thephpleague/oauth2-server#1296]
Hi, can anybody give me some hints how to persist tokens in a mysql database?

**Comment by t3touch** [comment]
After sometime I think I understand how to do this ;-)

**Comment by Sephster** [comment]
My apologies for not getting back to you in time but I'm glad you got it sorted! If you still have any follow up questions please shout and I will try to get back to you a bit sooner this time. Thank you
