### ISSUE TITLE
Change minimum supported PHP version.

### ISSUE THREAD

**Issue by JimTools** [thephpleague/oauth2-server#1317]
With PHP 7.4 coming to its end-of-life in November 2022, now would be an excellent time to bump the minimum required PHP version of this package allowing the use of typed properties and other newer language features.

Preferably setting the minimum version to 8.0 as this is the lowest supported version.

[PHP Supported Version](https://www.php.net/supported-versions.php)

Update:
I've got a very rough [branch](https://github.com/JimTools/oauth2-server/tree/feature/php-version-bump) branch working.

**Comment by Sephster** [comment]
I'm working on this but as there will be breaking changes introduced, it needs to be a major change

**Comment by JimTools** [comment]
that is understandable, there are a lot of changes but I believe type safety is worth it. 

Is there anything I can do to help, in the meantime?

**Comment by Sephster** [comment]
Nothing thanks Jim. Appreciate the offer though. Hoping to just plod on with it and get it out in the not too distant future.
