### ISSUE TITLE
Symfony 6.2 require

### ISSUE THREAD

**Issue by BudayPavel** [thephpleague/oauth2-server#1322]
Since symfony/security-bundle 6.2: The “Symfony\Component\Security\Core\Security” service alias is deprecated, use “Symfony\Bundle\SecurityBundle\Security” instead. It is being referenced by the “league.oauth2_server.listener.authorization_request_user_resolving” service.

**Comment by Sephster** [comment]
I believe this should be reported to the oauth2-server-bundle package. Please can you report it there? Many thanks 🙏
