### ISSUE TITLE
Offering of help with maintenance

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/oauth2-server#1332]
I noticed that the tests are failing, and this package is not installable on PHP 7.2 due to incorrect dependences, and is not tested on PHP 8.1 or 8.2. I was wondering if you needed some help with the maintenance of this package. I maintain and co-maintain lots of packages, including Guzzle and Laravel, and (not that it has had much love recently) league/factory-muffin-faker. I am happy help out here in whatever ways you need, including pairing if that's what's needed to fix up things here.

**Comment by Sephster** [comment]
Thanks Graham. That's very kind to offer but I should be ok. I welcomed a son at the start of the year so things have been a bit hectic for a while but I've started work on upgrading tests now and getting things in order. Should have an update out in the next few days. 

Thank you for the kind offer though. It is appreciated 👍

**Comment by GrahamCampbell** [comment]
Congratulations. The offer still stands, in any case, including if you want any code review. 🚀

**Comment by GrahamCampbell** [comment]
FYI, the original thing that drove me here was incompatibility with lcobucci/jwt v5. I stopped after seeing that we didn't have a way to test the package would work since it requires PHP 8.1, and we don't have a working test suite yet for PHP 8.1. I'm happy to re-visit this once we have CI going and passing tests as a baseline.
