### ISSUE TITLE
Relation between entities/models

### ISSUE THREAD

**Issue by AurelienPillevesse** [thephpleague/oauth2-server#1357]
I have a question about the organization between the entities/models.
I can see that all (or most) relationships are done by identifiers.

Why aren't relations made between entities directly instead of using string identifiers?

**Comment by Sephster** [comment]
The database implementation is largely up to you. If you want to add relations to enforce referential integrity, you should be able to afaik

**Comment by AurelienPillevesse** [comment]
Thanks for your answer
