### ISSUE TITLE
Why setUserIdentifier, not setUser?

### ISSUE THREAD

**Issue by DarthLegiON** [thephpleague/oauth2-server#1376]
Hello!

I'm using this package with Symfony and making `AccessToken` and `AuthCode` entities with Doctrine ORM. All relations are good, except of one: `TokenInterface` has `setUserIdentifier` method that accepts id. In Doctrine, making associations you should pass entire entity inside assiciated entity to make it work. And my new token entity unfortunately doesn't allow it, because it accepts user id.

The only place it's set is `AbstractGrant:501`:
```php
$authCode->setUserIdentifier($userIdentifier);
```
This value is passed from `AuthenticationServer:363`:
```php
$authorizationRequest->getUser()->getIdentifier(),
```
An UserEntityInterface entity may be simply passed there without resolving the id, and everything would be nice. Why?

The same situation is with `getNewToken` method of `AccessTokenRepositoryInterface`. This just confusing me so much, and makes to seek for ugly solutions to make Doctrine relations work. Maybe you could provide me a workaround? Thanks!

**Comment by Sephster** [comment]
Have you looked at the [bundle](https://github.com/thephpleague/oauth2-server-bundle) for Symfony? It might be easier to integrate with your application using it

**Comment by DarthLegiON** [comment]
@Sephster Unfortunately, we cannot use it as we have old Symfony version and not updated yet. But it's a good idea to look there for a workaround, thanks.

**Comment by DarthLegiON** [comment]
@Sephster I see that the Symfony bundle doesn't make any foreign keys in the persistense entities and just fills DB with [schema initialization code](https://github.com/thephpleague/oauth2-server-bundle/blob/master/src/Persistence/Mapping/Driver.php). It doesn't suit our requirements, we should make database manipulations with migrations.

I just cannot understand why in this particular field you don't operate interface and use id. It doesn't make any sense for me.

**Comment by Sephster** [comment]
I can't speak as to why the code is like that as I didn't write the lines you are referencing. I am not sure why this would have such a bearing on your application code though. Are you able to share example code? 

I believe people have successfully implemented this lib using Doctrine as the backend in the past as this issue hasn't been raised before so I'm hoping the fix can be done in userland rather than this codebase if possible

**Comment by DarthLegiON** [comment]
Of course, I already found a workaround, but it looks a bit ugly.

**Comment by sgoranov** [comment]
I also wonder why the User entity is not passed instead the identifier . This one is used only here:

_vendor/league/oauth2-server/src/Grant/AbstractGrant.php_
```php
    protected function issueAuthCode(
        DateInterval $authCodeTTL,
        ClientEntityInterface $client,
        $userIdentifier,
        $redirectUri,
        array $scopes = []
    ) {
        $maxGenerationAttempts = self::MAX_RANDOM_TOKEN_GENERATION_ATTEMPTS;

        $authCode = $this->authCodeRepository->getNewAuthCode();
        $authCode->setExpiryDateTime((new DateTimeImmutable())->add($authCodeTTL));
        $authCode->setClient($client);
        $authCode->setUserIdentifier($userIdentifier);
```

_vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php_
```php
        if ($authorizationRequest->isAuthorizationApproved() === true) {
            $authCode = $this->issueAuthCode(
                $this->authCodeTTL,
                $authorizationRequest->getClient(),
                $authorizationRequest->getUser()->getIdentifier(),
                $authorizationRequest->getRedirectUri(),
                $authorizationRequest->getScopes()
```
And it looks like there is no problem to pass the whole User entity.

**Comment by DarthLegiON** [comment]
@sgoranov yes, I'm talking about the same: always when we're going to link accessToken/authCode to a user, we can pass User entity and loose nothing. But looks like the code base is already cannot be adapted for this, and it will break backward compatibility.

**Comment by Sephster** [comment]
The original developer of this is no longer involved in the project so I can't speak as to why it was implemented that way. Do you have a link to the Doctrine behaviour stating you must pass an object to create a relation? Thanks

**Comment by Sephster** [comment]
Closing due to lack of response
