### ISSUE TITLE
Test Refresh Token Fails on Google Home Test Suite

### ISSUE THREAD

**Issue by w1lldone** [thephpleague/oauth2-server#1379]
Hello everyone, i've been using [oauth2-server](https://github.com/thephpleague/oauth2-server), along with Laravel Passport to build an integration for Google Home Cloud to Cloud. We have encountered a test failure within the Google Home Test Suite:

![image](https://github.com/thephpleague/oauth2-server/assets/19965509/b32b0d58-c7f2-4134-8f99-251e3e11f8d0)

> Error happened during refresh with invalid token. This is likely because partner didn't return invalid_grant with 400. Please check Cloud log if this provider has been associated with cloud project id.;Refresh token has been rotated. This is not forbidden, however we do not see much benefit that rotating the refresh token can provide but the potential problem it has. We also tried to refresh token with the old refresh token after it has been rotated. Refresh didn't work, this means partner invalidated the old refresh token right after the rotation. Partners shall only invalidate the old refresh token after seeing we use the new one to ensure we got it successfully.;: expected 'FAIL' to not equal 'FAIL'

Is anyone else experiencing this issue?

**Comment by eugene-borovov** [comment]
Try to not revoke refresh token.

**Comment by Sephster** [comment]
Aye, try to turn off the revoking of refresh tokens. This can be done in the AuthorizationServer class. There is a public function called `revokeRefreshTokens`. Thanks @eugene-borovov
