### ISSUE TITLE
Wrong Type in DocBlock 3rd param `AbstractGrant::issueAccessToken`

### ISSUE THREAD

**Issue by tonybolzan** [thephpleague/oauth2-server#1391]
In class `AbstractGrant::issueAccessToken` 3rd param `$userIdentifier` must be equal to `AccessTokenRepositoryInterface::getNewToken` 3rd param.

Change `@param string|null $userIdentifier` to `mixed` in [AbstractGrant.php#L441](https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AbstractGrant.php#L441) like in [AccessTokenRepositoryInterface.php#L27](https://github.com/thephpleague/oauth2-server/blob/master/src/Repositories/AccessTokenRepositoryInterface.php#L27)

**Comment by Sephster** [comment]
Thanks for reporting this. It should be fixed in #1402
