### ISSUE TITLE
Compatibility on interfaces

### ISSUE THREAD

**Issue by JoMo1970** [thephpleague/oauth2-server#1413]
Hello,

I am trying to use this framework but I am consistently hitting the below issue:

Fatal error: Declaration of OAuth2ServerExamples\Repositories\ClientRepository::getClientEntity(string $clientIdentifier): ?League\OAuth2\Server\Entities\ClientEntityInterface must be compatible with League\OAuth2\Server\Repositories\ClientRepositoryInterface::getClientEntity($clientIdentifier)

I cannot seem to get passed this problem. It happens when the AuthorizationServer object initializes and I try the /authorize flow. I might have a configuration wrong but I am not sure. Anybody have any ideas? Thanks in advance.

**Comment by eugene-borovov** [comment]
Hello, @JoMo1970.

This is a PHP issue. Make your implementation fully compatible with an interface. I suggest to set up type hints in method declaration.

**Comment by JoMo1970** [comment]
Understood. Appreciate the feedback.
