### ISSUE TITLE
Initial Configuration

### ISSUE THREAD

**Issue by JoMo1970** [thephpleague/oauth2-server#1415]
Hello,

I am very new to using this framework. To initialize the oauth2 server, where do I configure the client id and other parameters that are to be used to validate incoming client ids, etc? I am not finding clear documentation on how to do this. I appreciate any help.

**Comment by pat0s** [comment]
Hi @JoMo1970 ,

I wouldn't call it a configuration. You can have tons of clients, which should be registered on your OAuth/OpenID server. 

If we skip the client registration process, you need some kind of storage (database) to store individual clients and information about them. Then you are able to validate the client's information from incoming requests with the stored one. 

A client is validated in the method `validateClient()`. You can find this method in [ClientRepositoryInterface.php](https://github.com/thephpleague/oauth2-server/blob/master/src/Repositories/ClientRepositoryInterface.php). Everything you have to do is connect your application to your storage (database). Create some repository class which implements this interface and create an implementation of this method. 

I hope you find this helpful. If you need any help don't hesitate to contact me.

**Comment by pat0s** [comment]
@JoMo1970, to better understand the whole process of validation, take a look at the method `validateClient()` in the class [AbstractGrant.php](https://github.com/thephpleague/oauth2-server/blob/2ed9e5f65045bebf9e99c33ef1558dcd6d0206b7/src/Grant/AbstractGrant.php).

**Comment by Sephster** [comment]
I would also recommend looking at the /examples directory which contains some examples of working solutions for the grants. Thank you for your help here @pat0s - @JoMo1970 if you are still having issues please do let us know here and I'll do my best to assist you.
