### ISSUE TITLE
ClientCredentials with refresh token

### ISSUE THREAD

**Issue by pavelwitassek** [thephpleague/oauth2-server#1438]
Are any plans to support ClientCredentials flow with issuing refresh token?

**Comment by hafezdivandari** [comment]
According to RFC 6749, [client credentials grant doesn't include a refresh token](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.3:~:text=A%20refresh%20token%20SHOULD%20NOT%20be%20included.).

**Comment by pavelwitassek** [comment]
Ok, thanks.
