### ISSUE TITLE
Clarification Needed: Purpose of src/ Folder in OAuth2 Repository with Slim4 Integration

### ISSUE THREAD

**Issue by viniribeirossa** [thephpleague/oauth2-server#1448]
Hello, friends! 

I'm new to using Slim4, and I want to implement OAuth2 and JWT in my development project. I cloned this repository, but I'm a bit confused. There are two folders: src/ and examples/. The examples folder is self-explanatory, but src/ is located at the same root level as examples. The src/ folder contains various subfolders and files. My question is: is this src/ folder part of the OAuth2 dependencies, or is it also example code?

**Comment by Sephster** [comment]
The src file contains the actual code for the OAuth2 server. The examples folder contains an example implementation of much of the src files using Slim. Hope this helps!

**Comment by viniribeirossa** [comment]
> The src file contains the actual code for the OAuth2 server. The examples folder contains an example implementation of much of the src files using Slim. Hope this helps!

Sorry for the delay. Thanks for clarifying the doubt and helping me with this.
