### ISSUE TITLE
Password Grant Deprecated

### ISSUE THREAD

**Issue by jleonardolemos** [thephpleague/oauth2-server#1463]
Password Grant was deprecated at 2.1 version of the OAuth spec. I am i little concerned because i have too much first party apps using Password Grand as the main authentication option.

Is this something that we should be concerned of? Or this oauth2 server implementation will continue to provide the the Password Grant for ever?

**Comment by Sephster** [comment]
I think 2.1 is still in draft status but as soon as it becomes an RFC, we will likely deprecate the password grant. I would recommend moving off this as it isn't recommended any more.
