### ISSUE TITLE
Add an option to always expose the `interval` param for the device code grant

### ISSUE THREAD

**Issue by erickskrauch** [thephpleague/oauth2-server#1464]
The title. I want to always expose the `interval` param. Clients aren't always responsible for reading the standard to know that the poll interval defaults to 5 seconds. Microsoft and Google always return this parameter.

My suggestion is simply to remove the next condition:
https://github.com/thephpleague/oauth2-server/blob/7b9ec37d5077c0382aa3748c6e125c5408d5adb9/src/ResponseTypes/DeviceCodeResponse.php#L48-L50

**Comment by hafezdivandari** [comment]
You may refer to #1410
