### ISSUE TITLE
Missing `8.5.x` branch causing latest 8.x release to be made with outdated.

### ISSUE THREAD

**Issue by crynobone** [thephpleague/oauth2-server#1468]
This can be fixed by:

```
git checkout 8.5.4

git checkout -b 8.5.x

git merge 8.4.x
```

then release `8.5.5`

**Comment by Sephster** [comment]
Will have this released in the next half hour. Normally would just ask you to upgrade to v9 but appreciate there are some long standing PRs stopping that move just now. Hopefully won't need to do any more such changes on the v8 branches as most as now closed off
