### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alexbilbie** [thephpleague/oauth2-server#193]
Now that `v4` has been merged into `develop` branch I can work on the documentation.

This issue is for tracking new documentation which will be located at http://oauth2.thephpleague.com/

TODO:

- [x] Resource server
- [x] Auth code grant
- [x] Client credentials grant
- [x] Password grant
- [x] Refresh token
- [x] Creating your own grants
- [x] Subscribing to events
- [x] Creating your own token identifier generator
- [ ] Creating your own token types
- [ ] Integration with frameworks
- [ ] Upgrading from v3

**Comment by zzal** [comment]
There's no implementation code example for «Authorization server with refresh token grant».
When the Access Token expires, how do we use the Refresh Token to require a new one?

**Comment by alexbilbie** [comment]
@zzal http://oauth2.thephpleague.com/authorization-server/refresh-token-grant/

**Comment by zzal** [comment]
> When the refresh token grant is enabled, a refresh token will automatically be created 
> with access tokens issued requested using the authorization code or resource owner password 
> credentials grants.

So the Access Token is re-issued automatically when Refresh Token is present?
If this is the case, it's no working for me… I must be missing something.

**Comment by alexbilbie** [comment]
If you have enabled the refresh token grant, when you use the auth code or resource owner password credentials grant a refresh token will be issued along with the access token.

You can then use the refresh token to request a new access token later on.

**Comment by zzal** [comment]
Yes I understand that: I have set a Password grant type along with a Refresh Token grant. I do receive a Refresh token with my Access Token.
The question remains: **how** do I use the Refresh Token to get a new Access Token? (which is sent along my Access Token in each and every request I do).

**Comment by alexbilbie** [comment]
Send a POST request to your access token endpoint (the same one that you use to get the access token using password grant) but the grant type is `refresh_token` instead.

There are extensive examples in the `tests/` folder e.g. https://github.com/thephpleague/oauth2-server/blob/master/tests/unit/Grant/RefreshTokenGrantTest.php#L425

**Comment by zzal** [comment]
Ok, thanks! Now I understand…
Sorry for the inconvenient and thanks for your time. :)

**Comment by nazan** [comment]
Yep, I hav the same problem as @zzal 
refreshed access token does not get the same scope as original access token.

**Comment by ashleydw** [comment]
Under the relational example, it'd also be nice to have some documentation on the expected table structure.

**Comment by peteclark3** [comment]
I ended up here following links related to more Storage implementations.  Yet I don't see it on the todo list.  Is this still a todo?
