### ISSUE TITLE
Integration with StackPHP

### ISSUE THREAD

**Issue by alexbilbie** [thephpleague/oauth2-server#200]
Integration with [StackPHP](http://stackphp.com/)

**Comment by zerkms** [comment]
Why to tie with frameworks when it's an independent library?

**Comment by hannesvdvreken** [comment]
StackPHP is not a framework. It's a framework interoperability tool.

**Comment by zerkms** [comment]
@hannesvdvreken why to tie with **anything**?

I've taken it and without any problems used with symfony.

**Comment by hannesvdvreken** [comment]
Yeah, but people like libraries with utility classes that they can just use to tie it in their application in no time.

**Comment by zerkms** [comment]
So why to put everything into one repository/project?

**Comment by hannesvdvreken** [comment]
It's better to add a stackphp middleware than to add framework specific classes for every single framework.

**Comment by zerkms** [comment]
@hannesvdvreken the question was: why to add it to the library? Why not create a separate project that provides integration?

Composition, you know.

**Comment by hannesvdvreken** [comment]
StackPHP will only be a dev dependency.

**Comment by zerkms** [comment]
@hannesvdvreken the question is still: why a library need to know about environment it will be used it?

**Comment by hannesvdvreken** [comment]
I would agree with you if it would be symfony or zend specific classes, but StackPHP is meant to be used in any application. So it's optional but also an invitation to use good app design.

This will be my last response, sorry, as I don't have more time to discuss. Have a nice day.

**Comment by zerkms** [comment]
It violates SRP.

But hey, it's your project, design it as you wish.

**Comment by hannesvdvreken** [comment]
I just noticed this is a 7 month issue. Don't worry about it, it probably will not be executed any time soon ;-)

**Comment by alexbilbie** [comment]
I've just woken up in my timezone so to answer your questions, the
middleware will be a single class with no additional dependencies required
because anyone implementing it will already have pulled them in themselves.

**Comment by hannesvdvreken** [comment]
As I said: just a dev dependency.

**Comment by zerkms** [comment]
> just a dev dependency.

Dev dependencies are not installed by default when a library is a dependency itself. I cannot see how it can be a pure dev dependency :-)

**Comment by alexbilbie** [comment]
What's a dev dependency? As I said implementing the middleware won't result
in any new dependencies being added to the project

**Comment by hannesvdvreken** [comment]
`require-dev`

**Comment by zerkms** [comment]
@alexbilbie middleware is integration. Why not have it separately?

OAuth library provides the protocol implementation, why spoil it with information about the environment it will be hosted in?

Especially keeping in mind that StackPHP is not an industry standard and not everyone uses them.

**Comment by zerkms** [comment]
@hannesvdvreken it **will not** be a dev dependency. It will be a middleware (in terms of StackPHP) implementation.

So a class that has nothing to do with library directly, just a glue layer with a specific "architecture"

**Comment by zerkms** [comment]
@alexbilbie simple example: https://github.com/thecodingmachine/silex-middleware

So they implemented a middleware for silex outside of siles, not as a part of it.

**Comment by alexbilbie** [comment]
I agree. It'll be a separate package. But as that separate package doesn't exist yet I'm just tracking it in here.

**Comment by zerkms** [comment]
White begins and wins!

Sorry for being nasty and/or annoying, I wish the project the best design :-)

**Comment by alexbilbie** [comment]
Closing for now; v5 will include PSR7 middleware
