### ISSUE TITLE
Add support for JWT

### ISSUE THREAD

**Issue by otherjohn** [thephpleague/oauth2-server#209]
Any timeline of JWT support? And is it possible to use the "Custom" grant types to make it work until then?

**Comment by patrickheeney** [comment]
Is there anything we can do to help with the JWT implementation?

**Comment by alexbilbie** [comment]
@patrickheeney at the moment no. I think JWT needs a lot more thought into how to properly implement it

**Comment by bernier** [comment]
+1

I just was testing things and this actually works when updating PasswordGrant.php line 165

        try {
            // attempt to verify the credentials and create a token for the user
            if(!$jwt_token = JWTAuth::attempt(array('email' => $username, 'password' => $password))) {
                throw new Exception\InvalidRequestException('invalid_credentials');
            } else {
                $this->server->getTokenType()->setParam('access_token', $jwt_token);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            throw new Exception\InvalidRequestException('could_not_create_token');
        }

I'm aware there's a lot more to do.

**Comment by alexbilbie** [comment]
v5 of this library will have built in JWT support

**Comment by alexbilbie** [comment]
I've added an example of how JWT support will work here - https://github.com/thephpleague/oauth2-server/blob/v5/examples/public/jwt.php

**Comment by alexbilbie** [comment]
V5 now issues JWT out of the box
