### ISSUE TITLE
invalid_request error in grant_type=password with angularjs http request.

### ISSUE THREAD

**Issue by arjundas** [thephpleague/oauth2-server#261]
I am Creating RESTful API with AngularJS and Laravel, I implement OAuth2-server in laravel and testing it.

i set grant_type in config file of package : 

```
    'grant_types' => [
        'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => function($username, $password) {
                return Auth::validate([
                    'email'    => $username,
                    'password' => $password,
                ]);
            },
            'access_token_ttl' => 604800
        ]
    ],
```

then in route.php file : 

```
Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});
```

And in Angular JS : 

```
    $http({
        url: 'http://url/to/oauth/access_token?grant_type=password&username=johndoe&password=A3ddj3w',
        method: "post",
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
    }).then(function(response) {
        console.log(response);
    }, function(response) {
        console.log(response);
    });
```

when i run above angular code it give error : `invalid_request` :+1: 

```
{
    "error":"invalid_request",
    "error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."
}
```

Please tell me where i made a mistake.

**Comment by ajaysodhi** [comment]
var promise = $http({
							        url: 'url/to/oauth/access_token',
							        method: "post",
							        async: true,
									crossDomain: true,
							        data: $.param({username : 'UNAME', password : 'PWD', "grant_type": "client_credentials", "scope": "all"}),
							        headers: {"authorization": "Basic Base64Encodedlogin:pwd_String", 'Content-Type': 'application/x-www-form-urlencoded'},
							    }).then(function(response) {
							        console.log(response);
							        alert("response.data.access_token: " + response.data.access_token); 
									return response.data.access_token;
							    }, function(response) {
							        console.log(response);
							        return promise;
							    });


This is how I used it.

**Comment by ajaysodhi** [comment]
Thanks @arjundas. This really helped me.
