### ISSUE TITLE
authParams serialisation problem

### ISSUE THREAD

**Issue by maknz** [thephpleague/oauth2-server#272]
I've come across an issue when following the auth code example from the docs:

```php
$authParams = $server->getGrantType('authorization_code')->checkAuthorizeParams();
```

The $authParams then need saved to a session. In my case, I'm serialising it and putting it into a Redis cache, but I assume both that and PHP sessions are implemented by serialising. This is problematic because the embedded `server` instance in the client entity can be very big, and contains complex constructs like closures which can't be serialised.

I can probably fish out the primitives (everything except the client) from $authParams, and then store the ID of the client so I can reconstruct the object later from the client storage. But that's a bit ugly and digs down into the implementation. Would there be a better way?

**Comment by jonnnnyw** [comment]
+1 for this. The scope entities in the auth params are also an issue.

A workaround is to extend your entity classes and the Serializable interface:

```
use League\OAuth2\Server\Entity\ClientEntity as BaseClient;

class Client extends BaseClient, \Serializable {

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->name
        ));
    }

    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->name
        ) = unserialize($serialized);
    }
}
```

Then return the extended entities from the client storage. This allows the objects to be serialized/unserialized in the session.

This could be incorporated into your entity classes.

Another solution would be to pass back the client and scope ids as strings in `checkAuthorizeParams` and handle instantiation on the entities in the grant class.
