### ISSUE TITLE
Slim integration

### ISSUE THREAD

**Issue by antoinerrr** [thephpleague/oauth2-server#283]
Hi, Is there a tutorial to help us for the integration of oath in Slim ? 

Found this but https://github.com/thephpleague/oauth2-server/issues/116 No responses.

Thanks by advance and sorry for my _bad_ english

**Comment by JHKennedy4** [comment]
The examples shown still rely on the HttpFoundation Request objects, Slim uses a different Request object. Is the library compatible with Slim as is or do we need to wrap the Request object for compatibility? It's also unclear whether this can be implemented as shown in the examples or needs to be implemented as middleware.

Happy to contribute back documentation on the solution, just need some pointers in the right direction. Thanks!
