### ISSUE TITLE
Downloadable example

### ISSUE THREAD

**Issue by austinkregel** [thephpleague/oauth2-server#289]
Is there any downloadable example for this version of the oauth2 server? I took a look bshaffer's example and I was so lost, I couldn't figure out what  was what and how to change things. I have been trying for a week now to utilize your version of the server and I can't figure out what I still need. I've looked around and can't find any good examples that don't use some third party extensive library. I'm just looking for a lightweight, deployment system to assist in helping people learn how to use the server. Any example would be nice, and before you refer  me to the docs website. I tried following it, and I must not know enough because I couldn't get anything to work. I have a feeling I am missing an .htaccess file with special configurations.

**Comment by alexbilbie** [comment]
Have you definitely correctly implemented all of the required storage interfaces - http://oauth2.thephpleague.com/implementing-storage-interfaces/ ?

**Comment by austinkregel** [comment]
I double, and triple checked everything, as far as code goes, everything appears to be correct. It doesn't look like I am missing anything.
