### ISSUE TITLE
Fatal error: Class 'League\OAuth2\Server\AuthorizationServer' not found

### ISSUE THREAD

**Issue by JHKennedy4** [thephpleague/oauth2-server#291]
It appears that League\OAuth2 is not being added to composer/autoload_namespaces. I'm struggling to figure out why.

Currently using version 4.1.

Code fails at:
    $server = new \League\OAuth2\Server\AuthorizationServer;

**Comment by alexbilbie** [comment]
To confirm, what is the composer command you're using?

**Comment by alexbilbie** [comment]
I've just done the following and it works for me:

```bash
mkdir /tmp/oauth-test
cd /tmp/oauth-test
composer require league/oauth2-server
touch test.php
```

The contents of `test.php` are:

```
<?php

include('vendor/autoload.php');

$server = new \League\OAuth2\Server\AuthorizationServer;
```

Running `php test.php` I get a code 0 exit which means execution was successful.

**Comment by JHKennedy4** [comment]
I used `composer require league/oauth2-server`

composer.json looks like this:
```
 {
    "require-dev": {
        "10up/wp_mock": "dev-master",
        "phpunit/phpunit": "4.3.*"
    },
    "require": {
        "league/oauth2-server": "~4.1"
    }
}
```

I've tried using `composer dump-autoload` a few times to regenerate the autoload files, but no luck thus far. I've got `require 'vendor/autoload.php'` in wordpress/index.php

**Comment by JHKennedy4** [comment]
:facepalm: the include is just in the wrong spot. Still not seeing the League in the namespaces file, but I guess that doesn't work the way I thought it did. Thanks for your help.
