### ISSUE TITLE
Passing data via Content-Type: application/json

### ISSUE THREAD

**Issue by kfuchs** [thephpleague/oauth2-server#292]
The previous version allowed you to pass in the input parameters and hence it was easy to use data passed via `application/json`. In this new version one would have to insert the data into the `Symfony\Component\HttpFoundation\Request->request` object them selves. Is there anything wrong with this approach if I wanted to add this feature when implementing this package?

Yes, I know the RFC states "using the "application/x-www-form-urlencode format" everywhere but it doesn't say anything about dis-allowing other data types. I see no harm in supporting multiple datatypes as an addition feature. Thoughts?

**Comment by hannesvdvreken** [comment]
@kfuchs You can use `AuthorizationServer::setRequest(Request $request)` to inject your own (populated) version of the Symfony request.
