### ISSUE TITLE
Associating scopes with users?

### ISSUE THREAD

**Issue by kfuchs** [thephpleague/oauth2-server#293]
Is there anything wrong with associating scopes with users and utilizing them as the roles granted to users?

**Comment by alexbilbie** [comment]
I implemented the [events subsystem](http://oauth2.thephpleague.com/authorization-server/events/) for scenarios like this.

When the `session.owner` event is fired, your listener can get the owner type and owner ID from the session. You can then implement your own logic to look up the users role and then call `associateScope` on the session entity for each scope you wish to assign.

**Comment by alexbilbie** [comment]
Closing this for now. Please follow up if you have any more questions
