### ISSUE TITLE
Refreshed access token (via refresh_token grant) does not get the same scope as original access token

### ISSUE THREAD

**Issue by nazan** [thephpleague/oauth2-server#297]
In the following method, notice that SessionEntity is never associated with the requested ScopeEntities.

> League\OAuth2\Server\Grant\AuthCodeGrant::newAuthorizeRequest(...)

Also notice that in the following method, ScopeEntities are associated to SessionEntity but the save() method of SessionEntity is never called (therefore not persisted into database).

> League\OAuth2\Server\Grant\AuthCodeGrant::completeFlow()

However in the following method (when using refresh_token grant type), it tries to retrieve ScopeEntities from the SessionEntity which gives an empty array. As a result the new access token ("REFRESHED" token) is never re-populated with the scopes from the original access token.

> League\OAuth2\Server\Grant\RefreshTokenGrant::completeFlow()

**Comment by nazan** [comment]
Care to shed some light on this issue? Anyone? In case my question is not understood.. Basically here is the problem:

- I want to use refresh_token grant type.
- I have already set everything up and I'm even getting a refreshed accessed token.
- But the problem is the refreshed access token does not get the same scopes as the original access token.

Example:
Suppose access token A has scopes 'abc,xyz,def'. When access token A expires I'm using refresh token grant mechanism to get a refreshed access token B. However access token B does not have scope 'abc,xyz,def'. In fact access token B does not have any scope at all.

**Comment by Fuxy22** [comment]
I can confirm this bug. Just ran into it myself.

Has this been fixed? The 4.0.0 milestone seems to have come and gone.

**Comment by nazan** [comment]
I get this problem in version 4.0.*

**Comment by gtux** [comment]
I get this same problem. I'd fix like this:

```
    public function newAuthorizeRequest($type, $typeId, $authParams = [])
    {
        // Create a new session
        $session = new SessionEntity($this->server);
        $session->setOwner($type, $typeId);
        $session->associateClient($authParams['client']);
        // $session->save();  not yet

        ...

        foreach ($authParams['scopes'] as $scope) {
            $authCode->associateScope($scope);
            $session->associateScope($scope);   // associate the scope with session
        }

        $session->save();   // here it must save it
        $authCode->setSession($session);
        $authCode->save();

        return $authCode->generateRedirectUri($authParams['state']);
    }
```
