### ISSUE TITLE
OwnerID always set as '1' in sessions table

### ISSUE THREAD

**Issue by mofman** [thephpleague/oauth2-server#298]
I'm having a problem whereby when I successfully authenticate with a username and password, it persistantly adds the ID 1 to ower_id; I am expecting to see the correct UserID in the column?

*Here is my grants*

    'grant_types' => [
        'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => function($username, $password) {
                return Auth::validate([
                    'email'    => $username,
                    'password' => $password,
                ]);
            },
            'access_token_ttl' => 604800
        ]
    ],

*My route*

    Route::post('oauth/access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

Is this a bug or am I doing something wrong?

**Comment by giolvani** [comment]
Hi,

I must repeat this question, but change the field...

For me, the owner_type, is always 'user'. I saw it is defined manually on PasswordGrant.php

**Comment by alexbilbie** [comment]
Using the client credentials grant the access token will be a `client`, using password grant the owner of the access token will always be a `user` likewise for authorization code and implicit grants

**Comment by giolvani** [comment]
@alexbilbie thank you!
I'm newbie oauth. I thought it had relationship with ACL
