### ISSUE TITLE
Purpose of sessions and their scopes

### ISSUE THREAD

**Issue by vvllaadd** [thephpleague/oauth2-server#299]
Stupid question here. What is the purpose of the sessions?
Also, what is the purpose of a session scope? What kind of scopes should I insert? Please help me understand its use; perhaps describe a possible scenario where this might be useful.

**Comment by alexbilbie** [comment]
Not a stupid question.

So the session is the core component that maintains a link between a user, a client and a token type. 

For example in the authorisation code flow this is the initial setup:

```
                                                          +--------+     
                                                          |        |     
                                                          | Scopes |     
                                                          |        |     
                                                          +--------+     
                                                                         
                                                               ^         
                                                               |         
                                                               |         
                                                               +         
                                                                         
                   +------+         +---------+         +------------+   
                   |      |         |         |         |            |   
                   | User | <-----+ | Session | +-----> | Auth token |   
                   |      |         |         |         |            |   
                   +------+         +---------+         +------------+   
                                                                         
                                        +                                
                                        |                                
                                        v                                
                                                                         
                                    +--------+                           
                                    |        |                           
                                    | Client |                           
                                    |        |                           
                                    +--------+                                                                         
```

When the auth code is converted to an access token the scopes which were associated with the auth code are copied to the session as well as associated with the access token:

```
                                                                             
                                                                             
                                                                             
                                      +--------+             +--------+      
                                      |        |             |        |      
                                      | Scopes |             | Scopes |      
                                      |        |             |        |      
                                      +--------+             +--------+      
                                                                             
                                           ^                     ^           
                                           |                     |           
                                           |                     |           
                                           +                     +           
                                                                             
                     +------+         +---------+         +--------------+   
                     |      |         |         |         |              |   
                     | User | <-----+ | Session | +-----> | Access Token |   
                     |      |         |         |         |              |   
                     +------+         +---------+         +--------------+   
                                                                             
                                        |                         +          
                                  +-----+                         |          
                                  |                               |          
                                  v                               v          
                                                                             
                             +--------+                   +---------------+  
                             |        |                   |               |  
                             | Client |                   | Refresh Token |  
                             |        |                   |               |  
                             +--------+                   +---------------+
```

We copy the scopes to the session as well as the access token because if we request a new access token using the refresh token, the new access token can have the same scopes as the original token or a reduced subset of the scopes.

Does that make sense?

**Comment by vvllaadd** [comment]
I see, thank you very much for the explanation! There's something wrong with my implementation, as I don't get the scopes copied over.

PS. Couldn't the access token keep track also of the user and client, instead of the session? It seems a bit redundant, as both the session and the access token have the same scopes.

**Comment by alexbilbie** [comment]
> I see, thank you very much for the explanation! There's something wrong with my implementation, as I don't get the scopes copied over.

You probably haven't correctly implemented [`League\OAuth2\Server\Storage\SessionInterface:: associateScope`](https://github.com/thephpleague/oauth2-server/blob/master/src/Storage/SessionInterface.php#L71)

> PS. Couldn't the access token keep track also of the user and client, instead of the session? It seems a bit redundant, as both the session and the access token have the same scopes.

As I said, an access token created with a refresh token might have a subset of the scopes that the original access token. But another access token created later on might require all of the scopes again. You need to store the original set of scopes somewhere.

**Comment by vvllaadd** [comment]
I think there's a bug in the code. Because the session scopes never get saved in the auth code grant flow. The session is saved inside newAuthorizeRequest, but when the flow is completed, the scope is assigned (only to the object) and not saved. I see the function call has been removed recently, to prevent duplicate sessions, but this also discards saving the scopes.

**Comment by alexbilbie** [comment]
The scopes are associated here along with the access token scopes - https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AuthCodeGrant.php#L239-L245

When the `save()` method is called on the session entity the scopes are saved in this call to the storage here - https://github.com/thephpleague/oauth2-server/blob/master/src/Entity/SessionEntity.php#L291-L307

**Comment by vvllaadd** [comment]
The save() method never gets called on the session entity.

**Comment by vvllaadd** [comment]
I fixed it by replacing this line https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AuthCodeGrant.php#L240
with this:
```javascript
$this->server->getSessionStorage()->associateScope($session, $authCodeScope);
```

**Comment by alexbilbie** [comment]
You're quite right @vvllaadd.

It looks like #282 broke this and there's now a conflict.

**Comment by maknz** [comment]
> We copy the scopes to the session as well as the access token because if we request a new access token using the refresh token, the new access token can have the same scopes as the original token or a reduced subset of the scopes.

This I did not realise. I thought it would use the scopes associated to the access token to determine that, but I guess it needs to keep track of the _very_ original scopes, so they can be added and remove between refreshes irrespective of what scopes the access token currently has assigned. Sorry guys.

We'll need another fix for the duplicate session then? I guess in the save it needs to know whether it's already been persisted (has an ID?) and to not call create again?

**Comment by atrauzzi** [comment]
Just getting started with this library, but I'm still confused by the need for sessions as per this explanation:

>As I said, an access token created with a refresh token might have a subset of the scopes that the original access token. But another access token created later on might require all of the scopes again. You need to store the original set of scopes somewhere.

Why don't you just store the scopes against the refresh token?  It would be the only basis by which this arises and would avoid introduction of a term not familiar to the Oauth2 spec.

**Comment by alexbilbie** [comment]
I agree, I've opened #306 to track progress of this

**Comment by alexbilbie** [comment]
I'm closing this, please discuss further in #306

**Comment by ArthurGuy** [comment]
Can you tag a release for the fix in this issue?

Thanks
