### ISSUE TITLE
Single authorization for the same client and same resource owner

### ISSUE THREAD

**Issue by vvllaadd** [thephpleague/oauth2-server#301]
I notice most OAuth2 implementations, for example Google API's, allow only one access token per client and resource owner. This library doesn't seem to offer any particular way for doing the same and by default it allows clients/owners unlimited access tokens, regardless of their requested scopes.
What would be the best way to have the library check if there is already a token issued for a particular client+owner and "refresh" it with the last request? Perhaps add some code inside SessionStorage::create to see if there is a similar session, but I'm not sure how to influence the flow (grant::completeFlow) in such a case.
Perhaps modify the grant class, add a configuration parameter, that will cause the previously issued session+token (for the same client+owner) to be removed. I would like to keep the changes of the library's base code to a minimum but I think it's not possible in this case, unless you consider the case and support it.

P.S. As the OAuth2 is a framework and not a protocol, a difficult to understand and implement one, and requires the developer to figure out its own way of dealing with various aspects, I'm thinking that maybe this library's documentation would benefit from a "Best practices" section with some tips (for example: cleaning expired codes and tokens, protecting the resource owner from allowing the client to get automatic consent (the example app has no protection for this), the situation described above). This will also increase the security of the implementations by helping the developers not miss anything.

**Comment by vvllaadd** [comment]
So I am guessing by the lack of replies that nobody that is using this class is providing the end user any kind of user interface for revoking the authorizations.

**Comment by alexbilbie** [comment]
I was intending on dealing with these issues later - not everyone is on your timezone or has infinite free time, give me a chance.

**Comment by vvllaadd** [comment]
No pressure on you Alex. I was thinking other developers might also follow the discussions here and I was hoping for another opinion on the matter.

**Comment by vvllaadd** [comment]
After some playing with Google's "OAuth 2.0 Playground" I am answering the question myself :) I was mistaken, Google does not provide the same access token, but different ones, it just doesn't show them separately in the list of authorized apps. I guess that's what I will be doing as well: even though there are multiple tokens with different scopes, I will only show "the app" as connected and revoking the access will remove all found tokens.
