### ISSUE TITLE
Create and depend on entity interfaces

### ISSUE THREAD

**Issue by atrauzzi** [thephpleague/oauth2-server#305]
When implementing this library, it would be nicer if the entity requirements were expressed as an interface rather than a base class.

The main issue with base classes is that you highjack/impose entity inheritance in peoples' projects.  For someone who uses Laravel's eloquent (or any other activerecord-like), this means they're manually populating entities with values.

If you wish to bundle default behaviour, you can always include traits for convenience.

**Comment by alexbilbie** [comment]
You're suggestion is actually implemented in the `develop` branch :+1:

**Comment by atrauzzi** [comment]
:tada:

**Comment by atrauzzi** [comment]
Quick question: Is `develop` up to date with things going on in `master` right now, or has it fallen behind a bit?

**Comment by alexbilbie** [comment]
It's probably fallen behind (I've not had much time over the last month to work on the library, that should change now that craziness in my life is over) but most of the changes that are in master are minor and/or examples/docblock/docs improvements so merging master on develop should work reasonably well

**Comment by atrauzzi** [comment]
Awesome.  I'm going to try and get familiar with the library and once you've completed some of the more major pending refactors, I'd like to help with code cleanup and any other small improvements that might occur to me.

**Comment by alexbilbie** [comment]
Thank you @atrauzzi :smile:
