### ISSUE TITLE
Remove `session` concept as it's confusing

### ISSUE THREAD

**Issue by alexbilbie** [thephpleague/oauth2-server#306]

**Comment by ashleydw** [comment]
I'm wondering if you have WIP for this? I'd like to remove the session concept too.

**Comment by atrauzzi** [comment]
I think @alexbilbie is fairly busy right now so I'm taking it upon myself to refactor this package.  Part of this refactor is going to be to remove the session concept.  It's going to take a bit as I'm cleaning up the injection and coupling in the library.

To that end, I think the end result is going to be that authorization tokens, refresh tokens and authorization codes are all going to have a relation to auth codes.  I'm just mentioning this here in case someone notices that I've missed something! ;)

**Comment by alexbilbie** [comment]
I am busy but I'm actually sat doing some updates as I type this.




Only one grant uses auth codes so it'd be a mistake to base relations on those. I've got some ideas on a more elegant way of removing sessions.



—

**Comment by atrauzzi** [comment]
I suspect both of our changes are quite an overhaul, hopefully they're compatible in some way.  The basic gist of it is that I'm making the library able to support any ORM and as I mentioned already, reworking the dependencies.

I've got base entity interfaces, I've converted your actual Entity *classes* into traits.  The idea being that any integration (Laravel, Doctrine) can be done as a simple repository + entity library, optionally leveraging the traits for default implementation.

I mentioned elsewhere that I'll be working on this 9-5, so if you want to hold off in any way and preview what I've done, I should be done by the end of the week.  It won't be PSR-2 initially, but that's only on the off chance that you totally hate it and I have to keep my fork.  If you do like it, I'll do the little bit of work to make it proper PSR-2.

**Comment by atrauzzi** [comment]
@alexbilbie Here's a preview of things: https://github.com/atrauzzi/oauth2-server/tree/cleanup/src/Entity

I'm still tearing things apart in the rest of the repository.  But feel free to poke around to see what I've done with repositories, and services.  I'm just working on the grants right now.

**Comment by atrauzzi** [comment]
@alexbilbie An example of how I'm thinking grants can look: https://github.com/atrauzzi/oauth2-server/blob/e390a7793acd84e92319457f6a7c7a9272df14d8/src/GrantType/AuthorizationCode.php

Basically flow dispatching is always handled at the service level and grants don't have to be directly called by implementers. Constants are used when grants support/require more than one flow.

Really hoping you like this so far as I feel like it's a huge improvement to the public interface of the library.  The end result I'm hoping is dead simple to implement with and easy to document.

**Comment by brutto** [comment]
@alexbilbie begin using this pretty awesome lib i really was misunderstanging what is Session about (each AccessToken issue new Session). It will be good to hear how it was planned, for what purporse? 

I'm interested in because of after some digging and implementation at my project found that maybe Session concept may used at AuthServer (not Resource) side at least with AuthCodeGrant and ImplicitGrant types to detect all tokens issued to current session and revoke all of them with this session delete.

**Comment by alexbilbie** [comment]
Sessions are now going in V5

**Comment by djtarazona** [comment]
@alexbilbie gone* in V5? 😇

Keep up the awesome work!

**Comment by alexbilbie** [comment]
All gone :smile:
