### ISSUE TITLE
Replace all occurrences of the term "Storage" with "Repository"

### ISSUE THREAD

**Issue by atrauzzi** [thephpleague/oauth2-server#307]
It's a minor distinction, but your storage classes and interfaces abide more or less to the repository pattern.  By naming it such, you'll get a lot of free _understanding_ from people consuming the library.

**Comment by alexbilbie** [comment]
I agree and in my local out-of-sync copy I've actually already done this - I will merge with dev soon :+1:

**Comment by atrauzzi** [comment]
Haha, awesome.  Sorry for being such a pain! :)

Feel free to use this issue to track/close with the commit.

**Comment by alexbilbie** [comment]
No trouble at all, I'm just glad I'm helping people out with my code :grinning:

**Comment by m4tthumphrey** [comment]
Could the repositories possibly introduce factories so we can extend the Entity classes? Or provide factories for each of the Entity types as standalone classes?

**Comment by alexbilbie** [comment]
@m4tthumphrey yep it's coming in v5. I might be able to backport to v4 too

**Comment by m4tthumphrey** [comment]
@alexbilbie amazing! Any timeline for either of those scenarios? :smile:

**Comment by alexbilbie** [comment]
This is done in V5
