### ISSUE TITLE
Make all Entity use EntityTrait or otherwise be uniformly bulk-settable

### ISSUE THREAD

**Issue by mcd-php** [thephpleague/oauth2-server#318]
Now `EntityTrait` is only used by `ClientEntity` and `ScopeEntity`.
Why not `EntityInterface` with `hydrate()` ? 
Why not all entities are made equal ?

Now to hydrate all entities uniformly I had to re-implement [YiiBase::configure()](https://github.com/yiisoft/yii2/blob/82c1136613f531b6830e6dcdf5d055d8193c6b99/framework/BaseYii.php#L515) with reflection ~~and hookers~~.

**Comment by rdohms** [comment]
:+1: 

Actually I believe the hydrate method should actually be static allowing you to build a new Entity without an instance of it.

`$client = ClientEntity::build($array)`

Makes for clean and expressive code.
@alexbilbie I would be glad to PR this is you define the best direction to go with it.

**Comment by mcd-php** [comment]
Static is plague, if not otherwise proven with math rigor on case-by-case basis. For example, here it will kill partial hydration, constructor options and class inheritance (may resurrect w/ ugly functions like `get_called_class()`, equals to reflection and occult magick).

Just hoist `hydrate()` into base class like `\League\OAuth2\Server\Entity\AbstractTokenEntity`, and turn into `HydratableInterface` and `HydrateTrait`.

Here's how I use it, so ugly:
```php
        $entity = new $entityClass($this->_server);
        // https://github.com/thephpleague/oauth2-server/issues/318
        if ( method_exists($entity,'hydrate')) {
            $entity->hydrate($fields);
        } else {
            ObjectHelper::configureForeign($entity,$fields);
        }
```

**Comment by rdohms** [comment]
@mcd-php static is plague is used incorrectly.

This case an entity is a Value Object and using a static to instantiate a VO is perfectly usable.
Its my understanding the constructor in this case should not be changing anyway.

Class inheritance issues can be dealt with a simple `new static`.

Either way, the static is not the issue and would just make more readable code.
This can also be achieved in 2 steps anyway, one to make hydrate available in every object and second to have a trait for static building.

**Comment by alexbilbie** [comment]
Agreed about using EntityTraits.

The `hydrate` method needs to die.

**Comment by rdohms** [comment]
@alexbilbie you lost me. :P which path do you want to take?

**Comment by alexbilbie** [comment]
So v5 will have entity traits which implement all of the required methods for this library to work. Then you can use your own Doctine/Eloquent/whatever entities.

Ergo the hydrate method won't be necessary

**Comment by alexbilbie** [comment]
I've just pushed an early version of version 5 of this library to the `v5` branch.

In this version I type hint against entity interfaces and use traits. Note as of this moment only the client credentials grant is implemented.

**Comment by alexbilbie** [comment]
This is now implemented in V5
