### ISSUE TITLE
Inverted condition in AbstractTokenEntity::isExpired()

### ISSUE THREAD

**Issue by mcd-php** [thephpleague/oauth2-server#320]
See [AbstractTokenEntity.php#L116](https://github.com/thephpleague/oauth2-server/blob/2108c88dfba643e48334337e0f1c12d48889da0e/src/Entity/AbstractTokenEntity.php#L116):
```php
    public function isExpired()
    {
        return ((time() - $this->expireTime) > 0);
    }
```

Let's we are in 1970, `time()` is 900, `expireTime` is 1000, token is fresh and has entire 100 seconds to expire. But the expression 900 - 1000 = -100 and is **negative**, so the token is rotten and will become fresh forever after expiry time.

Flipping the comparison actually did help me to get through the error to next one.

**Comment by rdohms** [comment]
@mcd-php i don't follow.

(-100 > 0) == false // -100 is not greater then 0
That means `isExpired` returns `false` meaning the token is indeed *not* expired.

If `time()` is higher then `expireTime` then the result is above zero and the token ins indeed expired.

So this is actually not an issue.

**Comment by mcd-php** [comment]
Yeah, sorry. Seemingly the real issue was value scaling/transform in my DB library.
