### ISSUE TITLE
Exceptions are not helpful, must have error description and send it with response

### ISSUE THREAD

**Issue by mcd-php** [thephpleague/oauth2-server#321]
See: [AuthCodeGrant.php#L219](https://github.com/thephpleague/oauth2-server/blob/ea6edf572a79e133a141e1c65165a5dece2ecdf6/src/Grant/AuthCodeGrant.php#L219)
```php
        // Ensure the auth code hasn't expired
        if ($code->isExpired() === true) {
            throw new Exception\InvalidRequestException('code');
        }
```
**Observed**: No error reason in response, no reason in log: 
> exception 'League\OAuth2\Server\Exception\InvalidRequestException' with message 'The request is missing a required parameter, includes an invalid parameter value,includes a parameter more than once, or is otherwise malformed. Check the "code" parameter.'

Absolutely clueless and misleading, have to look into the source.

**Expected**: Helpful and immediately available error messages in logs and in response, not only in code comments:

> exception '...' with message 'The code has expired'

**Comment by alexbilbie** [comment]
All of the error messages are taken from the OAuth 2.0 specification.




If you can find a more appropriate error from the spec please let me know and I'll change if I agree, otherwise for now it's how it is.



—

**Comment by mcd-php** [comment]
I have read http://tools.ietf.org/html/rfc6749 , section 5.2 allows optional `error_description`. 

Yes, it will take rework of exception hierarchy, but not giving human-worded description of error will impede cooperation between services using the library, and their clients.

I have both client and server in neighbour IDE windows (splitting my project in SOA way), but what if client is foreign developer ? How can he know what failed in server, or what is his own fault ?

**Comment by alexbilbie** [comment]
I agree. I'll have a look into what can be done add support for the `error_description` field

**Comment by vvllaadd** [comment]
+1 on this, an error description will help a lot

**Comment by tpavlek** [comment]
Thank goodness there's progress on this. Just spent an hour tearing out my hair because I thought I wasn't including an auth code, when it was just expired in fact.

Thumbs up alex :+1:

**Comment by dav-m85** [comment]
Issue to be closed ?

**Comment by mcd-php** [comment]
Here's the closing criteria:

Let's https://alice.net uses this library, and https://bob.org has junior web-master Pogo who tries to establish trust with https://alice.net, but does not know what language and library does the https://alice.net use, let alone any opportunity to view it's source and debug side by side.

The poor Pogo can clearly and definitively find out what's bad with the connection only from network messages coming his way, no need for comments in code of library he doesn't know of existence and usage.

If that's true, then close.

P.S. Sorry, don't have my offending projects handy and ready for test.

**Comment by dav-m85** [comment]
@mcd-php awesome test case to write indeed :)

**Comment by alexbilbie** [comment]
V5 now has much much improved error messages
