### ISSUE TITLE
.htaccess login vs. Authorization header

### ISSUE THREAD

**Issue by di5abled** [thephpleague/oauth2-server#337]
Hy,

I have an staging server which is protected with an .htaccess login and because of this I can't use the Authorization header and have to stick to the `?access_token=...` param. But this doesn't work because as soon as an Authorization header is present, which is the case with an .htaccess login, the RessourceServer.php uses this header instead of the `access_token` param.

What is the best way to work around this problem? 
Do I have to write my own RessourceServer.php and use it?
Would you mind adding a setting for this?

Unfortunately I can't disable the .htaccess login for this spezific routes...

**Comment by alexbilbie** [comment]
This is a limitation of your setup I'm afraid, it's not something this project or even PHP or Apache can solve
