### ISSUE TITLE
Using relational storage example

### ISSUE THREAD

**Issue by peteclark3** [thephpleague/oauth2-server#338]
Let's say I want to use the relational storage example classes as-included..  How would I include them? Do I need to add a line to my existing composer.json so they are auto-loaded?  They don't seem to be auto loaded when I install the package via "$ composer require league/oauth2-server" .. b/c I try to load them in one of my classes and I get a fatal error that the SessionStorage class is not found (this is the first one it tries to load). I'm sure my other composer-included packages are working so figured I just needed to know where to copy the included Storage classes and/or how to include them.  

If there is a better forum for posting this question, please let me know.

**Comment by brti** [comment]
Why not just copy the files out of that folder and put them under a namespace and autoload them in that way?
