### ISSUE TITLE
Setting up Server to Server

### ISSUE THREAD

**Issue by alnutile** [thephpleague/oauth2-server#339]
@alexbilbie 
Hello, was looking for a way to offer paying you for some insight to setting this up. We have all the pieces in place but just want to see about the final steps.

We have a server/web app to server oauth communications setup. The server making the requests will have users but this is not about the users role when using this external API we made. The Oauth2 server will talk to many servers when all is done and never to users.

# Setup Idea 1

Give server (client) a token that last for some time (say 1 year) and have it use that token to talk to the Oauth2 server.

# Setup Idea 2

We can use the Oauth2 client from phpleague, set it up and add if needed the functionality for the below

The client talks to the server using a token and if gets a token expired response the Error exception handler on the request will try once to refresh then token before trying the request again, if for some reason it gets another error it will try the password grant to generate a new token, finally ending if that does not work.  If it succeeds in any of these it will update the records in the db to have the encrypted token refresh token. The client secret and id and other info is all saved in a .env file since that will not change like above.

Two seems like the "official" way if I am understanding things. I just did not know if saving all this info was the best way. For example we end up with one table and one row in that table to save the access token and refresh token.

Thanks 

alfrednutile@gmail.com if you would like to me email me and do a google hangout. We can talk about fees etc as well.

**Comment by alexbilbie** [comment]
I'm really sorry the late reply on this. Did you solve this?

**Comment by alnutile** [comment]
Not in a good way. Maybe we can talk. Alfrednutile@gmail.com
