### ISSUE TITLE
ResourceServer: access_token in requests other than GET

### ISSUE THREAD

**Issue by demagu** [thephpleague/oauth2-server#340]
Hello,

What is the reasoning behind this code:
```php
$accessToken = ($this->getRequest()->server->get('REQUEST_METHOD') === 'GET')
                                ? $this->getRequest()->query->get($this->tokenKey)
                                : $this->getRequest()->request->get($this->tokenKey);
```
https://github.com/thephpleague/oauth2-server/blob/master/src/ResourceServer.php#L143

In case I wanted `access_token` to be passed as query string parameter in all request methods (POST, PATCH, DELETE etc) the above line will prevent it. 

What would be the best way of making this possible?

**Comment by alexbilbie** [comment]
Please see #111 

Basically, use the `Authorization` header to pass in the access token

**Comment by demagu** [comment]
@alexbilbie, thanks for the hint. 

In my specific case `access_token` has to be passed in as query string. 
I ended up extending `ResourceServer` and overwriting `determineAccessToken` method to for my needs.

**Comment by andreikun** [comment]
If you want to access secured paths using access_tokens as query string informations below might help you:

Check here: https://github.com/thephpleague/oauth2-server/blob/master/src/ResourceServer.php#L146

It shouldn't be $this->getRequest()->request->get($this->tokenKey). Instead it should be $this->getRequest()->get($this->tokenKey).

That;s why it does not work. I already adjusted my code, it would be nice if someone from phpleague will adjust too.

It works now with both POST and GET having access_token in query string like ?access_token= mQ77AR4vzpTdn81Sc4os7FdRYWd3UJJjQ1GBJ3Us

**Comment by alexbilbie** [comment]
It isn't going to be changed in this library. Extend the ResourceServer
class if you really want it or just use Authorization headers.
