### ISSUE TITLE
Question: What is the reason for the parameters to the ResourceServer constructor?

### ISSUE THREAD

**Issue by christianjul** [thephpleague/oauth2-server#343]
*This is not an issue as such, and I am sorry if this is not the right place to ask, but I could not find anywhere more suitable.*

The ResourceServer requires 4 types of storage instantiated and passed to the constructor. As far as I can see only one of them is used. Also the parent class instantiates an event system that apparently is never used.

I was wondering what the thoughts are behind this design? Am I completely missing something?

**Comment by alexbilbie** [comment]
Sorry for the late reply to this. The reason is that the resource server requires these dependences, whereas the other auth server has different dependencies depending on the grants used.

As for the event system; you're right it isn't used currently. This will be cleaned up in v5
