### ISSUE TITLE
Issue with verifying tokens

### ISSUE THREAD

**Issue by kartikagarwal1993** [thephpleague/oauth2-server#349]
I am making a request to access user resource like this

http://localhost:8000/user/kartik?access_token=a19ca2112a04b76ef3286c80db19d3b03f72356b

Following error occurs : Only one method may be used to authenticate at a time (Auth header, GET or POST)

I haven't send any data using post, nor I have attached any headers.

The function Bearer::getAccessTokenParameter() uses the following code 
$methodsUsed = !empty($headers) + (bool) ($request->query($this->config['token_param_name'])) + (bool) ($request->request($this->config['token_param_name']));

to count the number of methods used. The value of $methodsUsed becomes 2 . That's why this error occurs.But since I have used only get method this should not occur.

**Comment by alexbilbie** [comment]
Sorry for the late reply; have you solved this? Please re-open if not
