### ISSUE TITLE
Add support for Open ID Connect Basic Client Profile

### ISSUE THREAD

**Issue by alexbilbie** [thephpleague/oauth2-server#35]
http://openid.net/specs/openid-connect-basic-1_0.html

**Comment by jakeasmith** [comment]
Any chance this is coming soon? I looked around for a roadmap but didn't see anything and there's a chance I may need to add support for this in my own app within the next few weeks.

**Comment by alexbilbie** [comment]
Closing for now; out of scope for V5

**Comment by Aliance** [comment]
@alexbilbie Can I use that package for implementing OpenID Connect?

**Comment by Sephster** [comment]
Not yet but there is a package available from a third party which will allow this https://github.com/steverhoades/oauth2-openid-connect-server
