### ISSUE TITLE
PSR-7

### ISSUE THREAD

**Issue by JanJakes** [thephpleague/oauth2-server#351]
Since PSR-7 have been accepted and many libraries start to adopt it, the request/response interfaces in this package should be replaced by the PSR-7 interfaces (https://github.com/php-fig/http-message).

Any thoughts/plans on this?

**Comment by marcteyssier** [comment]
:+1:

**Comment by alexbilbie** [comment]
I'm way out of touch with what's been happening in the PHP world. How have other packages implemented this?

**Comment by alexbilbie** [comment]
V5 is PSR compliant
