### ISSUE TITLE
Authenticated apps for a user

### ISSUE THREAD

**Issue by iamdriz** [thephpleague/oauth2-server#354]
Where do you store apps that the user has authenticated? For example if I have authenticated an application and then return to the client and login using the provider it shouldn't ask for me to approve or decline the application again it should just give the client an access token to gain access to the API.

The only thing I see that gets stored is the access tokens, but these could have expired and they don't handle if a user decides to revoke an application but then might re-approve in the future. Also manage settings for an application they have approved, etc, allow them access to different scopes, etc.

**Comment by tyuwan** [comment]
You have to handle that logic yourself.

**Comment by iamdriz** [comment]
Where would I handle it?

**Comment by iamdriz** [comment]
@tyuwan It would have to somehow intercept the request... Even if it's an authorization code it would need to step over the asking the user to agree and just return the code.

**Comment by alexbilbie** [comment]
Your server should clean up old access tokens. If an access token has expired then the user should approve permission again.

**Comment by iamdriz** [comment]
Both GitHub and Facebook don't work this way and instead just grab another access token once the current one has expired and check that the app still has permission without requiring the user to click to authorise again. In fact you can even list your authenticated apps and revoke the current token or the application itself. So they are clearly storing authenticated applications as well as access tokens.

**Comment by alexbilbie** [comment]
The implementation is up to you. If you want the same functionality then you need to simply store that a user has approved a client already and then re-issue a new access token with the same permissions as before.
