### ISSUE TITLE
MAC-tokens & refresh tokens - incompatible?

### ISSUE THREAD

**Issue by auro1** [thephpleague/oauth2-server#356]
Hi

When I add both the RefreshToken grant and the MAC token type, it will not issue a refresh token. When I remove the mac token, it issues a refresh token just fine?

**Comment by alexbilbie** [comment]
I will take a look into this

**Comment by joaopramos** [comment]
It looks like the MAC token type is not returning the issued refresh token.

Issued pull request #369

**Comment by alexbilbie** [comment]
Merged #369
