### ISSUE TITLE
Fatal error: ... getScopes() ...

### ISSUE THREAD

**Issue by cboden** [thephpleague/oauth2-server#357]
> Fatal error:  Call to a member function getScopes() on a non-object in /vendor/league/oauth2-server/src/Grant/RefreshTokenGrant.php on line 136

I'm using an `AuthorizationServer` with `PasswordGrant` and `RefreshTokenGrant`. Initial issuing of an access token works great. When I try to refresh the token I get the above error. Here is part of the code doing the refresh:

```php
$app->post('/refresh_token', function() use ($app, $server) {
    $params = [
        'grant_type' => 'refresh_token',
        'refresh_token' => $app->request->params('refresh_token')
        'client_id' => $app->request->params('client_id')
        'client_secret' => $app->request->params('client_secret')
    ];

    $request = new Request([], $params);
    $server->setRequest($request);
    $response = $server->issueAccessToken();

    // etc
});
```

I've verified the values of `$params` are what they should be.

**Comment by IamRobin** [comment]
Hi, I'm having the exact same issue with refresh tokens. What did you do to resolve it? (If you have)

**Comment by refear99** [comment]
I'm having the exact same issue
@cboden Is this fixed?

**Comment by cboden** [comment]
@refear99 I forget exactly what was wrong but I remember it was my fault in the configuration...I think I forgot a database field and an empty row was causing it.

**Comment by refear99** [comment]
@cboden Please help...
Which part of configuration? Auth? Grant?
