### ISSUE TITLE
Cannot serialize $authParams as per examples and documentation

### ISSUE THREAD

**Issue by raijinsetsu** [thephpleague/oauth2-server#361]
Documentation is here: http://oauth2.thephpleague.com/authorization-server/auth-code-grant/
The comment that reads:
````
// Everything is okay, save $authParams to the a session and redirect the user to sign-in
````
does not specify how $authParams is to be saved - this does not appear to be a serializable object as putting it in to the session and then taking it out returns an empty string.

I am reworking my code to save off the query parameters and restore them so I can make a second call to checkAuthorizeParams() after the user has authorized access. This seems sub-optimal and also seems likely to break down in some future iteration where checkAuthorizeParams() generates additional data that cannot be regenerated.

It seems we would be better off if checkAuthorizeParams() returned a serializable object or if utility methods were created to handle this situation.

**Comment by eunion** [comment]
hi ,How did you solve the problem? I use phalcon framwork it can not save the authParams to session.

**Comment by raijinsetsu** [comment]
I was not. No matter what, I could not unserialize the authParams.
Serialization worked fine.
