### ISSUE TITLE
access_token from request query problem in lumen 5.1 

### ISSUE THREAD

**Issue by yazfield** [thephpleague/oauth2-server#362]
Hello,

I'm using the package with lumen 5.1 and i've noticed that there's a problem with sending the access_token as a request query.

The problem is at ``` League\OAuth2\Server\ResourceServer@determineAccessToken line 140 ```, the if condition ``` if($this->getRequest()->headers->get('Authorization') !== null) ``` is always true because get('Authorization') returns an empty string (even though it wasn't set) so the method never checks for access_token in request query.

fix: 
```
$authorization = $this->getRequest()->headers->get('Authorization');
if( !  empty($authorization)) ....
```

Cheers :D

**Comment by andreikun** [comment]
Hello yazfield

Please check here my problem: https://github.com/thephpleague/oauth2-server/issues/375

Maybe you have the same issue, and your request is just the same with the previous one where you had Authorization.

Check the get() method. This won't return empty string, for sure. empty array or null will return this one if no authorization is found. Better check your Auhorization header from previous requests.

Thanks.

**Comment by alexbilbie** [comment]
Would changing the line to `if($this->getRequest()->headers->get('Authorization', null) !== null)` fix it?

**Comment by alexbilbie** [comment]
Closing as V5 implements differently

**Comment by rickshawhobo** [comment]
hey @alexbilbie can we patch this for 4.1 with the code you suggested above? We're being forced to use 4.1 for now now due to the Luca package. Much appreciated!

**Comment by alexbilbie** [comment]
@rickshawhobo I've created a `4.1.x` branch - if you make the change and PR against that branch I will merge and create a new `4.1.x` tag

**Comment by rickshawhobo** [comment]
Thanks @alexbilbie  Here is the PR https://github.com/thephpleague/oauth2-server/pull/652
