### ISSUE TITLE
Implement nonce functionality for MAC tokens

### ISSUE THREAD

**Issue by michaelhogg** [thephpleague/oauth2-server#366]
Currently, [`TokenType\MAC`](https://github.com/thephpleague/oauth2-server/blob/2496653/src/TokenType/MAC.php) doesn't do anything with [the nonce](https://github.com/thephpleague/oauth2-server/blob/2496653/src/TokenType/MAC.php#L93), except to [include it in the `$calculatedSignatureParts`](https://github.com/thephpleague/oauth2-server/blob/2496653/src/TokenType/MAC.php#L106). The real nonce functionality needs to be implemented.

[This article](http://hueniverse.com/2008/10/03/beginners-guide-to-oauth-part-iii-security-architecture/) by Eran Hammer (although written about OAuth 1) describes a good solution which I think would work well in this library:

> Using nonces can be very costly for Service Providers as they demand persistent storage of all nonce values received, ever. To make implementations easier, OAuth adds a timestamp value to each request which allows the Service Provider to **only keep nonce values for a limited time**.
>
> When a request comes in with a timestamp that is older than the retained time frame, it is rejected as the Service Provider no longer has nonces from that time period.
>
> It is safe to assume that a request sent after the allowed time limit is a replay attack.
>
> From a security standpoint, the real nonce is the combination of the timestamp value and nonce string. Only together they provide a perpetual unique value that can never be used again by an attacker.

**Comment by alexbilbie** [comment]
I'll keep this in mind for v5

**Comment by alexbilbie** [comment]
Because the latest MAC token draft has expired and significantly changed from the implementation in this project I've removed it for now. If the MAC spec is formalised I will take another look.
