### ISSUE TITLE
Separation of Session scopes and AccessToken ones

### ISSUE THREAD

**Issue by newls** [thephpleague/oauth2-server#374]
Hello,

I am building an application that uses oauth2-server authorization micro framework,
i am seeking to implement each of the Storage classes correctly, but I still persist to wonder if it's necessary to separate the Session's scopes from the AccessToken ones ?  
I, per example defined getScopes() in my AccessTokenInterface implementation like here :  
returning the session scopes when using AccessToken::getScopes() from my other SessionStorageInterface implementation

```php
   public function getScopes(AccessTokenEntity $token) {
      $sessionStorage = OAuthHelper::getSessionStorage();
      $session = $sessionStorage->getByAccessToken($token);
      return $sessionStorage->getScopes($session);
   }
```

I wondered if this is totally against the soul of oauth2-server ?

Note: I finally avoided doing what I was trying to, because
I prefer to follow the example implementation to the maximum extent,
but my question still remains !

Tell me,
Regards,
Nelson

**Comment by alexbilbie** [comment]
This is something that v5 will fix (i.e. get rid of the concept of sessions).

Please follow #306
