### ISSUE TITLE
Authorization header not recognized using phpUnit and multiple requests. 

### ISSUE THREAD

**Issue by andreikun** [thephpleague/oauth2-server#375]
Hello,

I spent half a day debugging why Authorization header is not recognized within my PHPunit tests. I am trying to make two calls, first to get access token (Ex. /oauth/token) and second one to get some data from a secured path. (Ex: /api/securedData)

I am using Lumen, having the implementation of oauth2-server from lucadegasperi, adapted to Laravel/Lumen. Thing is that:

- Authorization header is sent with success and recognized within any middleware
- when check inside \vendor\league\oauth2-server\src\ResourceServer, i got a different request while var_dump($this->getRequest()) in determineAccessToken method.
- It seems that when i am expecting request to /api/securedData with Authorization header, i got the request from  /oauth/token.
- Somehow, $this->request is not updated within AbstractServer class located at \vendor\league\oauth2-server\src\. 

Can you please check this? I am at a dead end right now. Other alternative should be to use access token as get parameter but this is just not right.

Thanks.

**Comment by andreikun** [comment]
It seems that Request is set via Authorizer inside the Oauth2ServerServiceProvider. This is an implementation of lucadegasperi for Laravel/Lumen.

When using PHPunit, app is bootstrapped only once for each TestCase, which means that ServiceProvider is registered only once even if i make multiple requests. 

This means that setRequest is called only once, at first call when application is boostrapped. This also can be fixed somehow from your part, by always getting the latest request.

I will also post an issue on lucadegasperi package.

**Comment by alexbilbie** [comment]
Are you binding the Laravel request into the server using `$server->setRequest($request);` ?

**Comment by andreikun** [comment]
No, where am i supposed to do this? I am just making requests to API like $this->get(...) and $this->post(....). that's it.

**Comment by alexbilbie** [comment]
On your OAuth server instance bind the Laravel request into it before the server starts its validation as shown above. 

I'm not familiar with Laravel so I can't necessarily help you on where to exactly put this in your specific code base.

**Comment by starJammer** [comment]
I think I found why this ISN'T working.

You have to dig all the way to `Symfony\Component\HttpFoundation\ServerBag->getHeaders` sort of. It is used by HeaderBag, which is used by `Symfony\Component\HttpFoundation\Request`.

Also, refer to http://stackoverflow.com/questions/7818867/check-header-authorization-on-restler-api-framework

Essentially, PHP under Apache ignores the Authorize header. So you have to either force apache to set the Authorize environment variable like in the stackoverflow question or you have to pass in the header under a different name.

**Comment by andreikun** [comment]
I am using nginx, so this has nothing to do with Apache.

In my case i was using Lumen, and it wasn't any implementation of oauth2-server for Lumen at that time, so i used an implementation from Optimus.

Now, lucadegasperi has fixed the issue on the latest version (5). They added the following line:

https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/Middleware/OAuthMiddleware.php#L70

Now, every time you check for Authorization header, request is updated by getting $request object from the Middleware function as parameter.

Thanks.
