### ISSUE TITLE
Cannot get access_token from url for REQUEST_METHOD other than GET

### ISSUE THREAD

**Issue by andreikun** [thephpleague/oauth2-server#376]
Hello,

I am trying to get access token passed as query string "?access_token=adawda" when using request method other than GET. 

I am currently passing access token in url as "?access_token=adawa" using a POST request because i am not able to do it via HTTP Headers using Authorization header.

Instead of this:

    $this->getRequest()->request->get($this->tokenKey)

It should be 

    $this->getRequest()->get($this->tokenKey)

**Comment by alexbilbie** [comment]
Please see #111

**Comment by andreikun** [comment]
Please see my comment to fix this here : https://github.com/thephpleague/oauth2-server/issues/340#issuecomment-137696626

**Comment by alexbilbie** [comment]
As I said in #340 this library isn't going to implement what you want. My recommendation is you switch to Authorization headers.
