### ISSUE TITLE
How to receive scope information

### ISSUE THREAD

**Issue by Romain17** [thephpleague/oauth2-server#379]
Hello,

Thanks for your plugin. I implemented and it work well.

I just have a question about the scope parameters. Indeed i send scope parameters in my request but i don't receive the information in response.
Can you tell me how to use them ?

Thanks!
Romain

**Comment by alexbilbie** [comment]
The OAuth 2.0 spec doesn't provide a method to detail what scopes have been granted - you'll need to come up with your own implementation of this.
