### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by davidsteinsland** [thephpleague/oauth2-server#382]
It is unclear whether or not relationships between sessions and access token is one-to-one or one-to-many. Same applies for several other database entities. 

If you are providing an relation db example, you should also spend some time explaining the schema.

**Comment by alexbilbie** [comment]
One session can have multiple access tokens.

I'm removing the concept of sessions in v5.

I'm not providing a schema on the basis that this library can be used with non-relational storage systems
