### ISSUE TITLE
Crushes when scope parameter is not а string

### ISSUE THREAD

**Issue by imissyouso** [thephpleague/oauth2-server#383]
When client trying to send scope parameter as array it rises exception.

It seems as in ValidateScopes method of AbstractGrant class we should to add input scopes parameter checking like this:
 ``` php
 if(!is_string($scopeParam)){
      throw new Exception\InvalidRequestException('scope');
 }
```
Isn't it?

**Comment by alexbilbie** [comment]
Scopes are sent as a string in the form `scope1 scope2 scope3 etc`. Note the space between each scope. Yes it's dumb but it's how the spec specifies it
