### ISSUE TITLE
Question about scopes

### ISSUE THREAD

**Issue by marcaube** [thephpleague/oauth2-server#384]
Maybe I don't understand the scope part, but it's weird to me that anyone with client credentials can request a token with the scopes they want. Some of my endpoints expose sensitive data and should not be accessible to just any client.

Is there a way to define in advance a list of scopes available to a client? Does it make any sense?

**Comment by alexbilbie** [comment]
Yep - when scopes are validated the client ID is passed in (see https://github.com/thephpleague/oauth2-server/blob/master/src/Storage/ScopeInterface.php). If the client shouldn't be able to access the scope then return `null` and the auth server will show an error to the cleint
