### ISSUE TITLE
DB structure to store login credentials

### ISSUE THREAD

**Issue by sterichards** [thephpleague/oauth2-server#385]
I can't find this within the project. I've noticed vendor/league/oauth2-server/examples/relational/config/init.php produces an include error.

I've ran init.php from every directory from the root up to the 'config' directory and each gives an error similar to:

failed to open stream: No such file or directory in vendor/league/oauth2-server/examples/relational/config/init.php on line 7

**Comment by alexbilbie** [comment]
You probably need to run `composer install` inside `examples/relational` first
