### ISSUE TITLE
Having refresh_token sent with a Client Credentials Grant

### ISSUE THREAD

**Issue by newls** [thephpleague/oauth2-server#390]
The Refresh Token support doesn't seem to be implemented in ClientCredentialsGrant ,
is it against the OAuth2 spec ?
Thanks a lot,
newls

**Comment by starJammer** [comment]
Yes, it's against the OAuth2 spec. The client credentials grant uses both the client_key and client_secret directly so you can just get another access token with those.

For reference: https://tools.ietf.org/html/rfc6749#section-4.4.3

See the 3rd sentence.

**Comment by newls** [comment]
Thanks a lot @starJammer .
newls

**Comment by newls** [comment]
adds:
I would like to know the reason for the usage of SHOULD NOT here, but be certain I'm going to respect the spec for now, as soon as I already was, of course reusing the credentials to fetch the token.
Thanks again @starJammer !

**Comment by starJammer** [comment]
@newls I made a mistake here and should've said "Yes, it's not recommended by OAuth2 spec".

[This document](https://www.ietf.org/rfc/rfc2119.txt) defines the meaning of SHOULD NOT as being 
```
SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.
```

It specifies that the implementation can go against the recommendation if the ramifications are understood but it's up to the implementation. So it isn't strictly prohibited.

I don't see an obvious downside to providing a refresh token other than leaking another "credential" onto the network.

**Comment by newls** [comment]
Thanks a lot @starJammer ,
I franckly admit I was asking this question hoping someone would know !
It is a good reason not to implement it in oauth2-server I guess !
Thanks for your reply, I asked before reading the RFC on this specific topics, lacking of time.
Thanks for providing all this information ! I will keep refreshing wiith the client credentials.
newls
