### ISSUE TITLE
Use pre-existing grant

### ISSUE THREAD

**Issue by davidsteinsland** [thephpleague/oauth2-server#392]
Would be nice if one could configure the server to respond with a pre-existing grant on authorize, if the user has granted the client and scopes before. This will reduce duplicate Oauth Sessions.

**Comment by davidsteinsland** [comment]
Can probably add that this needs to go a step further. When issuing an access token, I believe that the previous session should be used, if there is any. If not the number of sessions for the same application will quickly rise to a very high number.

`One app = One session` given that the scopes are the same.

Today it's
`One authorization request = One session`, although it's the same app and scopes

**Comment by alexbilbie** [comment]
This logic can be created in the storage interface implementations. Will update docs to demonstrate this
