### ISSUE TITLE
Can I encrypt "get access token" call

### ISSUE THREAD

**Issue by snky1987** [thephpleague/oauth2-server#393]
First things first.

I am working on API based mobile application where user will log in once and after successful access_token (via password grant) will be received it will store encrypted details in device's encrypted storage.
When his access_token expires app will take credentials from the encrypted storage and ask for a new access_token.

To do that I need to send grant_type, username, password, client_id, client_secret etc. to Authentication Server.
The thing is that I don't want to send them as plain text (even through HTTPS).

Is there a way to send encrypted data and override passwordGrant::completeFlow() functionality to decrypt data before server will try to get client_id and client_secret (without editing an vendor because I managed to do that this way) ?

**Comment by alexbilbie** [comment]
Refresh tokens solve your problem
