### ISSUE TITLE
scopes and internal app permissions

### ISSUE THREAD

**Issue by leemason** [thephpleague/oauth2-server#398]
im working on an app which has:

users
roles
permissions

users can have many roles
roles and/or users can have many permissions (role permissions propigate down to the user)

now as you would expect obviously ive in advance kept my "permissions" compatible with scopes for consistency.

both permissions and scopes have the same identifiers which works great.

ive come across a situation that i need clarifying:

say i have:

User1
Has Editor Role
Has Permissions user:read, user:update

User2
Has Admin Role
Has Permissions user:read, user:update, user:delete

i then have api endpoints:

get /user/{id} - read user
put /user/{id} - updates user
delete /user{id} - deletes user

What should happen if i have an app that requests the ```user:delete``` scope, but gets authorized by a user without that permission?

1. should an access token be granted, with the actual permissions granted as part of the response so the app can account for the lack of this scope (dont think this is possible right now, it throws an exception).

2. should i check for this on the authorize page that gets displayed to the user and not allow them to authorize the app as they cant forfill the requirements?

3. should i catch the exception is my handler and send back to the redirect uri with an error stating the issue?

**Comment by alexbilbie** [comment]
Number 3
