### ISSUE TITLE
Why password grant needs client_id and client_secret?

### ISSUE THREAD

**Issue by aslikeyou** [thephpleague/oauth2-server#407]
Using password grant I receive following message: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"client_id\" parameter.". I opened PasswordGrant and find out the next: 
```
// Get the required params
        $clientId = $this->server->getRequest()->request->get('client_id', $this->server->getRequest()->getUser());
        if (is_null($clientId)) {
            throw new Exception\InvalidRequestException('client_id');
        }
$clientSecret = $this->server->getRequest()->request->get('client_secret',
            $this->server->getRequest()->getPassword());
        if (is_null($clientSecret)) {
            throw new Exception\InvalidRequestException('client_secret');
        }

        // Validate client ID and client secret
        $client = $this->server->getClientStorage()->get(
            $clientId,
            $clientSecret,
            null,
            $this->getIdentifier()
        );
```
Can someone explain me?

**Comment by alexbilbie** [comment]
The password grant needs to authenticate the client that is trying to acquire an access token with a user's credentials

**Comment by aslikeyou** [comment]
But in official docs there is no client_id and secret.

**Comment by alexbilbie** [comment]
https://tools.ietf.org/html/rfc6749#section-4.3.2

>  If the client type is confidential or the client was issued client
   credentials (or assigned other authentication requirements), the
   client MUST authenticate with the authorization server as described
   in Section 3.2.1.

**Comment by vinkla** [comment]
https://github.com/lucadegasperi/oauth2-server-laravel/issues/615#issuecomment-161579547

**Comment by aslikeyou** [comment]
ok)
