### ISSUE TITLE
Is not the exact match of ts in MAC a bit extreme?

### ISSUE THREAD

**Issue by zerkms** [thephpleague/oauth2-server#410]
In v4.1.x it's implemented as

```php
if (abs($params->get('ts') - time()) > 300) {
```

and in WIP-5 it's

```php
if ((int) $params->get('ts') !== time()) {
```

which looks a bit extreme and unlikely to pass ever.

Is it a deliberate change?

**Comment by alexbilbie** [comment]
The change was made in v4 from what is currently in v5 and I haven't
updated it again in v5. See discussion in #364

**Comment by zerkms** [comment]
Oh, okay, sorry.
