### ISSUE TITLE
Example sqlite or MySQL Structure dump?

### ISSUE THREAD

**Issue by mikepmtl** [thephpleague/oauth2-server#411]
I know the init.php file is in the examples config.  But would there be a possibility to have a copy of a sqlite3 DB file or MySQL structure dump?

I understand the storage is abstracted, but it would be nice to be able to load an example structure and see the relationships.

Thanks,
Mike

**Comment by dav-m85** [comment]
@mikepmtl run ```php examples/relational/config/init.php```and then open the oauth2.sqlite3 with the dbm of your choice... cannot think of a simpler way of doing it without crippling the repository with a useless file.

**Comment by alexbilbie** [comment]
@mikepmtl for now please follow @dav-m85's advice. Will consider this for new documentation
