### ISSUE TITLE
Use AuthoriZation for consistency

### ISSUE THREAD

**Issue by marcorivm** [thephpleague/oauth2-server#413]
On some places in the documentation AuthoriZation and AuthoriSation are swapped.

And although they hold the same meaning and the later is the preferred form in standard English (http://grammarist.com/spelling/authorise-authorize/); I think AuthoriZation is more mainstream on the development community and also used through the code.

![image](https://cloud.githubusercontent.com/assets/1222598/11919671/a6e8b0fe-a71e-11e5-8179-0c37d98a4202.png)

**Comment by alexbilbie** [comment]
Whilst it pains me as an Englishman to use American spelling; the OAuth spec uses Z's instead of S's I will fix this :stuck_out_tongue: 

Good spot, thanks!
