### ISSUE TITLE
Tag Symfony 3.0 support

### ISSUE THREAD

**Issue by vinkla** [thephpleague/oauth2-server#415]
Would it be possible if you could tag a new version with Symfony 3.0 support? We're having issues in the Laravel wrapper package with Laravel 5.2 since it allows Symfony `^2.8 || ^3.0`.

https://github.com/lucadegasperi/oauth2-server-laravel/issues/636
https://github.com/lucadegasperi/oauth2-server-laravel/issues/634

**Comment by alexbilbie** [comment]
I've tagged and pushed 4.1.5 which should resolve this

**Comment by vinkla** [comment]
Thanks for being quick on this :+1:
