### ISSUE TITLE
Allow option for scope to be returned in Token Response

### ISSUE THREAD

**Issue by kfuchs** [thephpleague/oauth2-server#417]
Right now none of the TokenTypes allow for a scope parameter to be returned. 

The [spec](https://tools.ietf.org/html/rfc6749#section-3.3) says this:

> The authorization server MAY fully or partially ignore the scope
>   requested by the client, based on the authorization server policy or
>   the resource owner's instructions.  If the issued access token scope
>   is different from the one requested by the client, the authorization
>   server MUST include the "scope" response parameter to inform the
>   client of the actual scope granted.

Example: 

Adding something like this to [Bearer](https://github.com/thephpleague/oauth2-server/blob/master/src/TokenType/Bearer.php#L32):
```
if (!is_null($this->getParam('scope'))) {
    $return['scope'] = $this->getParam('scope');
}
```

The grant flows will need a little update as well.

Thoughts?

**Comment by gfyrag** [comment]
+1 for this features.

**Comment by alexbilbie** [comment]
Implemented in v5
