### ISSUE TITLE
save the authParams to session 

### ISSUE THREAD

**Issue by eunion** [thephpleague/oauth2-server#418]
hi ,I hava a problem that i can not save the authParams to session.I use the Phalcon framework

The error is "Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in [no active file]:0 Stack trace: #0 [internal function]: session_write_close() #1 [internal function]: Phalcon\Session\Adapter->__destruct() #2 {main} thrown in [no active file] on line 0".

how can i solve it!

**Comment by gfyrag** [comment]
I had the same problem. Just saved the authParams fields in a flat dictionnary to restore it later.

**Comment by wgq91here** [comment]
i use symfony. i no problem.
`
use Symfony\Component\HttpFoundation\Session\Session;

$session = new Session();
$session->start();
...
$session->set('authParams', $authParams);
`

And notice is , don't save function in session. like it :
`
$checkUser = function ($username, $passwd) {
  $User_model = new RelationalExample\Model\Users;
  $user = $User_model->get($username);

  if (password_verify($passwd, $user[0]['password']) === true) {
    return $username;
  } else
    return false;
};

$server->getGrantType('password')->setVerifyCredentialsCallback($checkUser);

$router->post('/auth', ...
`

change it :
`
$router->post('/auth', function(...

  $server->getGrantType('password')->setVerifyCredentialsCallback($checkUser);
)
`
