### ISSUE TITLE
V5 - random_bytes

### ISSUE THREAD

**Issue by juliangut** [thephpleague/oauth2-server#426]
I think it is better to use default [CSPRNG random_bytes](https://secure.php.net/manual/en/function.random-bytes.php) instead of a custom baked algorithms. For those using PHP<7.0 [paragonie/random_compat](https://github.com/paragonie/random_compat) can be included

**Comment by alexbilbie** [comment]
Are you referring to [DefaultAlgorithm](https://github.com/thephpleague/oauth2-server/blob/V5-WIP/src/Utils/KeyAlgorithm/DefaultAlgorithm.php) ?

**Comment by juliangut** [comment]
Yep, about the whole `SecureKey::generate()`

I can't say by myself what mechanism is better but according to the guys at [paragonie/random_compat discussions](https://github.com/paragonie/random_compat/blob/master/ERRATA.md) this is the order of preference:
* Use libsodium if available.
* fread() /dev/urandom if available (never on Windows)
* mcrypt_create_iv($bytes, MCRYPT_CREATE_IV)
* COM('CAPICOM.Utilities.1')->GetRandom()
* openssl_random_pseudo_bytes() (absolute last resort)

There is a lot to read about security in that repo but in the end I'd say it is overall more secure

**Comment by juliangut** [comment]
At the same time I'd change `KeyCrypt` encrypt and decrypt methods to use [phpseclib](https://github.com/phpseclib/phpseclib/tree/2.0) package instead, fully compatible with openssl

**Comment by alexbilbie** [comment]
:+1: I'll make the changes now

**Comment by alexbilbie** [comment]
I've implemented the `random_bytes`
