### ISSUE TITLE
OAuthException->getHttpHeaders missing WWW-Authenticate: MAC

### ISSUE THREAD

**Issue by Bobselp** [thephpleague/oauth2-server#427]
Hey,

The method to add the "WWW-Authenticate" header in OAuthException->getHttpHeaders() is only supporting "Basic" and "Bearer", missing "MAC".

Thanks!

**Comment by alexbilbie** [comment]
Please send a PR to fix for V4 of this library (master), have fixed in V5 660378c7b35e03a7c0b82394fd7d333f1e9eb23d

**Comment by alexbilbie** [comment]
fixed by #429
