### ISSUE TITLE
Allow variable token length

### ISSUE THREAD

**Issue by Bobselp** [thephpleague/oauth2-server#428]
Hey,

I know that one can implement an all new random string generator for the tokens, but it would be nice to have an option define the token length per grant.

AbstractGrant could be extended to include $tokenLength and setTokenLength($length) (which might do some sanity checks, like longer than X characters), and subsequent calls to SecureKey::generate() use the length as parameter.

Thanks!

**Comment by alexbilbie** [comment]
In v5 of this library access tokens will be JWTs now, and refresh tokens will be encrypted payloads so they're going to get a lot longer (~200 characters)

**Comment by Bobselp** [comment]
I didn't mean to limit the length, but to set a custom length, like 60 characters access tokens. Currently all tokens are 40 characters long.

**Comment by alexbilbie** [comment]
What's the benefit?

**Comment by Bobselp** [comment]
I originally intended to have longer refresh tokens than access tokens, so that they have an easy distinguishable feature. But you said that refresh tokens will be way differently in V5, so I guess this can be closed.
