### ISSUE TITLE
ms sql

### ISSUE THREAD

**Issue by ciprogrammer** [thephpleague/oauth2-server#438]
I am using the codeigniter implementation offered at https://github.com/thephpleague/oauth2-server/issues/72 and I get access tokens just fine but I need to integrate the oauth tables into an existing ms sql server. I don't see anything in the docs for using different db types. Is it documented somewhere?

If I edit the code to pass a ms sql DSN to the PDO file and establish a connection to the ms sql server and build the sample mysql tables into the ms sql db, will the queries work or will they need to be rewritten? They are both sql so will they just work on the ms sql db, if connected?

Thanks

**Comment by alexbilbie** [comment]
That implementation is very very old and out of date.

I believe MySQL and MSSQL are reasonably compatible though
