### ISSUE TITLE
Why is redirect_uri required?

### ISSUE THREAD

**Issue by davidsteinsland** [thephpleague/oauth2-server#439]
NOOP

**Comment by alexbilbie** [comment]
Can you clarify?

**Comment by davidsteinsland** [comment]
https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AuthCodeGrant.php#L119-L122

`redirect_uri` is optional in spec.

**Comment by alexbilbie** [comment]
How will the user be redirected back to the client if there isn't a
redirect URI?

**Comment by davidsteinsland** [comment]
ClientStorage keeps track of redirect uri, no? how the uris are stored and
fetched is implementation specific. the library should conform to the spec.
>
>

-- 
Mvh / Regards,
David Steinsland

**Comment by alexbilbie** [comment]
No, the redirect_uri should be pre-registered (i.e. whitelisted) with the auth server. Facebook and others have fallen prey to attacks multiple times because they weren't requiring whitelisted redirect uris

**Comment by davidsteinsland** [comment]
I guess you misunderstood. Redirect URI must be matched against a whitelist, yes. But the query string argument `redirect_uri` is *optional*, meaning that if it isn't set we get a default from the storage.

**Comment by alexbilbie** [comment]
Sorry when you said client storage I thought you were referring to javascript client storage and was going down completely the wrong trail of thought.

I understand now. I do apologise. I will re-open this ticket and address it soon.

**Comment by mosounov** [comment]
`redirect_uri` is required in Access Token Request if Authorization Request had it.
http://tools.ietf.org/html/rfc6749#section-4.1.3

**Comment by davidsteinsland** [comment]
I am talking about the initial authorization grant.

Den tirsdag 16. februar 2016 skrev Konst; <notifications@github.com>
følgende:

> redirect_uri is required in Access Token Request if Authorization Request
> had it.
> http://tools.ietf.org/html/rfc6749#section-4.1.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thephpleague/oauth2-server/issues/439#issuecomment-184864619>
> .
>


-- 
Mvh / Regards,
David Steinsland

**Comment by alexbilbie** [comment]
I've implemented this in v5 now

**Comment by vanteew29** [comment]
getRedirectUriwhen_you_send_2x_2018_v1https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AuthCodeGrant.php#L119-L122

**Comment by Sephster** [comment]
> getRedirectUriwhen_you_send_2x_2018_v1https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AuthCodeGrant.php#L119-L122

I don't understand your comment. Could you clarify if you have found an issue please? Thanks
