### ISSUE TITLE
Autoloader doesnt work on Windows

### ISSUE THREAD

**Issue by ciprogrammer** [thephpleague/oauth2-server#441]
I was tasked with adding oauth2 to a php app via composer and everything works as expected on my linux box but after it was put on a windows box upstream the composer autoloader fails to load the class files. 

Any help on this is appreciated.

**Comment by alexbilbie** [comment]
Did you solve this?

**Comment by ciprogrammer** [comment]
No. I ended up building a Windows VM for development because this lib doesn't support the sqlsrv driver and the Azure server where the app has to be deployed uses sqlsrv over mssql and I didn't feel like back porting the Windows environments to use the mssql driver. Thanks anyway.
