### ISSUE TITLE
Database not found

### ISSUE THREAD

**Issue by podisto** [thephpleague/oauth2-server#443]
Hi i try to follow your tutorial but i can't found the folder sql/mysql.sql in the repository to import the database.

**Comment by alexbilbie** [comment]
Please can you point me to the tutorial you're referring to?

**Comment by podisto** [comment]
This is your tutorial here is the [http://alexbilbie.com/2013/02/securing-your-api-with-oauth-2/](url)

**Comment by alexbilbie** [comment]
That post is really very old. Please follow the docs here instead http://oauth2.thephpleague.com/

**Comment by podisto** [comment]
@alexbilbie ok thanks finally i used [http://bshaffer.github.io/](url) documentation to implement OAuth2 process
