### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by juliangut** [thephpleague/oauth2-server#449]
How do you feel about adding StyleCI ([.styleci.yml](https://github.com/juliangut/oauth2-server/blob/styleci/.styleci.yml)), to the project, to enforce styling rules? I've done it on a separate branch and there are a lot of style fixes that can be included

**Comment by alexbilbie** [comment]
Have never heard of it before now. Have added a .styleci.yml and got it set up. Cheers :+1:
