### ISSUE TITLE
I'm trying to install the example oauth-server, not really sure how to use it

### ISSUE THREAD

**Issue by martynbiz** [thephpleague/oauth2-server#452]
I'm a little new to Oauth and trying to get up and running so I can learn a bit more about Oauth authentication. However, I don't really know how to get up and running. Is there somewhere I can download an example of both client and server? I think the documentation will start to make more sense when I can walk through a working example. Otherwise what do you recommend to get informed to be able to install server and client?

**Comment by wgq91here** [comment]
Examples is litter demo. Maybe can't use it directly.
Please visit oauth wiki, understand it.

**Comment by zstergios** [comment]
There is no way to install the examples. I'm trying to download them via "zip" or directly from composer
composer require league/oauth2-server but the "example" folder is not included somewhere. Can you give more information how I add the example file in my "vendor" folder?

**Comment by alexbilbie** [comment]
@zstergios you need to clone the repository manually due to the `.gitattributes` file
