### ISSUE TITLE
Why Request and Response classes?

### ISSUE THREAD

**Issue by jpkleemans** [thephpleague/oauth2-server#455]
Just a friendly question: Why is there a dependency on the HttpFoundation (or zend-diactoros in v5)?
For example: I don't understand why the package itself pulls the request data out of the request object, like here: https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/PasswordGrant.php#L117

Why not just pass the needed data as parameters to issueAccessToken() for example?

Do I miss something important here?

Thanks!

**Comment by alexbilbie** [comment]
By working with the request object directly the library can better follow the OAuth 2.0 specification in terms of validating each request parameter.

Returning a response object likewise ensures that the correct headers and body are sent back to the client.

Both of the above also means the server can be used as a PSR7 middleware layer

**Comment by jpkleemans** [comment]
@alexbilbie Thanks for your answer! Wouldn't it maybe be nice if the HTTP part of the package would be extracted into a seperate package on top of a more flexible 'core' package? So that users get the freedom to choose which Request/Response implementation they want to use (also those not implementing psr-7).

**Comment by alexbilbie** [comment]
Out of interest what would you use the "core" package for that the current implementation doesn't provide or doesn't fit your specific needs?

**Comment by jpkleemans** [comment]
@alexbilbie personally I would like to use my own HTTP Request/Response classes to handle the request and then for example manually issue the access token by calling something like $passwordGrant->issueAccessToken($username, $password).

So your package does everything I need, but I just prefer to have a bit more 'control'. Besides that I think it's generally a good idea to separate HTTP stuff from business logic.

**Comment by alexbilbie** [comment]
I understand what you are saying but OAuth is intrinsically an HTTP protocol and so this library has always handled the HTTP too. V5 uses the standardised PSR7 and versions before that Symfony HTTP Foundation.

I don't envision this library handling OAuth in other scenarios such as XMPP or IMAP so I'm comfortable and happy with it's current approach.

If you can output your own request objects in a PSR7 compatible format then you can easily add a translation middleware in front of this library, likewise you could have a translation layer from a PSR7 response object to your own response type.

**Comment by jpkleemans** [comment]
@alexbilbie ok, thanks. I'm looking forward to v5!

**Comment by mtangoo** [comment]
@alexbilbie dropping Httpfoundation for PSR7 was good except I cannot find standalone libraries yet for PSR7. So whats alternative library for those of us who want to use your  library and don't want to be hooked to any framework (infact I have home grown "framework"). 

Am currently using http foundation but will be happy to move to any decent php Request/Response PSR7 library

**Comment by alexbilbie** [comment]
I use Zend/Diactorus for PSR7 requests and responses

**Comment by mtangoo** [comment]
Thanks. I'll check it out

**Comment by mtangoo** [comment]
@alexbilbie Am sorry for asking something unrelated to Oauth but confuses me.
>I use Zend/Diactorus for PSR7 requests and responses

I have checked it out and see it implements the PSR7 fine but it is lacking a lot of methods compared to symfony's component. That is fine since its goal isn't that. Can you advise a way to use both symfony's httpfoundation and Diactorus when using your library?

Would you recommend using something like [Http Message Bridge](http://symfony.com/doc/current/cookbook/psr7.html) what warning if any would you give someone who decided to use this one?
Thanks in advance!

**Comment by alexbilbie** [comment]
Yep the Symfony bridge is the way to go. Can't offer any advice as I've not
used it but it's an officially supported Symfony package so they will be
able to advise and help

**Comment by mtangoo** [comment]
Thanks a lot
