### ISSUE TITLE
V5 - validate secret responsibility

### ISSUE THREAD

**Issue by juliangut** [thephpleague/oauth2-server#460]
ClientEntity is being responsible for secret validation, while business logic such like that should be out of the model

At the same time on https://github.com/thephpleague/oauth2-server/blob/V5-WIP/examples/src/Repositories/ClientRepository.php#L29 example client repository, secret verification is made another very different way which is not consistent with the Interface

IMO `getSecret` method should be added to `ClientEntityInterface` and then https://github.com/thephpleague/oauth2-server/blob/V5-WIP/src/Grant/AbstractGrant.php#L212 changed to

```php
if ($client->canKeepASecret() && $clientSecret !== $client->getSecret()) {
// or
if ($client->canKeepASecret() && password_verify($clientSecret, $client->getSecret())) {
```

Client secret hashing seems over-complicated to me

**Comment by alexbilbie** [comment]
Agreed. Have fixed

**Comment by juliangut** [comment]
Note that it must be stated on the docs that client secret must be a password_hash(ed) string
