### ISSUE TITLE
V5 - repositories visibility on AbstractGrant

### ISSUE THREAD

**Issue by juliangut** [thephpleague/oauth2-server#463]
I've just noticed that `authCodeRepository` and `refreshTokenRepository` are private in contrast to all the other repositories that are protected. All repositories should share the same visibility, either protected or private (and provide accessors for them)

For example `RefreshTokenGrant` uses `accessTokenRepository` and immediately after calls `getRefreshTokenRepository()` (https://github.com/thephpleague/oauth2-server/blob/V5-WIP/src/Grant/RefreshTokenGrant.php#L70):

```php
// Expire old tokens
$this->accessTokenRepository->revokeAccessToken($oldRefreshToken['access_token_id']);
$this->getRefreshTokenRepository()->revokeRefreshToken($oldRefreshToken['refresh_token_id']);
```

**Comment by alexbilbie** [comment]
Oversight on my part. Will fix

**Comment by alexbilbie** [comment]
Cheers for the PR!
