### ISSUE TITLE
$this->getRequest()->headers->get('Authorization') is NULL (but I can see it is there)

### ISSUE THREAD

**Issue by martynbiz** [thephpleague/oauth2-server#471]
I've got as far as issuing an access token, and now I'm trying to access a resource with the token. It's been a bit of beast to get this far, but I've hit a point that appears to be a bug in the ResourceServer class?

I'm a little new to debugging these libraries so my method is a little untidy, hopefully it makes sense (or highlights a clear error on my part)

On the oauth2-client library end, I'm just outputing the response from the resource server with the access token to screen:

```php
protected function fetchResourceOwnerDetails(AccessToken $token)
    {
        $url = $this->getResourceOwnerDetailsUrl($token);

        $request = $this->getAuthenticatedRequest(self::METHOD_GET, $url, $token);



// debug - messy I know, but this is just to catch the raw response
$response = $this->sendRequest($request);
$parsed = $this->parseResponse($response);
var_dump($parsed, $request->getHeaders()); exit; // I can confirm that the Authorization header is present here
// $this->checkResponse($response, $parsed);
```
On the server end, in this ResourceServer (during $server->isValidRequest() call) method:

```php
public function determineAccessToken($headerOnly = false)
    {
        var_dump(getallheaders()); // Yes, I can see the Authorization header "Bearer ..."
        var_dump(get_class($this->getRequest())); // Symfony\Component\HttpFoundation\Request
        var_dump($this->getRequest()->headers->get('Authorization')); exit; // NULL

        if ($this->getRequest()->headers->get('Authorization') !== null) {
            $accessToken = $this->getTokenType()->determineAccessTokenInHeader($this->getRequest());
        } elseif ($headerOnly === false && (! $this->getTokenType() instanceof MAC)) {
        ...
```

Result of my var_dumps:

Response from Server:
```
string(287) "array(3) { ["User-Agent"]=> string(50) "GuzzleHttp/6.1.1 curl/7.35.0 PHP/5.5.9-1ubuntu4.14" ["Host"]=> string(16) "sso.jt.martyndev" ["Authorization"]=> string(47) "Bearer ebfvoqKIUAh288x0JZgeGUrl2dIUKF5fUYnPpfb5" } 

string(40) "Symfony\Component\HttpFoundation\Request" 

NULL " 
```

Client request headers
```
array(2) { ["Host"]=> array(1) { [0]=> string(16) "sso.jt.martyndev" } ["Authorization"]=> array(1) { [0]=> string(47) "Bearer ebfvoqKIUAh288x0JZgeGUrl2dIUKF5fUYnPpfb5" } } 
```

As it's vendor code I can't just easily change the `if ($this->getRequest()->headers->get('Authorization') !== null) {`. Also, not really enough experience yet to suggest a PR if it is a bug (I'll work on that though :). Thought I should ask anyway as it appears that my client is providing the header, but the if condition will never pick it up (as it's method of detecting it results in NULL)

**Comment by martynbiz** [comment]
OK seems I had to add the following to .htaccess

```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

My bad :)

http://stackoverflow.com/questions/11990388/request-headers-bag-is-missing-authorization-header-in-symfony-2

**Comment by alexbilbie** [comment]
I will add this information to the documentation

**Comment by isaaciss** [comment]
I had the same problem but using JWT. I've sent the Authorization Token in Request Headers but it wasn't showed when I used Symfony method $this->getRequest()->headers->get('Authorization'). I changed my apache2.conf -> Directory /var/www/ to "AllowOverride All" and now everything is fine.
