### ISSUE TITLE
Discussion - OpenSSL padding

### ISSUE THREAD

**Issue by juliangut** [thephpleague/oauth2-server#479]
Organizing the ideas around OpenSSL padding

As per @paragonie-scott comment if no padding is specified in https://github.com/thephpleague/oauth2-server/blob/V5-WIP/src/CryptTrait.php#L74 we end up in this problem [ZF2015-10](http://framework.zend.com/security/advisory/ZF2015-10)

As per PHP documentation openssl_private_encrypt and openssl_public_decrypt don't accept `OPENSSL_PKCS1_OAEP_PADDING` as padding parameter

On the other hand openssl_public_encrypt and openssl_private_decrypt do accept `OPENSSL_PKCS1_OAEP_PADDING` padding

Having a look at how zendframework/zend-crypt handles this `OPENSSL_PKCS1_OAEP_PADDING` is used for [public encryption](https://github.com/zendframework/zend-crypt/blob/master/src/PublicKey/Rsa/PublicKey.php#L82) and [private decryption](https://github.com/zendframework/zend-crypt/blob/master/src/PublicKey/Rsa/PrivateKey.php#L118) while `OPENSSL_PKCS1_PADDING` is used on the other way around

As per @alexbilbie comment:

> My thinking is that the authorization server signs things with it's private key.
>
> The resource server and anything else that needs to validate access tokens can use the public key to verify the integrity of the token.

But according to previously shown information `OPENSSL_PKCS1_OAEP_PADDING` can't be used to encrypt with private key

The other way of seing token encryption is that the server encrypts tokens with its public key so only the server can read them back (authorization and resource servers should share same keys). This is my thinking

What is the case of someone else checking token integrity? (really asking)

**Comment by alexbilbie** [comment]
I don't believe anything other than the authorization server should have the private key because the key holder is able to generate valid tokens

**Comment by paragonie-scott** [comment]
> As per PHP documentation openssl_private_encrypt and openssl_public_decrypt don't accept OPENSSL_PKCS1_OAEP_PADDING as padding parameter
> 
> On the other hand openssl_public_encrypt and openssl_private_decrypt do accept OPENSSL_PKCS1_OAEP_PADDING padding

Oh geez, I read that backwards. Sorry, that detail is really important.

You probably want to use `openssl_sign()` and `openssl_verify()`, but sadly there's no way to (reliably) achieve RSASSA-PSS from PHP without using e.g. PHPSeclib by @terrafrost et al.

**Comment by alexbilbie** [comment]
I'm closing this for now because I don't believe this is an issue with how the library has implemented encryption (i.e. use private key to encrypt, public key to verify)
