### ISSUE TITLE
Move Entities Interfaces out

### ISSUE THREAD

**Issue by juliangut** [thephpleague/oauth2-server#504]
In all cases but Entities interfaces are at the same level as implementations

* `GrantTypeInterface` and its implementations
* `ResponseTypeInterface` and its implementatios and 
* `RendererInterface` and template renderer implementations

But in the case for Entities a new NS is created to hold interfaces. I'd suggest to move them up one level directly under Entities directory

**Comment by alexbilbie** [comment]
Fixed by 4eee48c
