### ISSUE TITLE
Question about password grant

### ISSUE THREAD

**Issue by rubenalliet** [thephpleague/oauth2-server#507]
When I'm trying to test the password grant method from the examples folder of your github I have the following problem.

When I send the post request with the following URL and body parameters. 

![image](https://cloud.githubusercontent.com/assets/10956432/14159177/a82d5dd8-f6d4-11e5-8334-ff3e64328d43.png)

I get this as result from my localhost:

![image](https://cloud.githubusercontent.com/assets/10956432/14159294/5d06af48-f6d5-11e5-9fd9-c329534b8a7b.png)

And if I take a look at the code: 

![image](https://cloud.githubusercontent.com/assets/10956432/14158981/a19820d0-f6d3-11e5-9113-467a0d22f04d.png)

It would be very nice if you would help me.
Because I'm starting to get desperate :D

**Comment by frederikbosch** [comment]
@rubenalliet Insert `echo $e->getMessage()` or `var_dump($e);` or `dd($e)` on line 56 to see the exception message and location where the exception is thrown. The exception is not coming from this oauth2 server package, but from somewhere else.

The error says. You are calling method `$e->errorType()` on class `\InvalidArgumentException` but that class does not contain such method. That is correct. See the methods on the [`\InvalidArgumentException`](http://php.net/manual/en/class.invalidargumentexception.php).

It would be even better to extend the try-catch block.

```php
try {
  $response = $server->issueAccessToken();
  return new Response(json_encode($response));
} catch (\InvalidArgumentException $e) {
  dd($e); // show me what is going on here
} catch (\Exception $e) {
  // handling of other exceptions
}
```
