### ISSUE TITLE
Question about Refresh Token Grant

### ISSUE THREAD

**Issue by sajunafernando** [thephpleague/oauth2-server#508]
Hi,

I have a question about using the refresh token grant. 

I want my refresh tokens to be long lived and without any rotation so i have setup it up like below.

```
$refreshTokenGrant = new League\OAuth2\Server\Grant\RefreshTokenGrant();
$refreshTokenGrant->setRefreshTokenTTL(7776000);
$refreshTokenGrant->setRefreshTokenRotation(false);
```
I then try to obtain a new access_token using this refresh_token. It works and gives me back a new access_token. However, its does NOT link this new access_token against the old refresh_token. The refresh_token is still linked to the old access_token which is now deleted after the new access_token is issued.

Having a look at the completeFlow() on the League\OAuth2\Server\Grant\RefreshTokenGrant i cant see any attempt to update the refresh_token when the rotation is turned off.

Is this a bug?

**Comment by alexbilbie** [comment]
Are you using v4 or v5 of the library?

Either way refreshing an access token results in a new access token and
refresh token off the top of my head.

**Comment by sajunafernando** [comment]
@alexbilbie Im using the v4 (have not updated to the v5 as of yet).

It should not result in a new refresh token if 'shouldRotateRefreshTokens' is set to false i thought?

Otherwise i do not see the point in having a long lived refresh token i'm afraid, if the refresh token too gets renewed every time.

**Comment by alexbilbie** [comment]
There might be a bug there.

I'm afraid I'm travelling in Asia without a computer for another week so I
can't debug at the moment. No one else has reported a similar bug as far as
I can recall.

If you find a solution please let me know back here and I will take action
when I'm home.

**Comment by sajunafernando** [comment]
Hey @alexbilbie,

Thats all right. I think what needs to happen is as below in the completeFlow of the refresh token grant.

Currently:

```
        if ($this->shouldRotateRefreshTokens()) {
            // Expire the old refresh token
            $oldRefreshToken->expire();

            // Generate a new refresh token
            $newRefreshToken = new RefreshTokenEntity($this->server);
            $newRefreshToken->setId(SecureKey::generate());
            $newRefreshToken->setExpireTime($this->getRefreshTokenTTL() + time());
            $newRefreshToken->setAccessToken($newAccessToken);
            $newRefreshToken->save();

            $this->server->getTokenType()->setParam('refresh_token', $newRefreshToken->getId());
        } else {
            $this->server->getTokenType()->setParam('refresh_token', $oldRefreshToken->getId());
        }
```

Should be:

```
        if ($this->shouldRotateRefreshTokens()) {
            // Expire the old refresh token
            $oldRefreshToken->expire();

            // Generate a new refresh token
            $newRefreshToken = new RefreshTokenEntity($this->server);
            $newRefreshToken->setId(SecureKey::generate());
            $newRefreshToken->setExpireTime($this->getRefreshTokenTTL() + time());
            $newRefreshToken->setAccessToken($newAccessToken);
            $newRefreshToken->save();

            $this->server->getTokenType()->setParam('refresh_token', $newRefreshToken->getId());
        } else {

           $oldRefreshToken->setAccessToken($newAccessToken);
           $oldRefreshToken->save();

            $this->server->getTokenType()->setParam('refresh_token', $oldRefreshToken->getId());
        }
```

**Comment by sajunafernando** [comment]
Have you pushed a fix to the V4?
