### ISSUE TITLE
AbstractGrant::generateUniqueIdentifier() uses random_bytes() which is available only since PHP 7

### ISSUE THREAD

**Issue by warlock39** [thephpleague/oauth2-server#510]
So implementation does not satisfy requirements for older PHP versions.

For example under PHP 5.5 i got fatal error: `Fatal error: Call to undefined function League\OAuth2\Server\Grant\random_bytes()`

**Comment by alexbilbie** [comment]
Hmm there is a dependency on paragonie/random_compat which has a backwards compatible implementation of random_bytes.

I'm currently travelling and don't have access to a computer to investigate; if you do solve this please let me know so I can ensure any fixes are in the final build

**Comment by warlock39** [comment]
I can't reproduce it anymore. I guess there were problem with composer cache or so.

Thank you for reply.
