### ISSUE TITLE
Redirect uri is required only if the "redirect_uri" parameter was included in the authorization request

### ISSUE THREAD

**Issue by warlock39** [thephpleague/oauth2-server#514]
It's about authorization code grant for v5 of league oauth server. 
According to specification section [4.1.3. Access Token Request](https://tools.ietf.org/html/rfc6749#section-4.1.3 ), "redirect_uri" parameter is required only in case when it was included in the authorization request.

Currently, it is required in any case.

**Comment by alexbilbie** [comment]
Good spot. This will be an easy fix; the auth code can contain a boolean flag to determine if a redirect uri was used.

**Comment by alexbilbie** [comment]
This has been fixed for RC2
