### ISSUE TITLE
Reusing CryptTrait facilities

### ISSUE THREAD

**Issue by msimkunas** [thephpleague/oauth2-server#541]
In 5.0.0-RC1, the authorization grant generated an `oauth_authorize_request` cookie which was encrypted and decrypted using the protected methods in `CryptTrait`. 5.0.0-RC2 refactored the authorization code grant to allow for more flexible login and authorization form handling which moved the cookie creation logic outside of the authorization grant class.

Should we use the `CryptTrait` trait in a custom service class to be able to encrypt/decrypt the `oauth_authorize_request` cookie outside of `AuthCodeGrant`? As it stands now, the encryption facilities can only be reused by extending the grant class OR by implementing a separate class which uses the `CryptTrait`.

I believe that this is implementation-specific because this cookie may not be a cookie at all. It could, for example, be a database row with a unique random identifier which would not require encryption. However, if we want to utilize a cookie for this purpose we need to be able to encrypt it to prevent the `user_id` from being changed by the user. Would it be possible to somehow reuse the `encrypt`/`decrypt` methods of the `AuthCodeGrant` outside the grant class?

**Comment by alexbilbie** [comment]
Hi @msimkunas,

The cookie stuff from RC1 was very much a hack and shouldn't be relied on going forward. As discussed in #499; it's better than the developer working with the library implement session stuff rather than this library try and work with it.

**Comment by msimkunas** [comment]
I suppose you’re right then, authorization request persistence options are probably beyond the scope of this library.

I’ve implemented a class that uses the `CryptTrait` trait for encrypting cookies. It works fine, although I’m considering switching to a database-based authorization request persistence (i.e. storing the authorization request details such as the user ID in a database row and assigning a unique random ID to it which could be later stored in a cookie). What would you recommend though?

Using the database in this particular case does not require encryption, but it does mean that scheduled cleanups need to be in place to avoid cluttering the DB with intermediate request details. 

> The cookie stuff from RC1 was very much a hack and shouldn't be relied on going forward.

Do you mean that using encrypted cookies for storing request details is a bad idea in general or simply that it shouldn't be part of this library?

**Comment by alexbilbie** [comment]
> Do you mean that using encrypted cookies for storing request details is a bad idea in general or simply that it shouldn't be part of this library?

It shouldn't be part of this library

> I’m considering switching to a database-based authorization request persistence (i.e. storing the authorization request details such as the user ID in a database row and assigning a unique random ID to it which could be later stored in a cookie). What would you recommend?

When you say storing authorisation request persistence what do you mean by this exactly? That the user has already approved a client?

**Comment by msimkunas** [comment]
> When you say storing authorisation request persistence what do you mean by this exactly? That the > user has already approved a client?

I am referring to the role of `oauth_authorize_request` cookie in 5.0.0-RC1.

**Comment by alexbilbie** [comment]
Ah right.

My recommendation is that you completely disregard the implementation from RC1. The bundling into the library of the authentication and authorising HTML pages with templating tied together with the encrypted cookie was a big hack because I was trying to provide what I thought was a simple solution but ultimately it added a huge amount of technical debt to the library.

As a result the `oauth_authorize_request` cookie has gone, it means nothing to the library.

You're free to use any sort of session/cookie management you want to track users as they travel through the authentication and authorisation screens.

**Comment by msimkunas** [comment]
Now when I think of it, issuing random (meaningless) session identifiers and storing the actual request data in the database may be a better solution than encrypted cookies for security reasons. This design would also allow me to avoid storing sensitive data on the client.

**Comment by msimkunas** [comment]
I was wondering whether this library would receive more major refactors until a stable v5 is released? The jump from RC1 to RC2 required me to perform quite a big refactoring on my project and I would be interested to know about any plans regarding the schedule of the next stable release.

**Comment by alexbilbie** [comment]
There are a few small internal fixes merged in but otherwise for the rest
of this week I intend on improving documentation and testing.

At this point I'm feel fairly confident to say that there won't be anymore
developer API changes to version 5.
