### ISSUE TITLE
[question][v5] refresh_token decrypt to trigger a revoke of the Token

### ISSUE THREAD

**Issue by ppvolto** [thephpleague/oauth2-server#543]
Hi i  current Try to implement [rfc7009](https://tools.ietf.org/html/rfc7009) in my Test System.
I try to create a Logout but i current have no Idea how i can decrypt the refresh_token, to get the token_id to trigger a Revoke of the same. A Hint on how i can decrypt the refresh_token or how i can Trigger a Revoke or how i can get the RefreshToken Object from the server can help me a lot.

**Comment by alexbilbie** [comment]
The refresh token can be decrypted with the authorisation server's public key
