### ISSUE TITLE
Return values in constructors

### ISSUE THREAD

**Issue by ionux** [thephpleague/oauth2-server#545]
There are a few places in the source for this project where I noticed constructors returning $this.  Are there technically legitimate reasons why this is the case since, by definition, constructors return void and discard return values?

**Comment by alexbilbie** [comment]
Could you give some examples please?

**Comment by ionux** [comment]
Sure, here are a few I found:
https://github.com/thephpleague/oauth2-server/blob/master/src/Entity/AbstractTokenEntity.php#L68
https://github.com/thephpleague/oauth2-server/blob/master/src/Entity/ClientEntity.php#L69
https://github.com/thephpleague/oauth2-server/blob/master/src/Entity/ScopeEntity.php#L55
https://github.com/thephpleague/oauth2-server/blob/master/src/Entity/SessionEntity.php#L96
https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationServer.php#L84
https://github.com/thephpleague/oauth2-server/blob/master/src/ResourceServer.php#L69

**Comment by alexbilbie** [comment]
It was probably over sight many moons ago (a quick glance most were put in December 2013).

As I intend to release V5 imminently I'm not going to release a patch fix as they're not doing any harm.

Thanks for pointing them out though.
