### ISSUE TITLE
How to implement ClientRepositoryInterface::getClientEntity()

### ISSUE THREAD

**Issue by lookyman** [thephpleague/oauth2-server#550]
Talking about Authorization Code grant, but it may apply to others as well.

If the client is confidential, you have to pass the `client_secret` parameter to the access_token endpoint. If you don't do that, this https://github.com/thephpleague/oauth2-server/blob/5b192b3548c769cb74f7565418f7cbc2a7d55203/src/Grant/AbstractGrant.php#L161 gets `null` as a `$clientSecret` argument. So you have to make a check in that method, something like "if the client has secret set, compare it with the passed `$clientSecret` and scream if it doesn't match".

All of that is still OK. However, the same method gets called from here https://github.com/thephpleague/oauth2-server/blob/5b192b3548c769cb74f7565418f7cbc2a7d55203/src/Grant/AuthCodeGrant.php#L166, and because here you don't send the `client_secret` parameter, it gets passed `null` every time. But now the check in that method starts to scream.

Am I just missing something important, or is this a bug?

**Comment by alexbilbie** [comment]
You're right, you've found a bug.

The easiest way I can think of resolving this is introducing a 4th parameter on the `getClientEntity` method on the `ClientRepositoryInterface`. This parameter would be a boolean `$mustValidateSecret`.

When `$mustValidateSecret === true` the client repository must attempt to validate the secret if the client is confidential.

For the authorisation and implicit grants, when validating the client as part of the authorisation request `$mustValidateSecret` will be `false`. For the other grants it will be `true`.

(cc/ @assembledadam; I believe you've also found this bug)

**Comment by alexbilbie** [comment]
I've released `5.0.1` which addresses the issue here.

**Comment by lookyman** [comment]
Thank you for a quick response!
