### ISSUE TITLE
Selective scope support?

### ISSUE THREAD

**Issue by MarcinOrlowski** [thephpleague/oauth2-server#552]
I need to support selective scopes, where client can ask for as much as he wants (i.e. `A, B, C` scopes) but can be only granted subset of scopes (i.e. just `B`). I do not need to have user involved here - everything will be done from code.

I'd like to have it for `PasswordGrant` so I checked the sources and I at the moment I am overriding `PasswordGrant`'s `completeFlow()`, do my filtering once user is authorized and it seems like working. My question here is however if this is the right way of implementing this?

**Comment by alexbilbie** [comment]
You can implement all of this in the `finalizeScopes` method of the `ScopeRepositoryInterface`.

This method is called right before an access token or authorization code is created.

Given a client, grant type and optional user identifier validate the set of scopes requested are valid and optionally append additional scopes or remove requested scopes.

This method is useful for integrating with your own app’s permissions system.

You must return an array of ScopeEntityInterface instances; either the original scopes or an updated set.

I hope that helps?

**Comment by MarcinOrlowski** [comment]
I am using https://github.com/lucadegasperi/oauth2-server-laravel/ which is using v4.1.5 of your server. I see in changelog Scopes were Storage before but it also looks like the interface is changed as well. Is it worth trying with v4.1.5?

**Comment by alexbilbie** [comment]
It's probably best to open a Github issue on that Laravel repo as I don't have any involvement with it.

Going back to your original question though overriding the grant is a valid solution
