### ISSUE TITLE
Implement ServerRequestInterface and ResponseInterface

### ISSUE THREAD

**Issue by rleonr** [thephpleague/oauth2-server#557]
I am trying create implementations following a flow similar to the one suggested in the documentation. Where can I find those interfaces? I am using pure php, not slim framework.

**Comment by alexbilbie** [comment]
All of the interfaces are documented here https://oauth2.thephpleague.com (at the bottom on the left).

The Slim framework example is purely for demonstration, there's no requirement for you to use it

**Comment by rleonr** [comment]
Not really. For instance, in the password grant implementation example
found on your website, you are creating
a \League\OAuth2\Server\AuthorizationServer called $server. Then you call
the method respondToAccessTokenRequest($request, $response);  My issue is
that neither the ServerRequestInterface and ResponseInterface are
documented. How can I integrate the $server variable with my
Request/Response mechanisms if those details are unknown?

Thanks in advance,
Ricardo

2016-04-25 5:42 GMT-04:00 Alex Bilbie <notifications@github.com>:

**Comment by alexbilbie** [comment]
The ServerRequestInterface and ResponseInterface are [PSR-7](http://www.php-fig.org/psr/psr-7/) implementations provided by your HTTP library. Most frameworks (Symfony, Laravel, Slim, Zend) as well as many libraries generate PSR-7 request and responses and it is these that the AuthorizationServer is expecting to be injecting in.
