### ISSUE TITLE
Mistake in Password Credentials Grant documentation page

### ISSUE THREAD

**Issue by carlosmojopicon** [thephpleague/oauth2-server#562]
There is a mistake in Password Credentials Grant documentation page [http://oauth2.thephpleague.com/authorization-server/resource-owner-password-credentials-grant/](url)
Instead of:
`$grant->setRefreshTokenTTL(new \DateTime('P1M'));`
It should be:
`$grant->setRefreshTokenTTL(new \DateInterval('P1M'));`

**Comment by alexbilbie** [comment]
Thanks @ca]
