### ISSUE TITLE
Shouldn't BearerTokenValidator check for token existence?

### ISSUE THREAD

**Issue by lookyman** [thephpleague/oauth2-server#565]
Currently it only checks that the token hasn't been revoked [here](https://github.com/thephpleague/oauth2-server/blob/acf262f879b148106a6672b812efc77476970c61/src/AuthorizationValidators/BearerTokenValidator.php#L67). But that method is supposed to return boolean, and documentation doesn't mention what to do when the token doesn't exist at all. So, a naive implementation could just return false ("I have no information that this token has been revoked, because it doesn't exist at all."), and the authorization goes through.

**Comment by alexbilbie** [comment]
A good question!

A missing access token and an improperly signed token would be caught [here](https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationValidators/BearerTokenValidator.php#L53-L56) and therefore it shouldn't be possible for the scenario you suggested to happen.

**Comment by lookyman** [comment]
Suppose the attacker gets hold of a server's private key..

**Comment by alexbilbie** [comment]
Security of the actual server is out of scope of this library. I will add
to the docs that it's probably a good idea to rotate keys every so often
