### ISSUE TITLE
Refresh grant and scopes

### ISSUE THREAD

**Issue by carlosmojopicon** [thephpleague/oauth2-server#568]
When doing a refresh grant request, it responds with invalid_scope message. 

After doing some debugging in RefreshTokenGrant.php I realized the error comes from `respondToAccessTokenRequest()` function when getting `$oldRefreshToken` array.

A `var_dump($oldRefreshToken['scopes'])` results in something like this:
```
array(7) {
  [0]=>
  array(1) {
    ["id"]=>
    string(17) "moderate_comments"
  }
  [1]=>
  array(1) {
    ["id"]=>
    string(10) "edit_users"
  }
  [...]
}
```

I'm not sure if I did something wrong when implementing scope repository, but the following lines for sure does not work with such a `$oldRefreshToken['scopes']` "array of associative arrays" structure, since my `getScopeEntityByIdentifier` implementation expects `$scopeId` as a string value:

```
$scopes = array_map(function ($scopeId) use ($client) {
				
          $scope = $this->scopeRepository->getScopeEntityByIdentifier($scopeId);
				
          if (!$scope instanceof ScopeEntityInterface) {
                    // @codeCoverageIgnoreStart
                    throw OAuthServerException::invalidScope($scopeId);
                    // @codeCoverageIgnoreEnd
          }

          return $scope;
  }, $oldRefreshToken['scopes']);
```

Something similar occurs when passing new scopes to the refresh token request, in this few lines:

```
foreach ($scopes as $scope) {
       if (in_array($scope->getIdentifier(), $oldRefreshToken['scopes']) === false) {
                 throw OAuthServerException::invalidScope($scope->getIdentifier());
       }
  }
```

**Comment by alexbilbie** [comment]
Sorry for the late reply on this; how are you implementing the `jsonSerialize` on your `ScopeEntityInterface` implementation?

**Comment by carlosmojopicon** [comment]
My fault, i've implemented it as `return $this;`. Changed it to `return $this->id;` and now it works like a charm.

**Comment by alexbilbie** [comment]
Glad to hear you've resolved it 👍
