### ISSUE TITLE
General guidelines on implementing this library

### ISSUE THREAD

**Issue by isko-algorithm** [thephpleague/oauth2-server#580]
Hello!

I still am somehow confused in making this library work. I am implementing a client credentials grant type  (using MySQL as storage) in my API and after installing, I'm kind of lost on what to do next.  Can anyone help? Thanks!

**Comment by alexbilbie** [comment]
Have you followed the docs here https://oauth2.thephpleague.com/authorization-server/client-credentials-grant/ ?

**Comment by isko-algorithm** [comment]
Oh. Sorry for the oversight. I'm looking at the repository interfaces, which I thought I should implement for all classes. I'll try this one first. Thanks!

**Comment by isko-algorithm** [comment]
hey, question: is it possible to use this library without having a public/private key?

**Comment by isko-algorithm** [comment]
is it possible to make this work without public and private keys? If not, where should the public and private keys be in a client_credentials grant type?

**Comment by alexbilbie** [comment]
Public and private keys are required.

You should store them outside the web root on your server

**Comment by isko-algorithm** [comment]
Okay. Now I'm on the part where three repositories are there. so should I implement them in three classes, perhaps? then what should I do to register the mysql database I am using for usage in this library?

**Comment by alexbilbie** [comment]
It is best practise to implement the interfaces as individual classes.

You database interaction takes place inside the methods of those classes.

**Comment by isko-algorithm** [comment]
okay. now how, for example, can I set mysql to be the storage choice for both my access tokens and my clients?

**Comment by alexbilbie** [comment]
You do this inside the relevant interface method; so for clients retrieve them from the database in this method https://oauth2.thephpleague.com/client-repository-interface/

**Comment by isko-algorithm** [comment]
I've seen in your example files that the client repository has one client which is hardcoded. Can a normal mysql call replace this? How would I do this?

**Comment by alexbilbie** [comment]
> Can a normal mysql call replace this?

yes

**Comment by isko-algorithm** [comment]
Okay I got this. thanks!
