### ISSUE TITLE
Invalid Request - Cannot decrypt the authorization code

### ISSUE THREAD

**Issue by bobmulder** [thephpleague/oauth2-server#582]
Hi,

I tried to implement the `/access_token` endpoint, but the following exception raises:

```
{
  "error": "invalid_request",
  "message": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
  "hint": "Cannot decrypt the authorization code"
}
```
What I did:

- Implemented the `/authorize` endpoint. For example: `http://auth.myapi.dev/authorize?response_type=code&client_id=573c65967b34d6938827976&grant_type=authorization_code&state=test_state&scope=scope_1 scope_2&redirect_uri=https://www.getpostman.com/oauth2/callback`
- I put this request in my browser and got back: `https://app.getpostman.com/oauth2/callback?code=TQwFP9FNd%2F8kGD%2FBX5QeFTFGPdnXV0lsNKltFWzpQzgX6%2Bu3Rg%2BT0cEcDBc9HNUTCAm%2BebuR5ccgnUpApXuZvp5jx%2FtN%2FgKfrMRGzp6Pbq5LYAaIbx4o62SVSXpyaFdRYcAdudg0NEq2RXtLUW9PF9dYLERRAeGEJfi0RLEWp%2FFlItqFsaz%2Ba6IUF9qpDrlcylBhFsSX0FcfD%2Bd6oZ08Hyi4Yksx9hgezp5xQondy%2B%2Bd0VPB56Z4AjuIsAUsR1VO7m0Zz%2FBvrJyZ9Vp5Bua9stG%2B%2FusoK2BO3k2C2kF%2B2PZCiwYmNhC6j%2BQtswSbWrik2IDa0XLVVrGLq9UYD4mN8ZTxhMknygB6VANR6lThaTCdByljU0C7eCB54bdX34e7NCINBI56Dxje302WBN7N5mAm6dtrRLKfwjg9tv6c4fErl%2BrSrshoK7VymzZIhlTTkvcz2yCKhPbciIBRT3%2BKlSJRI3HsesSVqrH7%2FMfZOSIoecZ7oHfRvzj7xZRXbYoc&state=test_state`
- I took the `code` query from that url, and put it in the `code` key of my body of the `/access_token` request...

Can you confirm this is right?

I've recreated my keys multiple times, but no result...

**Comment by alexbilbie** [comment]
Are you `url_decode`-ing the auth code first before sending?

**Comment by bobmulder** [comment]
I do not @alexbilbie. How should I do that? Passing the string of the `code` query isn't good?

**Comment by alexbilbie** [comment]
`url_decode` the `code` parameter before sending it the authorisation server to get an access token

**Comment by bobmulder** [comment]
Ahh amazing! That did the trick ;)

Thanks @alexbilbie ;) :+1:

**Comment by alexbilbie** [comment]
I will update the documentation to make it clearer

**Comment by bobmulder** [comment]
I am already doing ;)

**Comment by alexbilbie** [comment]
@ChrisTitos is your code definitely URL-decoding in the final API call to get an access token?

**Comment by ChrisTitos** [comment]
This is the code in the test:

```
$I->canSeeInCurrentUrl( '?code=' );
$code = urldecode( $I->grabFromCurrentUrl( '/code=([-\w\s+%]+$)/' ) );
$I->sendPOST( '/oauth/access_token',
        [
            'grant_type'    => 'authorization_code',
            'client_id'     => $this->client->getID(),
            'client_secret' => $this->client->getSecret(),
            'redirect_uri'  => $this->client->getRedirectUris()[0],
            'code'          => $code
        ] );
```

As you can see in my previous comment, the code I get back is:
`ahD2esbfUDIW9EGoBfslHReMJlUvZb1R4A9pxR2g9O0u1yGC3M5HMBIPLhONqq%2BzcBMDYN0Af7l094Qrxd7Zcy6SGi6K6zPfZGMC%2BVQAevimGCs%2FZVmz2momRWvfEp254N80IBF9KPuNkiAQCxa%2B6kr9fGs8A59fE%2BKQ6gwfm5CEa9I2maelG927er%2BtA5zpuRQ5PmXyXx5V2vriISMbVXvzAqavOxYz6pTF4%2FlGeDDz9tFziYqJdeZIon1Uy9HgHavHuqYLgR0E6c2kK8Rzs0zxLhhbNlhEsOEtCn4T443ZH5ofXlxcJGgG2nQGtcRNGsKxl4gsK2AEkAapMWAZb1q4wwDpQMD7GDeKSiAX9VM%2FVrzKIOJwlTm5K3KahX2x6Url1VUO2gcC8fZMhTdNjyJWZHI76GirVFbA5bdHdzn9R7AMk9vy5hbUOBf0jO8N6LQqZWUoXcJCHAzztIrbUGozXgLX0PQQvvxWVlncw7Ybry6%2FYLfIp7o94eNIYQyt`

And the code I POST is:

`ahD2esbfUDIW9EGoBfslHReMJlUvZb1R4A9pxR2g9O0u1yGC3M5HMBIPLhONqq+zcBMDYN0Af7l094Qrxd7Zcy6SGi6K6zPfZGMC+VQAevimGCs/ZVmz2momRWvfEp254N80IBF9KPuNkiAQCxa+6kr9fGs8A59fE+KQ6gwfm5CEa9I2maelG927er+tA5zpuRQ5PmXyXx5V2vriISMbVXvzAqavOxYz6pTF4/lGeDDz9tFziYqJdeZIon1Uy9HgHavHuqYLgR0E6c2kK8Rzs0zxLhhbNlhEsOEtCn4T443ZH5ofXlxcJGgG2nQGtcRNGsKxl4gsK2AEkAapMWAZb1q4wwDpQMD7GDeKSiAX9VM/VrzKIOJwlTm5K3KahX2x6Url1VUO2gcC8fZMhTdNjyJWZHI76GirVFbA5bdHdzn9R7AMk9vy5hbUOBf0jO8N6LQqZWUoXcJCHAzztIrbUGozXgLX0PQQvvxWVlncw7Ybry6/YLfIp7o94eNIYQyt`

I get the same error when I manually go through the flow, urldecode the auth code (using [this for example](https://www.functions-online.com/urldecode.html)) and POST it via my REST client app.

**Comment by ChrisTitos** [comment]
I tried regenerating the public and private keys, with or without a passphrase. I also tried grabbing the auth code directly from the result of `encrypt` and using that for the POST request.

Still no luck.  `openssl_public_decrypt` immediately returns false.

**Comment by alexbilbie** [comment]
Which version of PHP are you running and with which versions of OpenSSL?

**Comment by ChrisTitos** [comment]
PHP 5.6

OpenSSL version:
```
OpenSSL 1.0.1e-fips 11 Feb 2013
built on: Mon May  9 07:30:30 CDT 2016
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic
```

On CentOS 6.7

**Comment by ChrisTitos** [comment]
Ok, I found out what was the problem. I turns out I had mbstring function overloading enabled:

http://php.net/manual/en/mbstring.overload.php

Turning it off solved my problem. 

(now to find out why it was enabled in the first place :/ )

**Comment by jihanalireza** [comment]
how to urldecode this code bro
