### ISSUE TITLE
How to obtain the client data by specific access_token (question)

### ISSUE THREAD

**Issue by joseluisq** [thephpleague/oauth2-server#585]
I have this access_token:
`POST http://localhost:8000/v1/user/add/?access_token=a31b28c8aa62f9b86680650d90f3b82d832e73bc`
and in backend, I would like to obtain the `client` data associated to this incoming `access_token`.

Is it possible to access a client data from `oauth_clients` (`client_id`, `client_secret`, `redirect_uri`, `grant_types`, `scope`, `user_id`) by valid `access_token`?

Thanks in advance!

**Comment by alexbilbie** [comment]
Please see
https://oauth2.thephpleague.com/resource-server/securing-your-api/

**Comment by joseluisq** [comment]
Awesome :+1: 
Thanks
