### ISSUE TITLE
Scopes 

### ISSUE THREAD

**Issue by TommyBs** [thephpleague/oauth2-server#589]
Hi,

Not really an issue with the code but I'm trying to understand the example a bit better.
On https://github.com/thephpleague/oauth2-server/blob/master/examples/src/Repositories/UserRepository.php

What does the 'scopes' refer to here as it doesn't seem to be used or stored anywhere in a member variable? Also I'm not sure why the grantType and $clientEntity are here and what they would be used for.

Is this detailed more in the OAuth specs?

Thanks

**Comment by alexbilbie** [comment]
Ah I understand now. It looks like a copy and paste error on my part. I
will remove it when I'm next at a computer.

Sorry for the confusion.

**Comment by TommyBs** [comment]
Ah, though thinking about it, I assume the Client Entity would allow me to see what scopes the Client had requested and had been approved by the user, then I could in theory set the scopes on a suitable object somewhere or filter what data the userEntity makes available

**Comment by alexbilbie** [comment]
See the finalizeScopes method on the ScopeRepository for that

**Comment by TommyBs** [comment]
Thanks, the example just seems to return the input though, https://github.com/thephpleague/oauth2-server/blob/master/examples/src/Repositories/ScopeRepository.php 

But haven't looked at the docs as well (https://oauth2.thephpleague.com/scope-repository-interface/ )  I can see what I'm meant to do. Thanks for your help I'm finding my way around it all more now.
