### ISSUE TITLE
No other redirect_uri allowed?

### ISSUE THREAD

**Issue by bobmulder** [thephpleague/oauth2-server#590]
When I have a client with an `redirect_uri` AND I do the `/authorize` request with a different `redirect_uri` the request fails. Where this goes wrong is at the file `/league/oauth2-server/src/Grant/AuthCodeGrant.php` on line 190:

```
$redirectUri = $this->getQueryStringParameter('redirect_uri', $request);
        if ($redirectUri !== null) {
            if (
                is_string($client->getRedirectUri())
                && (strcmp($client->getRedirectUri(), $redirectUri) !== 0)
            ) {
                $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
                throw OAuthServerException::invalidClient();
```

> Last line is line 190

So this code tells me: "When the client does have a `redirect_uri` set AND the request contains a `redirect_uri`, I am going to compare those, and throw an error when they're not equal.

Can anybody confirm this is right? In my usecase it's very strange.

#### Usecase
I am building my docs with RAML. It has a 'Try-now' functionality where you can try your API and get access with OAuth2. So the Api Console will set a different `redirect_uri` as I choose when registering my API. When the `/authorize` screen will pop up, I get the exception as mentioned above.

#### Example
Another thing why this problem sounds strange is; Imagine you want to access an API via a 'Try now' tool or whatever. It will return to another `redirect_uri` as well, but it won't throw an exception...

So, please confirm me what's going on here.

**Comment by alexbilbie** [comment]
Redirect URIs are whitelisted because otherwise there is an "open redirector" vulnerability attack vector.

**Comment by bobmulder** [comment]
In that case I question myself why you should add the `redirect_uri` in the request if you should add it to the client...

**Comment by alexbilbie** [comment]
Because it is possible to return an array of whitelisted redirect URIs on the ClientEntity (https://github.com/thephpleague/oauth2-server/blob/master/src/Entities/ClientEntityInterface.php#L28-L35) and then in the `redirect_uri` parameter indicate which one you wish to the user to be returned to.

So for example you might have a production and a development URI registered and returned in that array.

**Comment by bobmulder** [comment]
Oh I get it! Didn't know that it could be an URL as well! Thank you for making this clear Alex!
