### ISSUE TITLE
Does the server support multiple grant_types with one server?

### ISSUE THREAD

**Issue by TommyBs** [thephpleague/oauth2-server#592]
Hi,

Can I implement multiple grant types? If so how would token validation work?

For instance I have an api that might have protected resources that require a user to be validated before they can access them. Now as the Api can be used by first and 3rd party apps, the first party apps can obviously use the password grant, whereas the 3rd party apps will use the Auth Code grant.

On top of this any request to any non-secure (as in public available even over https) endpoint, should validate that it has come from a valid app, now I'm toying with just having an appKey header or whether I should use 'client credentials' scope here?

I suppose what I'm not sure on, is how to secure a private endpoint that require a user access token and stop someone just supplying the client access token to bypass this? Is there a way to validate the type of token to determine if it should be able to access a specific resource?

**Comment by alexbilbie** [comment]
Good question.

When an access token is parsed a number of attributes are set on the PSR-7
Request object (see
https://oauth2.thephpleague.com/resource-server/securing-your-api/#implementation
).

You could add some logic to your API to determine whether or not both the
user and the client are allowed to access the endpoint (based on the
request attributes).

**Comment by TommyBs** [comment]
Hi sorry for the late follow up to this.

I've been thinking about this, and there could be cases where either type is allowed to access the same endpoint. Similar to a facebook app where I could query a user endpoint with an app access token or a user access token and the response is different depending on which it is. In your response are you suggesting then that I should just check whether a oauth_user_identifier is part of the request to determine if it's a user or an app token?

Do you think it would be a security risk to put the 'grant_type' as a parameter in the JWT? Then check this? Would this be tamper proof from outsiders bearing in mind they *shouldn't* be able to alter the JWT due to the signature? So something like this

```
public function convertToJWT(CryptKey $privateKey)
    {
        return (new Builder())
            ->setAudience($this->getClient()->getIdentifier())
            ->setId($this->getIdentifier(), true)
            ->setIssuedAt(time())
            ->setNotBefore(time())
            ->setExpiration($this->getExpiryDateTime()->getTimestamp())
            ->setSubject($this->getUserIdentifier())
            ->set('scopes', $this->getScopes())
            ->set('grant_type', $this->getAccessTokenGrantType()) // Get grant type of token
            ->sign(new Sha256(), new Key($privateKey->getKeyPath(), $privateKey->getPassPhrase()))
            ->getToken();
    }

```
Thanks
