### ISSUE TITLE
Is it possible to use this in wordpress?

### ISSUE THREAD

**Issue by shanmugamrsk** [thephpleague/oauth2-server#594]
If the answer is yes, please explain how to use this in wordpress..I like to convert this into wordpress plugin so please guide me to do this..

**Comment by bobmulder** [comment]
In fact you should implement all given repository- and entity interfaces and put wordpress-like queries in it...

**Comment by alexbilbie** [comment]
I'm sure it can probably be used with WordPress but I've not looked at WordPress in years so I couldn't give you any advice in terms of starting I'm afraid.

If you work it out please feel free to update this ticket with a link to a blog post or some advice to others 😄
