### ISSUE TITLE
Discussion: authenticated encryption

### ISSUE THREAD

**Issue by zerkms** [thephpleague/oauth2-server#603]
I have mentioned it in another issue that I closed (due to my misunderstanding of code), but this concern should still be discussed:

https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly

Currently this library uses `openssl_private_encrypt` and `openssl_public_decrypt` functions only to encrypt/decrypt data. I think that's not enough (since the encrypted data is not authenticated) and I think those `openssl` functions should not be used.

Both statements must be confirmed/refuted by security professionals, but I think it is the case here.

As a substitution I suggest the https://github.com/defuse/php-encryption

In case of that library it would be possible to use a secret phrase rather than file-based keys, which is generally much easier to manage.

**Comment by alexbilbie** [comment]
I'm totally open to improving this. I need to do some tests with `defuse/php-encryption` to ensure that it's a backwards compatible change but otherwise 👍

**Comment by zerkms** [comment]
> that it's a backwards compatible change but otherwise

It depends on what you want to be BC. I believe tokens definitely will not be BC, so the support for old ones need to be kept for some time (until next major release since people may have emitted tokens with TTL of few years).

**Comment by alexbilbie** [comment]
Access tokens shouldn't be affected only authorization codes and refresh tokens as they are both encrypted.

Authorization codes are short-lived and are not processed in any way by the client (other than sending it back to the authorization server within a few minutes) so I'm not concerned about BC of those. Refresh tokens are in a similar situation (although the client should know how to deal with expired refresh tokens too).

I'm more concerned about maintaining library-API backwards compatibility but I'm sure it won't be an issue.

**Comment by zerkms** [comment]
> Access tokens shouldn't be affected only authorization codes and refresh tokens as they are both encrypted.

they will be - if you switch from using `openssl_*` functions directly to using that library - the generated tokens will be different (the latter at least adds MAC).

So `decrypt` should be mantained for both implementations (since the decryption would definitely be incompatible), and `encrypt` might be simply swapped.

**Comment by alexbilbie** [comment]
Access tokens are currently JWTs which aren't encrypted (just signed using the private key). Only refresh tokens and authorization codes are encrypted

**Comment by zerkms** [comment]
Oh right. So, then it should be an easy improvement.

**Comment by fgambino** [comment]
It may be wise to version the tokens going forward. Prepend them all with an identifier of some sort. I agree with moving away from file-based keys too. Being able to store the key in an environment variable or database would simplify the setup a lot.

**Comment by zerkms** [comment]
@fgambino what is the purpose of the version?

**Comment by fgambino** [comment]
@zerkms if the encryption scheme is ever changed again, the library will know how to handle any incoming tokens. If somebody has a long-lived refresh token that isn't versioned, it would get messy trying to figure out how to validate it.

**Comment by defuse** [comment]
The `openssl_private_encrypt` and `openssl_public_decrypt` are asymmetric crypto, not interchangeable with the symmetric crypto in https://github.com/defuse/php-encryption (unless what's being done currently is to use asymmetric crypto as if it were symmetric crypto).

**Comment by Sephster** [comment]
@alexbilbie changed the library to use the _php-encryption_ library in this commit 1af4012df459cf8382b9d184af59161fbe62f192.

As such, I don't believe there is anything else that needs doing for this issue so will mark it as closed. If anyone has any objections please shout.
