### ISSUE TITLE
Question about upgrading

### ISSUE THREAD

**Issue by RonRademaker** [thephpleague/oauth2-server#609]
Hi,

I noticed in the changelogs the new 5.x releaes are a complete rewrite. Are there upgrade docs available for upgrading 4.x to 5.x?

**Comment by alexbilbie** [comment]
I'm afraid not. V5 is a complete rewrite however the interfaces that need
to be implemented are much simpler than V4s.

**Comment by RonRademaker** [comment]
Thanks for the quick reply, will look into upgrading later.
