### ISSUE TITLE
Frameworks without PSR7 such as Laravel

### ISSUE THREAD

**Issue by mhayes14** [thephpleague/oauth2-server#610]
Hi,

How are people working with this library when PSR7 is unavailable, such as with Laravel? I'm trying to implement the middleware now and although Laravel can [inject a PSR7 compatible request for a route or controller](https://laravel.com/docs/5.1/requests#psr7-requests), it won't do this for middleware.

Is there a reason we can't have, for example, a standalone verification method on the BearerTokenValidator class for flexibility? I don't really want to maintain my own copy of such a class.

Any advice is much appreciated, implementing an OAuth server can be such a headache!!

Thanks

Edit: I've come to the conclusion I can either 1) build my own PSR7 `ServerRequest` object from Laravel's Request object and pass this into `BearerTokenValidator`'s `validateAuthorization` method or 2) just create my own implementation of `AuthorizationValidatorInterface` compatible with Laravel's Request object. It would be nice to hear thoughts on having a method on `BearerTokenValidator` which allows us to simply pass in the required data (seemingly just the headers array or even the "authorization" header string alone) and return the interesting data as an array. I support PSR7 but it's a bit tricky when your framework doesn't support PSR7 properly. Any thoughts/suggestions/feedback still appreciated.

**Comment by alexbilbie** [comment]
In the short term for the few Symfony/Laravel projects I've worked on I've made custom `AuthorizationValidatorInterface` implementations to support non-PSR7 requests and responses.

The long term solution to this is probably adopting some sort of adapter system that can support both PSR-7 and Symfony HTTP objects.

**Comment by lucadegasperi** [comment]
There's already an adapter that works with Symfony objects and Laravel. You can check this section of the Laravel documentation on how to use it:
https://www.laravel.com/docs/5.2/requests#psr7-requests
as well as the more detailed version on the Symfony blog:
http://symfony.com/blog/psr-7-support-in-symfony-is-here

**Comment by mhayes14** [comment]
> http://symfony.com/blog/psr-7-support-in-symfony-is-here

Thanks, `DiactorosFactory` is what I was looking for. However converting requests back and fourth seems a bit unnecessary, I'll probably go with the custom `AuthorizationValidatorInterface` implementation.

> The long term solution to this is probably adopting some sort of adapter system that can support both PSR-7 and Symfony HTTP objects.

This sounds good.

**Comment by mhayes14** [comment]
I'll close this because I've had an answer from the man himself. Comments still welcome.

Also, thanks for an awesome library.
