### ISSUE TITLE
Upgrading to version 5, old tokens

### ISSUE THREAD

**Issue by ChrisTitos** [thephpleague/oauth2-server#612]
As version 5 is a complete rewrite of version 4, I was wondering how access/refresh tokens issued by version 4 are handled?

If they are no longer validated, what would be the best way of "upgrading" the tokens, without requiring al my users to login again?

**Comment by alexbilbie** [comment]
The best way would probably be to implement your own [AuthorizationValidatorInterface](https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationValidators/AuthorizationValidatorInterface.php) based on the existing [BearerTokenValidator](https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationValidators/BearerTokenValidator.php); if the JWT cannot be parsed then assume it's a V4 token and go from there.
