### ISSUE TITLE
Provide default implementations for entities

### ISSUE THREAD

**Issue by pounard** [thephpleague/oauth2-server#619]
I am currently using only default implementations using your traits for the various entities this package provide, but it does make me unhappy, for some reason, I had to write all of them by myself, and this is just useless code that I think most people will actually just write, and write, and rewrite, since default implementations are mostly OK and there is no use implementing them another way if you do a basic usage of them.

Would you be OK for me doing a pull request to provide default implementations within this package?

**Comment by alexbilbie** [comment]
The value of this library is in it's flexibility - I do appreciate what you're saying and previous implementations provided default implementations of entities but the V5 release was all about getting out of the way of developers.

I don't think your implementations are useless code - this library tries to make no-assumptions and your requirements for your entities might change over time.

**Comment by pounard** [comment]
While I do agree, they are basically only value objects, and repositories in my case are the objects where the logic is implemented into. I mean in the end, you already provided 99% of the code with traits, why not giving the user directly the working class ?

Nevertheless I do understand and respect your point of view, thanks for answering.
