### ISSUE TITLE
Are you using software to automatically triage issues ?

### ISSUE THREAD

**Issue by pounard** [thephpleague/oauth2-server#620]
I wrote a few issues on this repository, two of them have been dropped in less than 5 minutes, was it intentional or should I re-open them ?

To support what I state, I attached a screen capture of the issues I opened visible from my public activity.

**Comment by alexbilbie** [comment]
I'm not sure what you're referring to sorry?

Github is [having problems](https://status.github.com) at the moment:

```
July 12, 2016

17:00 BSTWe're investigating delayed updates across the site.
```

**Comment by pounard** [comment]
Yes, exactly what I saw a few minutes after I wrote this. Thanks for answering anyway :)
