### ISSUE TITLE
PasswordGrant/RefreshTokenGrant and exposing oauth_client_id/oauth_user_id for logging

### ISSUE THREAD

**Issue by alexplumb** [thephpleague/oauth2-server#628]
Hi, looking for some feedback/recommendation here on how I should proceed. 

As part of logging requests/responses, I'm trying to capture the oauth_client_id and oauth_user_id to track exactly who (and with which client) is accessing, or trying to access, the API. When someone uses the AuthorizationCodeGrant, getting the client data is simple: just call `$authRequest->getClient()`. When someone is authenticating and I call ResourceServerMiddleware, getting the client and user data is a matter of getting the request attributes that get passed to the callable method.

There doesn't seem to be any equivalent for PasswordGrant or RefreshTokenGrant, however. There's no $authRequest that I can get the data I need from, nor are there attributes passed back when I use the AuthorizationServerMiddleware.  Instead, what I seem to need to do is to read the contents of the response body and then decrypt the refresh token in order to get to its sweet, sweet innards. 

Is there an easier way to do this for these two grant types?

**Comment by pounard** [comment]
For your information, I am susceptible to having the same problem soon, but I am not using the middlewares (I actually can't because I'm working with a Symfony application embedded into a Drupal, yuck) so I had to write my own access checks helpers, following the middlewares code flow. Maybe trying to write your own you may find a way to fetch the decrypted JWT token at some point and get the original data that was set into ?

**Comment by alexplumb** [comment]
I was able to figure out a (relatively) simple way to do this by creating new emitter events for successful client and user authentication. Rather than modifying the built-in grants to emit events for successful authentication, I've set up the repositories to be emitter aware instead.

**Comment by alexbilbie** [comment]
Sorry for my lack of response here - I'm currently on holiday.

@alexplumb your suggestion of using events inside the repositories is a good one. Alternatively you could do this logging in `finalizeScopes` method of the `ScopesRepository`
