### ISSUE TITLE
State param & password grant

### ISSUE THREAD

**Issue by DaanGeurts** [thephpleague/oauth2-server#629]
Hi Alex,

I'm using your library, which is awesome, but I don't get my mind around the state param. If I check all grant types, the only one using the state param upon creating an access token is the AuthCode grant. I'm using password grant, is state param not needed for this?
Thanks in advance,
Daan Geurts

**Comment by alexbilbie** [comment]
Hi Grant,

No the state param is just used in the authorization code and implicit
grants. It is used as an anti-CSRF device.
