### ISSUE TITLE
CryptKey using a different protocol than file://

### ISSUE THREAD

**Issue by frederikbosch** [thephpleague/oauth2-server#631]
My key is using different protocol then `file://`. This is not possible because [`file://` is prepended](https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L40) at this moment. I have no idea why. Maybe because of some openssl function requiring it? So this fails.

```php
$cryptKey = new CryptKey('protocol://host/file/key.key');
```

Moreover, I am sorry to say, [the constructor of CryptKey is horrible](https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L35). All the logic of that class takes place in the constructor. That is not what a constructor is for. A decent CryptKey file with same functionality should look as follows. Too bad it is backward incompatible. I suggest creating a `CryptKeyInterface` so people can come up with their own CryptKey implementations.

```php
final class CryptKey
{
    protected $keyPath;
    protected $passPhrase;

    public function __construct($keyPath, $passPhrase = null)
    {
        if (!file_exists($keyPath) || !is_readable($keyPath)) {
            throw new \LogicException(sprintf('Key path "%s" does not exist or is not readable', $keyPath));
        }

        $this->keyPath = $keyPath;
        $this->passPhrase = $passPhrase;
    }

    public function getKeyPath()
    {
        return $this->keyPath;
    }

    public function getPassPhrase()
    {
        return $this->passPhrase;
    }

    public static function fromString($keyContent) {
        $keyPath = sys_get_temp_dir() . '/' . sha1($keyContent) . '.key';

        if (!file_exists($keyPath) && !touch($keyPath)) {
            // @codeCoverageIgnoreStart
            throw new \RuntimeException('"%s" key file could not be created', $keyPath);
            // @codeCoverageIgnoreEnd
        }

        file_put_contents($keyPath, $keyContent);

        return new self ('file://' . $keyPath);
   }
}

**Comment by alexbilbie** [comment]
The openssl function requires `file://` to be prepended.

There was a recent PR - https://github.com/thephpleague/oauth2-server/pull/625 - that allows you to inject the key directly into the first parameter - perhaps that could help in your situation?

In any case I do agree with you that it has got unwieldy and the upcoming version 6 release can address this.

**Comment by frederikbosch** [comment]
Yeah, I could, but that would mean I would change the CryptKey in an incompatible manner. Would you allow that? As in a revert of a PR + better fix?
