### ISSUE TITLE
Are there any plans on supporting "nonce"?

### ISSUE THREAD

**Issue by klickagent** [thephpleague/oauth2-server#634]
Are there any plans on supporting "nonce" (https://tools.ietf.org/html/draft-ietf-oauth-v2-threatmodel-06) ?

btw: Thanks for your awesome oauth2 component!

**Comment by alexbilbie** [comment]
@klickagent please could you clarify from [the RFC](https://tools.ietf.org/html/rfc6819) where you want nonces to be used?
