### ISSUE TITLE
More visibly call out PSR-7 support requirement

### ISSUE THREAD

**Issue by xiehan** [thephpleague/oauth2-server#640]
Hi there! First off, many thanks for this great library; we've been using it in production for over a year and a half now, and it's worked out really well for us. 😄 

We finally managed to be allotted two sprint cycles to upgrade from V4 to V5, which I'd originally thought was mainly a matter of data model changes (switching from the old *Storage classes to the new *Repository infrastructure, removal of the concept of Sessions, etc.) but was completely thrown for a loop yesterday when I discovered the dependency on PSR-7 compatible Request and Response objects, which isn't mentioned at all in the README nor very clearly called out anywhere on the documentation site.

This is a problem for us because we're using our homegrown [zaphpa](https://github.com/zaphpa/zaphpa) routing library, which isn't PSR-7 compatible. We'd already talked off and on about eventually switching to a more actively-maintained alternative (Slim being one of the top contenders) but hadn't done so because frankly there weren't enough reasons to; this may finally give us the impetus we needed to make the switch (which is a good thing!). All that said, that work is out-of-scope for the time being because we probably couldn't get it done in 2 cycles and that's all the time we were given for these infrastructure changes. 😕 

We're looking into alternatives like Diactoros to act like a shim layer between Zaphpa/our custom code and the oauth2-server library, hoping that we can still figure out a way to get the V4->V5 migration completed in the short-term, but in the meantime, I just wanted to mention that the PSR-7 requirement was a huge surprise, and I think it should be called out more visibly as a requirement in the README and the documentation site. I just want to save someone else the shock/potential derailment of the roadmap that we went through!

**Comment by pounard** [comment]
I had the same surprise as you, but hopefully for me, as opposed to your use case, Symfony does provide a transparent conversion layer using the Sensio extra bundle.

**Comment by Sephster** [comment]
Hi @xiehan - thank you for the feedback. Apologies that this wasn't made explicitly clear in the docs. As we are on version 6 now, I feel the upgrade notes opportunity has passed. However, I think it is important we do capture this somewhere in either the readme or the docs. There are references in the docs stating that you need to pass PSR7 compatible requests and responses such as on the [client credentials grant page](http://oauth2.thephpleague.com/authorization-server/client-credentials-grant/#implementation) but I agree that this could be more front and centre. I will look to add this to the README soon. Thank you

**Comment by Sephster** [comment]
Closing this issue as added a note on PSR-7 to the readme requirements.
