### ISSUE TITLE
Validate token

### ISSUE THREAD

**Issue by nrwiersma** [thephpleague/oauth2-server#641]
Hi,

Was looking for a way to manually validate a token. It seems to only be possible to through a bearer token validator. There are a fair number use cases for this, the main one in my case is allowing consumers to validate a token and its scopes.

As a reference, GitHub does this, the documentation can be found [here](https://developer.github.com/v3/oauth_authorizations/#check-an-authorization).

**Comment by alexbilbie** [comment]
You'll need to implement this manually for now, but V6 will support "token
introspection" which is an RFC that I've been working on.

**Comment by nrwiersma** [comment]
Awesome, great to hear. Thanks.

**Comment by simonhamp** [comment]
@alexbilbie did Introspection make it's way into v6?
