### ISSUE TITLE
How to handle JWT on client side of web apps?

### ISSUE THREAD

**Issue by big12isu** [thephpleague/oauth2-server#644]
I was wondering how we are supposed to store the JWT on our client side. I'd like to store the JWT in a cookie but this can open up vulnerabilities with CSRF? I was wondering what the intention was to handle this issue or if there is anything built into this library to handle CSRF? Or, is this a problem we should tackle on our own?

**Comment by alexbilbie** [comment]
Here are two really good articles that should help you out:

https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage
https://auth0.com/blog/ten-things-you-should-know-about-tokens-and-cookies/
