### ISSUE TITLE
No call of finalizeScopes in ImplicitGrant?

### ISSUE THREAD

**Issue by RyanTheAllmighty** [thephpleague/oauth2-server#650]
Hi there,

Looking at the ImplicitGrant.php file there is no call to finalizeScopes in there. Granted there is no `respondToAccessTokenRequest` method (at least not a used one), so it doesn't have an opportunity to finalize the scopes for implicit grants.

Is this intended or an oversight?

**Comment by alexbilbie** [comment]
It's a mistaken oversight

**Comment by alexbilbie** [comment]
This is fixed now
