### ISSUE TITLE
Help to identify oauth2-server version

### ISSUE THREAD

**Issue by LeonanCarvalho** [thephpleague/oauth2-server#661]
Hi, I'm working to upgrade some legacy repository that uses static lib files to compose, I tried version 2.0 but it doesn't correspond the same file structure:

![image](https://cloud.githubusercontent.com/assets/3593706/18925186/459bf1cc-8589-11e6-8789-e834f1e0c570.png)

The licence header means version 2.0 but it does not correspond any branch here :

```
<?php
 /**
 * OAuth 2.0 Resource Server
 *
 * @package     league/oauth2-server
 * @author      Alex Bilbie <hello@alexbilbie.com>
 * @copyright   Copyright (c) Alex Bilbie
 * @license     http://mit-license.org/
 * @link        https://github.com/thephpleague/oauth2-server
 */
```

![image](https://cloud.githubusercontent.com/assets/3593706/18925229/726ba0d0-8589-11e6-9463-bcf1e3bdd8da.png)

I'm not sure where and how it was gotten, but the files points to here.

Thanks.

**Comment by LeonanCarvalho** [comment]
I realize that version is 4.1.x

To use it through composer is necessary use `"league/oauth2-server": "4.*"`

**Comment by alexbilbie** [comment]
@LeonanCarvalho "OAuth 2.0" is the specification it isn't the library version number

**Comment by LeonanCarvalho** [comment]
Yes, I'm sorry for my misunderstanding.

😳
