### ISSUE TITLE
Is there a way to set custom response type?

### ISSUE THREAD

**Issue by nueko** [thephpleague/oauth2-server#663]

**Comment by alexbilbie** [comment]
Can you describe your requirements?

**Comment by nueko** [comment]
Sorry for that, just looking a way to use this lib with a framework that doesn't support the PSR7.
I have problem with the psr7 Response. have you any idea to use this without PSR7 response?

**Comment by alexbilbie** [comment]
Which HTTP library are you currently using? Symfony? Zend?

**Comment by nueko** [comment]
I use Zend for Request, and Phalcon For Response

**Comment by alexbilbie** [comment]
You need to find a Zend->PSR7 and Phalcon->PSR7 adapter

**Comment by nueko** [comment]
as i told, phalcon doesn't support psr7. but thanks

**Comment by nueko** [comment]
Phalcon
