### ISSUE TITLE
Recommended key length should be at least 2048 bits

### ISSUE THREAD

**Issue by er0k** [thephpleague/oauth2-server#666]
According to the docs [https://oauth2.thephpleague.com/installation/] the recommended key length is 1024 bits. 

1024 bit RSA keys have been considered insecure since ~2010 according to NIST: https://www.keylength.com/en/4/

I think the docs should be updated to recommend at least 2048 bits when generating private/public keys

**Comment by alexbilbie** [comment]
@er0k could you send a PR please?

**Comment by er0k** [comment]
https://github.com/thephpleague/oauth2-server/pull/668

**Comment by alexbilbie** [comment]
Merged. Thanks
