### ISSUE TITLE
Specific exception message when redirect_uri is invalid

### ISSUE THREAD

**Issue by gitomato** [thephpleague/oauth2-server#667]
Hi! I wonder if we can consider a new static method `OAuthServerException::invalidRequestUri()` with a specific message when `redirect_uri` is invalid on lines:
https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AbstractGrant.php#L175
https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AbstractGrant.php#L181

It would help configuring a client.

**Comment by simonhamp** [comment]
Hi @gitomato, apologies for the very late reply to this issue.

I understand where you were coming from, but we're trying to follow the spec as closely as possible, so unfortunately there's no scope for a separate kind of error in this scenario. [According to the spec](https://tools.ietf.org/html/rfc6749#section-5.2), any problems with the client identification should be bundled under `invalid_client` error.

I believe this does make the specific issue of an incorrect `redirect_uri` trickier to detect during development, but that's actually not a bad thing in case of a bad actor trying to impersonate a client application in production.

I'm going to close this issue off for now, but if you have any other questions or suggestions, please don't hesitate to open another ticket. Thanks
