### ISSUE TITLE
OAuthServerException::accessDenied() throws 401 HTTP status code

### ISSUE THREAD

**Issue by pounard** [thephpleague/oauth2-server#676]
OAuthServerException::accessDenied() creates and throw an exception using the 401 HTTP response code, which means for most browsers out there (especially Chrome) that the HTTP Basic Auth failed.

Chrome at least (30% of users) will then prompt the user for a HTTP Basic Auth (login/password).

This is not the awaited behavior, an access denied with a 403 has less meaning, but would allow those browsers to mislead the users.

I looked up in the code, and it seems that this is called only during the authorization workflow, and the authorization code workflow should inform the client it's invalid, but not mislead the browser.

What do you think about this, I am misunderstanding something?

**Comment by alexbilbie** [comment]
In this instance you've highlighted - the user would actually be redirected back to the client with a 302 header - see https://github.com/thephpleague/oauth2-server/blob/master/src/Exception/OAuthServerException.php#L224-L231

**Comment by Shkeats** [comment]
Just a note to say I have seen this behaviour once but I can't reproduce it currently. The browser popped up a basic auth login at the auth server. As I recall it happened during some other misconfiguration of the client or client details.

**Comment by Shkeats** [comment]
Managed to recreate just now, it's happening in my setup if the client id is set incorrectly. The user get's sent to the auth server and you get a basic auth popup and it says: "The site says "OAuth"" both on Chrome and Firefox.

**Comment by alexbilbie** [comment]
In this case then the actual failure is much earlier on because the client ID and redirect URI are incorrect in the query string. Throwing a HTTP authorization dialog is correct behaviour.
