### ISSUE TITLE
Failure without 'scope' in BearerToken

### ISSUE THREAD

**Issue by everflux** [thephpleague/oauth2-server#677]
The 'scope' parameter is optional according to RFC 6749, but the `BearerTokenValidator` fails without a scope in the token due to

```
return $request
                ->withAttribute('oauth_access_token_id', $token->getClaim('jti'))
                ->withAttribute('oauth_client_id', $token->getClaim('aud'))
                ->withAttribute('oauth_user_id', $token->getClaim('sub'))
                ->withAttribute('oauth_scopes', $token->getClaim('scopes'));
```

I assume a possible fix would be to provide a default value

```
->withAttribute('oauth_scopes', $token->getClaim('scopes', [] ));
```

**Comment by alexbilbie** [comment]
Thanks; will look into it

**Comment by Sephster** [comment]
Thanks for this @everflux - I'm working on a fix at the moment to allow devs to set a default scope which I will add here shortly. If no scope is provided and no default scope is present, an exception will be thrown. Thanks for reporting this
