### ISSUE TITLE
AbstractGrant issueAccessToken strange implementation

### ISSUE THREAD

**Issue by PhilippSchaffrath** [thephpleague/oauth2-server#680]
The method `issueAccessToken` in `AbstractGrant` does this:

    $accessToken = $this->accessTokenRepository->getNewToken($client, $scopes, $userIdentifier);

    $accessToken->setClient($client);
    $accessToken->setUserIdentifier($userIdentifier);
    $accessToken->setExpiryDateTime((new \DateTime())->add($accessTokenTTL));

    foreach ($scopes as $scope) {
        $accessToken->addScope($scope);
    }

It seems like `accessTokenRepository->getNewToken` should return a new empty instance of `AccessToken`. But why are we passing `$client`, `$scopes` and `$userIdentifier` to it?

I don't see any good reason for this, so can we remove it?

**Comment by alexbilbie** [comment]
For legacy reasons. It's removed in v6

**Comment by PhilippSchaffrath** [comment]
:+1:
