### ISSUE TITLE
How can I delay token revocation?

### ISSUE THREAD

**Issue by ServiceTo** [thephpleague/oauth2-server#686]
I'm writing a chatty ember-cli front-end app and I'm finding that it's sending multiple requests asynchronously to my Laravel back-end and what's happening is the token is being revoked in the same second as another request comes in so the new token hasn't made it back to the front-end for use yet. This provides an exception on the second request and the user has to log in again.

What is the best way to delay these lines from running in RefreshTokenGrant.php from respondToAccessTokenRequest() (without forking, if possible)

// Expire old tokens
$this->accessTokenRepository->revokeAccessToken($oldRefreshToken['access_token_id']);
$this->refreshTokenRepository->revokeRefreshToken($oldRefreshToken['refresh_token_id']);

Thanks in advance for any advice

**Comment by alexbilbie** [comment]
You're best bet it to probably add logic to the front end to correctly respond to invalid token errors and back-off for a moment until the frontend has got the new access token

**Comment by ServiceTo** [comment]
Argh, okay. Thanks.
