### ISSUE TITLE
V6 roadmap?

### ISSUE THREAD

**Issue by juliangut** [thephpleague/oauth2-server#687]
@alexbilbie do you plan to post a roadmap on V6?, you've been leaving some clues scattered over the issues and have a 6.0.0 milestone but I don't manage to get a grasp on what your plan is

Also an update on what is the current development status, maybe updating 6.0.0-WIP branch which is frozen on Aug 21?

Just a humble request 😄

**Comment by Sephster** [comment]
Closing this as version 6 was released some time ago. Going to take a good hit at the outstanding PR's etc over the Christmas period and will then look to getting something put together for V7.
