### ISSUE TITLE
Help with slim and oauth

### ISSUE THREAD

**Issue by drosendo** [thephpleague/oauth2-server#692]
I have this working like the example.

https://github.com/thephpleague/oauth2-server/blob/master/examples/public/middleware_use.php

I already check the user against a DB (https://github.com/thephpleague/oauth2-server/blob/master/examples/src/Repositories/ClientRepository.php) instead of the array.

My questions are, and please do supply some visual code for me to understand:

1. How do I get the generated token so I can store it on the DB before sending the response

The documentation is not very explicit...

Thanks,
David

**Comment by jorgeGrisolle** [comment]
your grant will call issueAccessToken then this function calls accessTokenRepository->persistNewAccessToken this is the class you need to implement and use to store the token in to your DB

**Comment by alexbilbie** [comment]
Yep, what @jorgeGrisolle said
