### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by yffim** [thephpleague/oauth2-server#696]
Hi,

I'm currently implementing a oauth2 server using your library and I'm just wondering if there is any point in storing the expiry date and scopes of tokens/codes. From what I can see the data is never used by the library. The repositories only checks if the tokens/codes are revoked.

**Comment by alexbilbie** [comment]
You don't have to store the dates however if you do you could use the expiry date as part of a cron job to remove expired tokens
