### ISSUE TITLE
Laravel oauth2-server fresh installation grant password unauthenticated

### ISSUE THREAD

**Issue by Listen-WebDev** [thephpleague/oauth2-server#700]
Hi all,

i have fresh installation of laravel 5.4 with oauth2-server, i need to user password grant type

it works well i obtain my access token but when i try to us this token to query my end points i receive message 

error:Unauthenticated

i have try all tricks but nothing works

any ideas?

**Comment by Listen-WebDev** [comment]
this is what failed

 $psr = $this->server->validateAuthenticatedRequest($psr);

in TokenGuard.php

**Comment by alexbilbie** [comment]
Please can you detail the HTTP request you are making to the authorisation server?

**Comment by Listen-WebDev** [comment]
Hi Alex, here you are

<code>
Endpoint: /api/v1/user
</code>

Bulk query headers

<code>
Accept:application/json
Authorization:Bearer 034a1861ede97e32269cfdda6038c5f2fb812622ad6c5bb99badb65b7b3c17324ae402b3b0dfbfed
</code>

**Comment by Listen-WebDev** [comment]
WTF !!! 

i understand... my access token was wrong, I copy and paste access token in oauth_access_token table. This is wrong! 

I feel stupid!

Thank alex for reply

**Comment by EslamIsmail93** [comment]
passport response The resource owner or authorization server denied the request

**Comment by mtangoo** [comment]
>passport response The resource owner or authorization server denied the request
I would suggest you start with laravel/passport then when you confirm it is indeed this library you then open new issue.
