### ISSUE TITLE
Is redirect URI valdiation not too strict? (URL query string also checked)

### ISSUE THREAD

**Issue by martynbiz** [thephpleague/oauth2-server#701]
The following snippet is in AuthCodeGrant::validateAuthorizationRequest method

```php
$redirectUri = $this->getQueryStringParameter('redirect_uri', $request);
if ($redirectUri !== null) {
    if (
        is_string($client->getRedirectUri())
        && (strcmp($client->getRedirectUri(), $redirectUri) !== 0)
    ) {
        $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
        throw OAuthServerException::invalidClient();
    } elseif (
        is_array($client->getRedirectUri())
        && in_array($redirectUri, $client->getRedirectUri()) === false
    ) {
        $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
        throw OAuthServerException::invalidClient();
    }
}
```

My request fails on the first condition because getRedirectUri() and $redirectUri do not match. Below is the values of each:

```php
var_dump($client->getRedirectUri(), $redirectUri); exit;
// string(26) "http://o-eco.vagrant/login" string(37) "http://o-eco.vagrant/login?var=123" 
```

Does the URL checking have to be so strict here? The URL is identical except for a URL query (?var=123). It just means that I need to overwrite the entire method to ease it up (make them match, and not terminate the process). Any thoughts/ suggestions?

**Comment by alexbilbie** [comment]
Yes it needs to be that strict because there is a risk of redirect hijacks which have bitten Facebook and others multiple times.

If you need to pass custom data back and forth use the `state` param which the auth server will pass the value of back to the client
