### ISSUE TITLE
how to create token basic Bearer , Non JWT

### ISSUE THREAD

**Issue by honarkhah** [thephpleague/oauth2-server#705]
old token 40char i need thats. how to config for NonJWT response?

**Comment by alexbilbie** [comment]
Best to use the old 4.* branch - https://github.com/thephpleague/oauth2-server/releases/tag/4.1.5

**Comment by bauer01** [comment]
Why I should use legacy version 4.* .... there souhld an option to disable built-in jwt....for example when I use some openidconnect built on top of this solution like https://github.com/steverhoades/oauth2-openid-connect-server ;-)

**Comment by Sephster** [comment]
We currently have someone working on a PR to make it easier to implement alternatives to JWT should you wish.

**Comment by mikefrancis** [comment]
@Sephster Hi, do you have the PR to hand? I am guessing it might have gone a bit stale and am interested to see if I can pick it up after discussion over on here https://github.com/laravel/passport/issues/543

**Comment by mabar** [comment]
I would also like to be able pick an alternative. I am currently working on oauth2-server integration for [Nette](https://nette.org) and [Apitte](https://contributte.org/packages/apitte/core.html) frameworks and I want choose [paragonie/paseto](https://github.com/paragonie/paseto) instead of JWT

**Comment by davidvalero** [comment]
Any update about this suggestion? I need to implement a basic token but I'm having problems to do it.

**Comment by DJPretorius** [comment]
@Sephster, Has there been any progress on using non JWT bearer tokens?
