### ISSUE TITLE
Cannot decrypt the refresh token

### ISSUE THREAD

**Issue by lkainers** [thephpleague/oauth2-server#706]
missing function decrypt in
[https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/RefreshTokenGrant.php](url)

**Comment by alexplumb** [comment]
RefreshTokenGrant extends AbstractGrant, which uses the CryptTrait trait. As long as you have CryptTrait, you should be able to decrypt things just fine.

**Comment by lkainers** [comment]
Thank you, the problem was homebrew.

brew install php70 (had OpenSSL problem)
brew install php70 --with-homebrew-curl --with-homebrew-libxml2 --with-homebrew-libxslt --without-legacy-mysql (fixed it)
