### ISSUE TITLE
Get user ID in route [Slim 3]

### ISSUE THREAD

**Issue by fjeddy** [thephpleague/oauth2-server#708]
Hello,

Following the docs rather clearly and i'm a bit confused on how to get the "user id" of the logged in user using the password grant.

`$this->get( '/user/notifications', \Routes\Notifications::class . ':getList' )->add( new ResourceServerMiddleware( $app->getContainer()->get( ResourceServer::class ) ) );`

I use this to only accept valid tokens generated by oAuth as per your documentation, but inside the Route, **how do i determine who exactly is logged** in so i can use the information to display the correct user specific information?

**Comment by fjeddy** [comment]
It's available as 

`
$request->getAttribute( 'oauth_user_id' )
$request->getAttribute( 'oauth_scopes' )
$request->getAttribute( 'oauth_client_id' )
`

and so on. Took me a couple of hours with Googling and testing before i figured this out :( Should be part of the documentation (Unless im completely blind).

**Comment by alexbilbie** [comment]
This is documented here - http://oauth2.thephpleague.com/resource-server/securing-your-api/
