### ISSUE TITLE
Implicit Grant redirection query doubt

### ISSUE THREAD

**Issue by xluccianox** [thephpleague/oauth2-server#714]
Hi, is there any logical explanation about why you use "#" instead of "?" when you build the redirect query?
See:
https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/ImplicitGrant.php#L207
<pre>
$response->setRedirectUri(
                $this->makeRedirectUri(
                    $finalRedirectUri,
                    [
                        'access_token' => (string) $accessToken->convertToJWT($this->privateKey),
                        'token_type'   => 'bearer',
                        'expires_in'   => $accessToken->getExpiryDateTime()->getTimestamp() - (new \DateTime())->getTimestamp(),
                        'state'        => $authorizationRequest->getState(),
                    ],
                   '#'
                )
            );
</pre>

**Comment by alexbilbie** [comment]
The implicit grant redirects with a `#` not a query string in the OAuth specification
