### ISSUE TITLE
Scopes claim typo ?

### ISSUE THREAD

**Issue by kpn13** [thephpleague/oauth2-server#720]
Hi,

According to the [rfc](https://tools.ietf.org/html/rfc6749#section-3.3), shouldn't it be "scope" and not "scopes" in the access token claim ?

Also I think it would be more logical to represent the list of scopes as a white space delimited string ?

Aren't you agree ?

**Comment by alexbilbie** [comment]
I think you're conflating two different issues.

As part of an authorization request the `scope` parameter is singular in this libraries implementation.

The embedded scopes array inside a JWT is of this libraries own design as I don't believe the embedding of scopes inside a JWT has ever been given an official claim.
