### ISSUE TITLE
Sample DB setup?

### ISSUE THREAD

**Issue by delboy1978uk** [thephpleague/oauth2-server#722]
I decided to use this lib and have started implementing the interfaces using Doctrine ORM. 

However, as the documentation states, "each of the repository interfaces describes what sort of data you might want to store not how to store it."

This is all well and good, however I have no idea which relations the db tables should have with each other. There used to be an SQL folder in older versions, but it doesn't match with the interfaces in the latest version. So I'm unsure of foreign keys, column lengths etc.

Can we get a sample SQL again, with a disclaimer that it's just *one* way of doing it? Once I see the relationships, I can tweak my entities to get the correct settings.

**Comment by alexbilbie** [comment]
This library is purposely open ended because there are so many ways you might want to utilise this library so I don't have a sample SQL file to give you I'm afraid.

Token IDs are 40 characters in length.

**Comment by delboy1978uk** [comment]
Thanks very much for the fast reply Alex! :-D

I'm creating an implementation for Bone MVC Framework. 40 characters? Great! It's mainly just the relations between the entities I'm wondering about.  

For instance, a RefreshToken should be a one-to-one with the access token, right?
I'm guessing AuthCode is many-many for scopes, one-one for users, many-one for clients.
And AccessToken many-many for scopes, many-one for users and clients.

Once I get these basic relationships I should be able to plough on ahead! Could you advise?
I haven't set up custom repositories yet, but my entities are here:
https://github.com/delboy1978uk/oauth2-api/tree/master/src/Entity/OAuth

Thanks again
Derek

**Comment by alexbilbie** [comment]
> For instance, a RefreshToken should be a one-to-one with the access token, right?

Yes

> I'm guessing AuthCode is many-many for scopes, one-one for users, many-one for clients.

Yes

> And AccessToken many-many for scopes, many-one for users and clients.

Yes

**Comment by delboy1978uk** [comment]
Ah great, guessed right first time! Thanks so much! :-D
