### ISSUE TITLE
How to integrate a resource server with the oauth-server

### ISSUE THREAD

**Issue by leroy0211** [thephpleague/oauth2-server#725]
How would we integrate a Resource Server with the Oauth2-server? And how will the resource-server validates if the current request is still valid?

For example: 

Some user or machine requests an access token which will be valid for about 1 hour. 
When the user is revoked access to a resource within that hour, how does that resource(-server) checks that?

As it seems that all validation is done with the JWT, I don't know how to check for that. 

Any help would be appreciated

**Comment by dimvic** [comment]
There is an example, look it up:
https://github.com/thephpleague/oauth2-server/blob/master/examples/public/api.php

**Comment by danitome24** [comment]
I don't know how to integrate it with Silex... any help?

**Comment by alexbilbie** [comment]
@leroy0211 please see the documentation here https://oauth2.thephpleague.com

@danitome24 you'll need to covert the PSR http requests into Symfony requests using middleware
