### ISSUE TITLE
Example getAccessToken() method adds scopes twice

### ISSUE THREAD

**Issue by delboy1978uk** [thephpleague/oauth2-server#728]
Whilst implementing the AccessTokenRepositoryInterface I copied the logic in the example here:
https://github.com/thephpleague/oauth2-server/blob/master/examples/src/Repositories/AccessTokenRepository.php#L49-L53 
However Doctrine complained about duplicate rows and threw an error.
Upon debugging, I saw that the scope was being added twice, first by the code in the repository, but secondly in issueAccessToken() in the AbstractGrant class:
```php
        $accessToken = $this->accessTokenRepository->getNewToken($client, $scopes, $userIdentifier);
        $accessToken->setClient($client);
        $accessToken->setUserIdentifier($userIdentifier);
        $accessToken->setExpiryDateTime((new \DateTime())->add($accessTokenTTL));

        foreach ($scopes as $scope) {
            $accessToken->addScope($scope);
        }
```
Should the Repository method just return a new instance of the class then?

**Comment by alexbilbie** [comment]
Sorry for the late response, I'm currently away travelling.

The idea here was that the `getNewToken` method could also add any additional grants into the request that fulfill any necessary backend logic.

It's going to be resolved in v6

**Comment by delboy1978uk** [comment]
Ah right ok, thanks for getting back! Version 6? :-D When can we expect to see that?
