### ISSUE TITLE
Csrf security hole 

### ISSUE THREAD

**Issue by Ekwav** [thephpleague/oauth2-server#730]
Hello, 
I am currently implementing the OAuth2-Server  package into [Userfrosting ](https://github.com/userfrosting/UserFrosting) it is a secure php user management system by Alexander Weissman to use it with my mobile games. I have two routes for one grant (I will take implicit for an example), the first is one that shows the user the requested scopes and asks if he approves, the form is then sent to the second route that I adopted from the example. But what happens, when a client app (maybe a malicious one) requests the second route when the user is logged in? It redirects withing one second with a access token that gives access to anything requested. I want to be able to use the [slim/csrf](https://www.slimframework.com/docs/features/csrf.html) package that ships with Usrefrosting by default, but it does only validate post/get/put/delete requests. The problem is, that your package only accepts GET requests, more specific this function getQueryStringParameter(). 
I need an option to use POST instead of GET to issue a new access token. 
Please advise me if I missed something.

**Comment by alexbilbie** [comment]
Hello,

The situation you described should be mitigated on the basis that if the client directly forwarded the user on to the second route then there would not be the necessary authorisation request serialised and stored in the user's session to complete the request.

Please see the code comments in the implementation example here - https://oauth2.thephpleague.com/authorization-server/implicit-grant/

**Comment by Ekwav** [comment]
Ok, I will store it in the session thanks for the advise :), but in my opinion it would make more sense otherwise.
