### ISSUE TITLE
ImplicitGrant finalizes scopes without user identifier

### ISSUE THREAD

**Issue by bartfeenstra** [thephpleague/oauth2-server#737]
We're using `ImplicitGrant` in our current set-up. It calls `ScopeRepositoryInterface::finalizeScopes()` which was, according to the docblock, designed to allow scopes to be added to or deleted from the list of scopes received through the first argument. Because the user identifier is optional, and `ImplicitGrant` does not provide it, the scopes cannot provide user-level validation, like check if a scope is even available to a user at all.

The design reason for this, if I understand the OAuth2 specification correctly, is that the PHP API is a direct implementation of an OAuth2 authorization server, which does not include the user identifier, since that is an implementation detail specific to the authorization server.

A long-term solution could be to provide a PHP API that implements the conceptual features as documented in the OAuth2 specification, but does not make any assumptions about the specific implementation of the authorization server itself. For example: PSR-7 requests can be converted to API value objects in a separate layer, making it easier to build projects in which this library is used to serve and validate tokens, but where HTTP-level OAuth2 integration is done through another system (we have a JS-based authorization server, for example).

While the previous paragraphs hopefully illustrate the problem and give some background information, they do not contribute to a short-term solution. I noticed that some other grant types have their own ways of retrieving the user the token is for, so adding optional parameters to `GrantTypeInterface` may solve the problem for `ImplicitGrant`, but will likely make DX worse for the other types as they'll look like they accept a new parameter which in truth has no impact on them.

**Comment by e0ipso** [comment]
I am also interested on this.
