### ISSUE TITLE
WWW-Authenticate should only be sent when neccesary

### ISSUE THREAD

**Issue by clarkwinkelmann** [thephpleague/oauth2-server#745]
It looks like it was decided to send the `WWW-Authenticate` header for every `invalid_client` error, probably in the hope to satisfy that "RFC 6749, section 5.2"

https://github.com/thephpleague/oauth2-server/blob/master/src/Exception/OAuthServerException.php#L263

However this is causing some very mysterious behaviour for the other `invalid_client` possible errors.

In particular in Laravel Passport if you misconfigure the redirect URL, you end up with Basic auth login popups firing and no useful error messages https://github.com/laravel/passport/issues/340

I'm unfamiliar with this RFC but I believe the case would be better uncovered than covered like this. Plus it looks like it's not enough #738

By the way you skipped test coverage on that code, so I think we can safely tell it's messy :disappointed:

**Comment by benito103e** [comment]
I think we should verify if request contains Authorization header field : 

```php
if (array_key_exists('HTTP_AUTHORIZATION', $_SERVER) !== false){
   // Add "WWW-Authenticate" response header field
}
```

**Comment by ravanscafi** [comment]
We are suffering with this problem too.

**Comment by benito103e** [comment]
@ravanscafi for my part, I removed manually this unexcpected header on my authorization controller : 

```
catch (OAuthServerException $exception) {
    return  $exception->generateHttpResponse($response)->withoutHeader('WWW-Authenticate');
}
```
