### ISSUE TITLE
convert bearer to current user login?

### ISSUE THREAD

**Issue by wysisoft** [thephpleague/oauth2-server#746]
taking Joomla for example, if I integrate this oauth2 server with Joomla using the authorization code grant, and then in Joomla I have a line of code that asks who the current user is, will the current user be correct (the person that initiated the authorization code grant)? If not do you have any insight on how I could make this happen?

**Comment by wysisoft** [comment]
i see in the UserEntityInterface there is a getIdentifier method, I assume this is stored in the "Aud" field inside the jwt token. I might be good with this.

**Comment by simonhamp** [comment]
@wysisoft how did you get on?

Sharing identifying data is kind of a separate area of concern and not really covered by this library (yet). You probably **shouldn't** rely solely on data stored in a token, as this may change and it's also not super flexible or private - for instance you wouldn't want to be storing any personally identifiable data in a token.

Most APIs have a specific endpoint that you can use once the user has generated a token to fetch some identifying details that you can match up with your local user record. You would typically use this association to determine which user should be logged in.

You should definitely check out the client-side version of this project for writing your client implementation, [OAuth2 Client](https://github.com/thephpleague/oauth2-client/). Many OAuth APIs have some basic concept of retrieving user (aka Resource Owner) data after token retrieval, and `oauth2-client` includes some helpful tools for working with these different methods - making your server support a similar approach could make your client implementation much simpler.

Further, a more generalised standard for retrieving user data that is gaining popularity is [OpenID Connect](http://openid.net/connect/). It's a bit complicated at the moment, but it's worth getting to know. This is something we're currently investigating adding into this package at some point.

**Comment by wysisoft** [comment]
For Wordpress and Drupal yes I think I can use the token and their API to get the user info, but for Joomla I didn't see any API like this. Am I wrong in assuming getIdentifier is stored in the token? I see Microsoft and Google storing some user identifier info in their tokens, was hoping for the same here.

**Comment by simonhamp** [comment]
It's possible that it will be a constant user identifier (probably of the user on the OAuth service), but this depends on your specific implementation. Honestly, you would probably be ok using this if you're in charge of the OAuth server and can be sure that it won't change.

But even if you are running the OAuth server, personally I wouldn't rely on this for a couple of reasons:

1. If you don't sign or validate the signature of access tokens (you should! Google, Microsoft _et al_ definitely are), you could expose your Joomla admin to privilege escalation, e.g. if a 'normal user' were able to modify their token at all, they might be able to replace their ID with that of an administrator giving themselves higher permissions than you'd like. Not ideal.

2. If your OAuth service changes how tokens are generated or the data stored in them for any reason, suddenly your identifying data may be different and the relationship between your OAuth users and your Joomla users might break, possibly resulting in either no one being able to login or, if they can, creating a bunch of new, empty user profiles (and much user and administrator frustration). Again, not ideal.

IMHO, it would be better all round to have a separate and more secure channel for transmitting user data from your OAuth server to your client applications. A separate API endpoint is ideal for this as it keeps the authentication (generating and validating tokens) separate from authorisation (Who is this user? What can they do?).

**Comment by Sephster** [comment]
Apologies if I am missing the gist of this discussion but I just answered a similar question so thought I would respond in kind here if it is of use. Sorry in advance to @wysisoft and @simonhamp if this is not what is being discussed.

If I'm understanding correctly, @wysisoft wants to know if he can tie his bearer token back to a specific user. I believe you can if you store the users ID in the _sub_ claim of the JWT. You can then read this to restrict API access to a given user. Please see the AccessTokenTrait for more information:

https://github.com/thephpleague/oauth2-server/blob/9fc288ce53bbd198ceb7be604ca00dc3910a7d82/src/Entities/Traits/AccessTokenTrait.php#L29-L41

As @simonhamp mentioned, it is imperative that this token is kept secure because anyone in posession of this token would have access to all permitted API end points for this users data as it is for any access token issued by the server. I hope this helps and apologies again if I've not understood correctly.

**Comment by Sephster** [comment]
@wysisoft did this answer your question or do you still have concerns?

**Comment by wysisoft** [comment]
i'll test it in the coming weeks and let you know, I think it will work
