### ISSUE TITLE
Refresh token not getting associated with client or user

### ISSUE THREAD

**Issue by lilliesAndRoses** [thephpleague/oauth2-server#756]
I am trying to refresh the access token and it is failing with the error “Token is not linked to client”.

The source of this error (the code in validateOldRefreshToken) compares client_id in the refresh token against the client id in the request. 
If I check the code of issueRefreshToken in AuthCodeGrant.php, I see that no client id is passed when the token is created. 

How is the above check supposed to work? Am I missing anything?

**Comment by alexbilbie** [comment]
It's hard to see what's wrong here without some more information.

Please can you share your implementation of the `RefreshTokenRepositoryInterface`?

**Comment by lilliesAndRoses** [comment]
This is in the context of drupal 8.3.4, simple_oauth module.

**Comment by simonhamp** [comment]
@lilliesAndRoses as this issue appears to be related to Drupal's simple_oauth library (and also relatively old), I'm going to close it. If you're facing any issues specifically with _this_ library, please feel free to open a new ticket.
