### ISSUE TITLE
A few questions about the security improvements

### ISSUE THREAD

**Issue by Lavoaster** [thephpleague/oauth2-server#757]
I'm quite skeptical of the security improvements this is supposed to bring. In the [audit report](https://wiki.mozilla.org/images/7/77/Oauth2-server-report.pdf), the only thing raised was that was that the RSA key validation was subpar. The code reference, from what I've looked over, appears to only be used to check if you've passed an RSA key to as string to the constructor. The auditor noted that it was going to be mitigated by you dropping encryption in future versions, not by switching encryption methods.

In addition to this, The encryption change is currently implemented in a [backwards incompatible way](https://github.com/thephpleague/oauth2-server/blob/26889abdd3dc04b7b9d633991e807159f6d410f9/src/CryptTrait.php#L105), once the new encryption key is provided, that's it, if the server receives a previously valid access token / refresh token, it's no longer valid because it can't be decrypted. This would be solved by checking the old encryption method after the new one fails. None of this is documented on your [security improvements](https://oauth2.thephpleague.com/v5-security-improvements/) page.

Also your breaking change for `6.0.0` [removes](https://github.com/thephpleague/oauth2-server/blob/315d079033df8f14e18860d9a56ff8f9653eeb22/src/CryptTrait.php) all code that deals with old encryption method, but still expects a private key to be given in the [constructor](https://github.com/thephpleague/oauth2-server/blob/315d079033df8f14e18860d9a56ff8f9653eeb22/src/AuthorizationServer.php#L87), why? **EDIT:** Just realised that this was for JWT signing. Considering you've dropped RSA encryption for "security improvements", you could have changed this to HMAC signing and used the encryption key for signing that as well. (Though you'd still be in the same boat for breaking backwards compatibility)

I'm not saying this is a bad change, but it's poorly documented and anyone following the advice given without looking into it may suddenly find themselves in a situation where they have basically performed a clean reset of their issued tokens.

**Comment by alexbilbie** [comment]
I will give a lengthier reply shortly but that audit is not the only audit
that took place. The other hasn't been released yet.

**Comment by webclaus** [comment]
Will certainly second the point that previously valid tokens are now invalid when providing an encryption key, effectively making it impossible to upgrade a production environment.

Using the previous decryption method as a fallback would ensure backwards compatibility and would be a trivial addition?

**Comment by magnetik** [comment]
I just came across the "v5-security-improvements" page, and I was quite puzzled too. 

The page should state clearly that all previously issued token will be invalid

**Comment by dmelo** [comment]
I also would appreciate if you could provide more details about the encryption key.

What is the encryption key used for? How should the encryption key be stored? On the example https://oauth2.thephpleague.com/v5-security-improvements/ it is hard coded on the parameter, is that the recommendation? Should it be stored separated from the RSA private key?

**Comment by mbrodala** [comment]
@dmelo See https://github.com/thephpleague/oauth2-server/issues/915#issuecomment-399425285 for the explanation of the encryption key. I assume it needs to be stored somewhere safe and injected into your code the same way as the keypair.

**Comment by Sephster** [comment]
Hey all, does anyone still need a response to this? I was not involved with the security upgrades so might find it difficult to find an answer to these questions. In addition, we are now on version 7 of the project so I feel that this questions is fairly out dated. Unless anyone has a strong objection, I will close this issue as I don't feel I can sufficiently answer it and even if I can, I don't believe we would make any changes now.

**Comment by Sephster** [comment]
Thanks @webclaus for the quick response. I will close this issue as I think that this change was made so long ago it probably isn't relevant any more. @Lavoaster if you would like this to be followed up, please add a comment and I can re-open this. Thank you
