### ISSUE TITLE
v6.0.0 returning undocumented 400 Bad Request error

### ISSUE THREAD

**Issue by LouisCAD** [thephpleague/oauth2-server#759]
Hi,
I'm an Android app developer, and after my backend teammates updated from v5.1.4 to v6.0.0, my app got undocumented HTTP 400 errors because it tried to refresh the token with an old token. I know the format changed, but why didn't it returned a 401 error instead to notify the app to login again?

Here's the error that was returned:
`{"error":"invalid_request","message":"The refresh token is invalid.","hint":"Cannot decrypt the refresh token"}`

**Comment by riskis** [comment]
Hi,
I have the same problem when try to refresh a valid token.
The problem is when you try to decrypt the token at decryptInternal function
