### ISSUE TITLE
Blog typo, V5 Security Improvements

### ISSUE THREAD

**Issue by zerkms** [thephpleague/oauth2-server#761]
http://oauth2.thephpleague.com/v5-security-improvements/

> All you need to do is replace the public key that was being passed into the constructor of AuthorizationServer with a 32 >>**bit**<< encryption key.

should be

> All you need to do is replace the public key that was being passed into the constructor of AuthorizationServer with a 32 >>**bytes**<< encryption key.

**Comment by gorantosicdev** [comment]
When we can expected fix for this problem?

**Comment by zerkms** [comment]
Oh, I did not know it's on github pages - I would have sent a PR then :-)
