### ISSUE TITLE
Laravel 5.4 passport not working when my composer updating league/oauth2-server from v5.1.4 to v5.1.5

### ISSUE THREAD

**Issue by chinna-magapu** [thephpleague/oauth2-server#762]
Hi I am implementing a php project with Laravel 5.4 framework. and i am using passport package to provide authentication to the apii's in project and it is working fine.

When i am doing composer update in my dependencies
league/oauth2-server from v5.1.4 is updating to league/oauth2-server from v5.1.5
then suddenly functionality related to passport is not working and throwing errors with 500 status.

while updating composer it is updating the league/oauth2-server from v5.1.4 to v5.1.5

![image_8k](https://user-images.githubusercontent.com/26054120/28167158-4629f40c-67f8-11e7-93bf-85f974f1b475.png)

and after updating composer while accessing the api with login credentials it is throwing the error like below with 500 status

![image_h3](https://user-images.githubusercontent.com/26054120/28167230-7fb39912-67f8-11e7-9300-2df3ce3fe0a1.png)

How can i fix this. please suggest me if any solution.
Thanks in Advance.

**Comment by alexbilbie** [comment]
Please upgrade to laravel/passport 3.0
