### ISSUE TITLE
Authorisation server hosted in apache...

### ISSUE THREAD

**Issue by slavkor** [thephpleague/oauth2-server#763]
HI,
My issue is not directly related to the code implementation of the OAuth2 framework in your library. I have a problem in hosting your example in apache. 
if i start the server through the console it works. But if hosted in apache i get 404. 
Can you help with some advice of how to host your example in apache?

**Comment by alexbilbie** [comment]
You probably need to use mod-rewrite with Apache. I don't use Apache so I can offer tailored advice I'm afraid.
