### ISSUE TITLE
How to opt out of using JWT and asymmetric encryption

### ISSUE THREAD

**Issue by halaei** [thephpleague/oauth2-server#764]
Does this package provide a mechanism to not use asymmetric encryption and JWT?

**Comment by alexbilbie** [comment]
You can't; please can you explain your use case?

**Comment by halaei** [comment]
Not a specific use case really, but some performance considerations. I thought maybe the overhead does not add any specific value to my project.

**Comment by alexbilbie** [comment]
When the performance of this library on a single server becomes a problem
you'll be pleased it's designed to scale horizontally without requiring a
database hit on the resource server.
