### ISSUE TITLE
Oauth2 allow social network login ?

### ISSUE THREAD

**Issue by sinzen** [thephpleague/oauth2-server#767]
Hi,

I have one question about the oauth2..
Is the library allow social network login ?

One more question..
Is the token is stored in the database ?
For each user.. Or it's only done in the clients part.
I try to implement into a slim project..
All of files in is needed I see your example in example folder but don't know what I do first..
Thanks :)

**Comment by alexbilbie** [comment]
`league/oauth2-client` is for social login

The server can store the access token if you want the ability to revoke them before they expire, otherwise yes it's the clients responsibility to store tokens.
