### ISSUE TITLE
Add missing @throws UniqueTokenIdentifierConstraintViolationException

### ISSUE THREAD

**Issue by benito103e** [thephpleague/oauth2-server#769]
Methods persistNewAccessToken() from AccessTokenRepositoryInterface and persistNewAuthCode() from AuthCodeRepositoryInterface attempt to throws an UniqueTokenIdentifierConstraintViolationException in case of unicity violation.

**Comment by benito103e** [comment]
#770

**Comment by alexbilbie** [comment]
Fixed by #770
