### ISSUE TITLE
What's `completeAuthorizationRequest` meant for?

### ISSUE THREAD

**Issue by raulferras** [thephpleague/oauth2-server#775]
In `AuthorizationServer` class there is a public method called `completeAuthorizationRequest`.
I can't find anything in the official documentation about it and Docbloc is not very descriptive about what the verb `complete` actually means.

**Comment by alexbilbie** [comment]
It's used as part of the auth code grant and implicit grant:

https://oauth2.thephpleague.com/authorization-server/auth-code-grant/#implementation

https://oauth2.thephpleague.com/authorization-server/implicit-grant/#implementation
