### ISSUE TITLE
Public/Private Key Permission

### ISSUE THREAD

**Issue by johannesschobel** [thephpleague/oauth2-server#778]
Hey guys, thanks a lot for this wonderful package.
I recently stumbled upon a _problem_ with the latest 6.0.2 build that was released a few hours ago.
When i try to login into my application, I get the following error:

```json
{
   "errors" : "Oops something went wrong.",
   "status_code" : 400,
   "message" : "Key file \"file:\/\/C:\\Path\\To\\My\\Larvel\\Project\\storage\\oauth-private.key\" permissions are not correct, should be 600 or 660 instead of 666", 
   "exception" : "ErrorException",
   "trace" : false
}
```

I saw, that there was a commit that had to do with this error message.
Please note that I am running a Windows System - how can I fix this issue!?

Cheers

**Comment by johannesschobel** [comment]
closed as this is related to laravel/passport

**Comment by LuisMejiaF** [comment]
I know this is closed, but I have the same problem and I'm using Slim. 

I understand permissions are important, but forcing to 600 or 660 still doesn't work for me.

In my company, we use a sandbox in the remote server to test our software, I'm not the owner of the server, I was given a user to be able to read/write the source code in the server, but I cannot control the folders above me.  

For instance, if I assign the permission to be 600 or 660, I get the error **private.key does not exist or is not readable**. As I said, I guess this have to do with the servers setup of my company, but again, it stops me to use freely this library during development.

**Comment by johannesschobel** [comment]
I reopened this issue, as it is - unfortunately - not related to laravel / passport. The problem arises within this library - specifically with this commit 2aca909d203e8a925da8c3a3f16a803683cecf04 .
I realize, **why** the change was introduced, but i think this breaks backwards-compatibility. Especially for developers on Windows machines (yes, we exist!) or users that do not have the permission to change the file permission of the keys!

I think, it would be good to make this behaviour (i.e., the `$keyPermissionsCheck` flag) customizable via a configuration file in order to not break Windows development machines or other scenarios.

What do you think?

**Comment by fuadmuhtaz** [comment]
Just add the webserver user to the group of file. So program can read private.key

[https://www.cyberciti.biz/faq/howto-linux-add-user-to-group/](url)

**Comment by johannesschobel** [comment]
still no solution for Windows Users!

**Comment by alexbilbie** [comment]
I’m going to need your help to debug this as I have no access to a Windows server system. You’ve not specified any details about the version of PHP your using, which Windows you’re using, etc.

Please open a new ticket that clearly expalins the issue for Windows users.
