### ISSUE TITLE
Document the new encryption key requirements

### ISSUE THREAD

**Issue by bartfeenstra** [thephpleague/oauth2-server#780]
Good morning :)

https://github.com/thephpleague/oauth2-server/commit/1af4012df459cf8382b9d184af59161fbe62f192 added support for encryption keys, triggers errors, but doesn't document how those should be used.

By looking at the code I don't get an idea of how this should be used either. The tests just set random strings as keys, and the production code seems to delegate everything to `CryptTrait`, which looks like it should work fine without this encryption key, falling back to private/public key encryption.

Any way, today's minor update of this library broke our build through those deprecation errors, which we'd like to fix. We require `~5.1` for now, and are wondering if this encryption key error can be ignored (suppressed), or if is something that should be fixed. If the latter, we're wondering where to find the documentation that explains why this is a new requirement, and how to use it.

Thank you!

**Comment by Sephster** [comment]
Hi @bartfeenstra - sorry it has taken so long for us to get back to you. You have likely came across the answer to your question by now but in case you haven't, documentation for this change was added [here](https://oauth2.thephpleague.com/v5-security-improvements/).

I think in your case the issue can be ignored but if you are still on the 5.1x branch I would recommend setting the encryption key to improve the security of your server installation. Hope this helps and apologies again for the delayed response.

I will mark this issue as closed but if you have further questions please don't hesitate to get back in touch. Thanks
