### ISSUE TITLE
"oauth-public.key" permissions are not correct, should be 600 or 660 instead of 666

### ISSUE THREAD

**Issue by riskis** [thephpleague/oauth2-server#781]
When I try my code in my WAMP installation this error is always returned and I can't change this file permission. Can you check if is windows or if its localhost? And disable in this case?

Thanks

**Comment by fuadmuhtaz** [comment]
You can try this,
$privateKey = new CryptKey('file://path/to/private.key', null, false);

This problem has been fixed from PR #776

**Comment by riskis** [comment]
Thanks @fuadmuhtaz but I can't disable de check in Laravel Passport plugin.
I changed it in my local vendor package

**Comment by fuadmuhtaz** [comment]
Make sure you use laravel/passport version ^3.0.1

They already fixed it [https://github.com/laravel/passport/pull/454](url)

**Comment by riskis** [comment]
Thanks! Update solve my problem.
I use "laravel/passport": "~4"

**Comment by Sephster** [comment]
Closing issue as bug has been fixed
