### ISSUE TITLE
CryptKey permissions 660 / 600

### ISSUE THREAD

**Issue by aleho** [thephpleague/oauth2-server#783]
I just stumbled upon a a few notices being output regarding "wrong" permissions.

I understand that a security check is a nice thing to have, but why enforce write permissions by default? Why should a key-pair be written in production environments by the web server? What's even more concerning is the fact that once could also use ACLs, which are enforced differently and then fileperms fails horribly (I tried. It detects group read rights when there's in fact a user read ACL entry). 

Also it doesn't account for user / group setup being different entities.

Apart from that, the check is problematic, because it enforces exact rights here, you cant do 0400 or 0640.

**Comment by alexbilbie** [comment]
The check can be disabled https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L34

**Comment by aleho** [comment]
Yes, I was aware of that. This is not about the possibility to disable the check though.

The check itself is harmful in terms of IT security. It doesn't help with securing the key pair, it actually requires the web-process to have write-rights (anything below will result in an error). By default the notice gets output in server responses, so that will lead to people setting access rights exactly as "required" by the notice to make it disappear. Even "correct" setups will lead to such a notice being shown.

Please don't see this as a support request about "I can't make the notice disappear", but consider fixing the broken warning leading to insecure setups.

**Comment by manticorp** [comment]
It's also very difficult/impossible to implement those exact permissions on a Windows machine.

The check should be disabled by default, or pushed to another, specific method, e.g. a static ```CryptKey::checkPermissions($file)``` that can be invoked as needed, not in the constructor for CryptKey.
