### ISSUE TITLE
RefreshTokenGrant - Revoking old tokens doesn't respect foreign keys.

### ISSUE THREAD

**Issue by LuisMejiaF** [thephpleague/oauth2-server#785]
I have my own MySQL Scheme to persist tokens. Two of the tables, are the ones that store the accessTokens and the refreshTokens.

Correct me if I'm wrong, but I think the relationship between both tables should be:
**accessToken** --has-one-> **refreshToken**
-- OR --
**refreshToken** --belongs-to-> **accessToken** 

That means that the accessToken record should be deleted before the refreshToken, right?
The problem is, that the `RefreshTokenGrant` class, [tries to delete](https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/RefreshTokenGrant.php#L73) the accessToken first, throwing a `Integrity constraint violation: 1451 Cannot delete or update a parent row`.

The current code is this:
```php
// Expire old tokens
$this->accessTokenRepository->revokeAccessToken($oldRefreshToken['access_token_id']);
$this->refreshTokenRepository->revokeRefreshToken($oldRefreshToken['refresh_token_id']);
```
But should be:
```php
// Expire old tokens
$this->refreshTokenRepository->revokeRefreshToken($oldRefreshToken['refresh_token_id']);
$this->accessTokenRepository->revokeAccessToken($oldRefreshToken['access_token_id']);
```

**Comment by sgomez** [comment]
You can configure your schema to do an 'ON DELETE CASCADE' or 'ON DELETE SET NULL'.

**Comment by alexbilbie** [comment]
When a new access token is issued a new refresh token is issued.

When an access token expires the corresponding refresh token won't expire (at least not immediately).

When a refresh token is exchanged for an access token, the refresh token used as well as it's corresponding access token are expired, and a new access token and refresh token are issued.

I hope that helps.
