### ISSUE TITLE
Implicit grant not adhering to the docs

### ISSUE THREAD

**Issue by christiaangoossens** [thephpleague/oauth2-server#786]
According to https://oauth2.thephpleague.com/scope-repository-interface/, the **finalizeScopes()** method should be called right before an access token is created (and thus after the user has been logged in, and the user identifier has been set, it could for instance be called when calling: `completeAuthorizationRequest()`). In all scopes, except the Implicit Grant, this is also the case, with the **finalizeScopes()** method being called upon token retrieval, and thus after all user interaction has happened.

For the implicit grant however, the **finalizeScopes()** method is being called in the `validateAuthorizationRequest()` method, where I would expect it to be called right before the access token creation (and not upon initial request) in the `completeAuthorizationRequest()` method, right before the `issueAccessToken()` method. The useridentifier could then also be passed in.

Also, why is the **issueAccessToken()** method overwriting the client, useridentifier and scopes on the created accessToken?

**Comment by christiaangoossens** [comment]
Related to #737

**Comment by christiaangoossens** [comment]
Resulted in PR #923.

**Comment by Sephster** [comment]
Closing issue as now fixed as part of PR #923
