### ISSUE TITLE
oauth2-client not working with oauth2-server

### ISSUE THREAD

**Issue by bchris999** [thephpleague/oauth2-server#791]
I am trying to get the thephpleague/oauth2-client working with oauth2-server.

On the client side, my Provider is extending `League\OAuth2\Client\Provider\AbstractProvider`.
I have implemented the getResourceOwnerDetailsUrl method as follows:
```
public function getResourceOwnerDetailsUrl(AccessToken $token): string {
        return self::BASE_URL.'auth'.'/get_owner'.'?access_token='.$token->getToken();
    }
```
When i then call `$provider-getResourceOwner($access_token)`, I get an error that the Authorization header is missing.

It looks like the ability to define an access token in a parameter of a GET request has been removed from the oauth2-server, but this seems to be required for this oauth2-client.

How do I correctly implement the server side of the getResourceOwner in oauth2-server? The documentation has no mention of this, even though it seems to be an integral part of the client.

Thanks.

**Comment by alexbilbie** [comment]
You need to modify your provider to send an Authorization code header not the access token in the query string. Please open an issue with thephpleague/oauth2-client.
