### ISSUE TITLE
Issued time claim validation is not tolerant of timing drift

### ISSUE THREAD

**Issue by soundsgoodsofar** [thephpleague/oauth2-server#798]
We had very difficult to diagnose problems with valid oauth tokens being rejected immediately after being issued, and we tracked it down to a claims enforcement issue.

It turns out that `iat` and `nbf` timestamps are being set in `AccessTokenTrait` to now().  Then in `BearerTokenValidator` a ValidationData object is created, also with time now().

The problem is when these oauth tokens can be generated on different servers.  We have a pool of backend servers and, like most real world environments, their system times are susceptible to drift, even when using NTP.  A second or even fractional second of drift is occasionally enough to have one server issue an oauth token with a timestamp that fails to validate if the token is immediately used by the client and a different server is hit.

Personally I don't see any real value in using these and would prefer to drop them since all they really do right now is cause potential errors.  The "not valid before" timestamp is hardcoded, so users can't use it to issue future tokens even if they wanted to.

The only other option would be to add some arbitrary amount of wiggle-room to the values either on setting or validating, but then you're picking an arbitrary amount of allowable drift which may not be reasonable in different environments.

**Comment by sergeyklay** [comment]
I propose to consider such a scenario:

1. User should explicitly set a timezone, this is not a responsibility oauth2-server
2. The oauth2-server should use `DateTime` and `DateTimeZone` objects instead of `time()` function

```php
interface DateTimeAwareInterface {
    public function getTimestamp(): int;

    public function getDateTime(string $format = 'Y-m-d H:i:s'): string;
}

trait DateTimeAwareTrait {
    protected $dateTime;

    public function __construct(DateTimeZone $timezone = null) {
        $this->dateTime = new DateTime('now', $timezone);
    }

    public function getTimestamp(): int {
        return $this->dateTime->getTimestamp();
    }

    public function getDateTime(string $format = 'Y-m-d H:i:s'): string {
        return $this->dateTime->format($format);
    }
}


$dc1 = new class(new DateTimeZone("Europe/London")) implements DateTimeAwareInterface {
    use DateTimeAwareTrait;
};

$dc2 = new class(new DateTimeZone("UTC")) implements DateTimeAwareinterface {
    use DateTimeAwareTrait;
};

var_dump(
    [
        $dc1->getDateTime() => $dc1->getTimestamp(),
        $dc2->getDateTime() => $dc2->getTimestamp()
    ]
);
```

```
array(2) {
  '2017-10-25 09:25:59' =>
  int(1508919959)
  '2017-10-25 08:25:59' =>
  int(1508919959)
}
```

**Comment by soundsgoodsofar** [comment]
That would be fine but it doesn't address the issue at hand.  Those DateTime objects are still reliant on system time.  System time can, and in real world does, drift between servers.

So the problem with this approach is:
1. User requests token from Server A.
2. Server A returns a token with iat timestamp 100000
3. 200ms later, user tries to use token in API call which gets sent to Server B
4. Server B's system time is 2 seconds behind Server A
5. Server B thinks that oauth token is from the future and rejects it

There's really very little use case for having oauth tokens with precise-to-the-second verification.  If anything, there should be a tolerance on verification for 60 seconds or so to make sure that some drift is tolerated.  At a minimum, this definitely shouldn't be precise to the exact second.

**Comment by sergeyklay** [comment]
Got it. Do you suggest to introduce something like **`setExpirationPrecision()`**?

**Comment by soundsgoodsofar** [comment]
My suggestion would be to modify AccessTokenTrait::convertToJWT and change these two lines:
```
            ->setIssuedAt(time())
            ->setNotBefore(time())
```
to:
```
            ->setIssuedAt(time() - 120)
            ->setNotBefore(time() - 120)
```

That would make these tokens issued timestamps 2 minutes in the past, which should be plenty to deal with normal drift, and not have any likely impact on usage.  If you wanted to make that a configurable property in case someone wants to modify that time that would make sense.  But I think the default case should definitely be to add a reasonable amount of buffer time.

**Comment by sergeyklay** [comment]
But not all auth system need to use drift. Also `120` looks a bit magic. This is why I asked about a separated method to enable drift and disable (set to 0).

**Comment by soundsgoodsofar** [comment]
Well drift isn't something anyone wants.  But it's something that will affect any product that scales to the point of needing more than one server.  You really don't want your default configuration to be something that works in a single-server environment, but breaks when you move to multi-server.

I would also say that portability is really the point of oauth.  So a library that is not tolerant of normal issues with distributed networks seems problematic.

To your point, yes 120 is magic, but it's normal magic.  Your browser has a magic number of seconds after which it will timeout a network connection.  Magic timing thresholds exist throughout asynchronous systems, and if you want to enforce a timing constraint on an oauth token, you have to pick some amount of acceptable drift in time between systems.  Currently the acceptable drift amount chosen is zero (which is also a magic number) and I'm just pointing out that that is a bad magic number.

My personal opinion would be to just remove this check entirely, which is what I've done in my own fork.  It really doesn't add anything in terms of security.  But if you _really_ want to keep it, the only option is to add some amount of timing tolerance that seems reasonable.  I can submit a patch for the former case if the repo owners like.

**Comment by alexbilbie** [comment]
I’ve thought about this for a while and I’ve come to the conclusion that removing `nbf` and keeping `iat` is the best solution.

I’ve had situations whereby I’ve needed to perform custom logic on tokens issued before or after a certain time so `iat`is useful to have.

Removing `nbf` will fix the described issues about drift.

**Comment by soundsgoodsofar** [comment]
I don't actually believe that would help.  NBF and IAT are being set and checked the exact same way right now.  If you want to keep one or both of them it should be fine, but you still need to add a bit of tolerance to the validation method.

IMO just leave them both set as they are now and add at least 5 seconds up to 120 seconds of tolerance on the check.

Another option would be to just expose the ValidationData object as configurable and let people decide.  I would still argue that the sensible default should be something tolerant of distributed timing drift, but at least making it fixable without forking the project would be great.

**Comment by soundsgoodsofar** [comment]
This bit us again in production today and I just want to bump this again as extremely important in real-world scenarios.

There's an open issue on the upstream lcobucci package for this problem as well.  Seeing it addressed in either place would be great.

https://github.com/lcobucci/jwt/issues/191

**Comment by RubenKruiswijk** [comment]
> This bit us again in production today and I just want to bump this again as extremely important in real-world scenarios.

This happened to us as well this week. Are there any plans to address this here or reopen https://github.com/thephpleague/oauth2-server/pull/1017?

**Comment by Sephster** [comment]
Yes this is planned for a future major release. Listed as issue #1021

**Comment by Sephster** [comment]
Closing this issue to track in #1021
