### ISSUE TITLE
RefreshGrant Need to bypass REFRESH_TOKEN_CLIENT_FAILED exception

### ISSUE THREAD

**Issue by alterphp** [thephpleague/oauth2-server#815]
https://github.com/thephpleague/oauth2-server/blob/5f4ec6a154f27c11adbb4279888338c75e3b9f14/src/Grant/RefreshTokenGrant.php#L100

Hi, 

I'd like to bypass the `throw OAuthServerException::invalidRefreshToken('Token is not linked to client');` for some clients. Indeed, I share a cookie that holds access and refresh tokens between many subdomains, but each subdomain is known as one client. So that access token from another client (subdomain) may be used to authenticate on another client (subdomain). 
I want refresh process follow the same behavior => clients may be differents, but, if they are from the server domain, refreshing with a refresh token from another client is allowed).

Or what can I do to achieve that ? Why emitting an event at this time if it can not modify following behavior ?

**Comment by Sephster** [comment]
This isn't something we would recommend as it could compromise the security of your server. Do all of your subdomains have the same client ID? If not, is this something you could achieve? I am assuming your subdomains don't have the same client ID at the moment so if it is possible to change this, that would be the easiest option.

**Comment by alterphp** [comment]
Ok, I understand I have to share the same client across subdomains (as I want to share authentication between them). For now, my trusted apps (subdomains) have their single own client ID so that I have to split those two layers.

Thanks for advice.

One last question, what kind of action do you expect to be achieved on REFRESH_TOKEN_CLIENT_FAILED event (in order to explain why this case emit an event and not other cases) ?

**Comment by alexbilbie** [comment]
As @Sephster suggested either have a shared client ID or subclass the RefreshTokenGrant class and override the problem method to suit your usecase.

The emitted event can be used for auditing purposes (which might result in blocking bad clients/tokens/etc)
