### ISSUE TITLE
Error at Create Token and client

### ISSUE THREAD

**Issue by marslanniaz** [thephpleague/oauth2-server#816]
I have installed passport in my laravel project 4-5 days ago. Now I am trying to create token but is showing this error.  
![error](https://user-images.githubusercontent.com/30683178/33060275-896c8c20-ceb9-11e7-857e-69b56b51ca36.PNG)

I have refreshed the migration, run the passport:install and passport:keys command but noting is working.
![create client](https://user-images.githubusercontent.com/30683178/33060404-eb86da14-ceb9-11e7-9678-37e59f649f3a.PNG)

The same issue is with create client.

**Comment by Sephster** [comment]
Hi @marslanniaz, as this is related to Passport, it would be better to [log an issue](https://github.com/laravel/passport/) there so the Laravel Passport devs can investigate. If this does turn out to be an issue with the OAuth2 server, please feel free to link us to the issue so we can investigate further. Good luck!
