### ISSUE TITLE
How to use scopes?

### ISSUE THREAD

**Issue by enesyurtlu** [thephpleague/oauth2-server#826]
Hi all,
This is not an issue. I can't get scope values. How can I get and use them? I tried $request->getAttribute("oath_scope") and $ScopeEntity->getIdentifier() but it returns null.
I want to make role based routes. Anyone knows how to ?

**Comment by Sephster** [comment]
Hi @enesyurtlu. If you look in the [examples readme](https://github.com/thephpleague/oauth2-server/tree/master/examples), you can see that we are requesting the scopes of `basic` and `email` which should be set on the access token returned if everything is ok. Are you requesting scopes with your auth request?

To take the client credentials grant as an example, if you look at the function `respondToAccessTokenRequest()`, you will see that we retrieve the scopes from the auth request by calling this:

`$this->getRequestParameter('scope', $request, $this->defaultScope)`

which eventually calls the `getParsedBody()` function to retrieve the parameter of `scope` that was passed with the request as shown below:

```
protected function getRequestParameter($parameter, ServerRequestInterface $request, $default = null)
    {
        $requestParameters = (array) $request->getParsedBody();

        return isset($requestParameters[$parameter]) ? $requestParameters[$parameter] : $default;
    }
```

The methods mentioned above should get you looking in the right places. Hope this helps you but if you have any further questions give us a shout. Cheers

**Comment by enesyurtlu** [comment]
I read examples and docs so many times. But I couldn't understand how I can pass scopes to my controller or routes section to make role based auth. I want to make scope check in the backend, not while sending authorization requests. And I wanted to store my admin users in another table. But I couldn't.

**Comment by Sephster** [comment]
Which grant are you working with?

**Comment by enesyurtlu** [comment]
I added something extra.
> I have 2 different routes. One for Admins and one for normal users. I want to secure both of them.

I am using password grant for my admin panel that is made with angular 5. And I don't know which grant to use for website (users section).

Admin can edit anything add, edit, delete.
Users can be add playlists, edit them and delete them. And change their profile settings, infos.

**Comment by enesyurtlu** [comment]
Want to add something I can send scopes with auth req, and server checks. But I am trying to check scopes while user trying to access a route.

**Comment by Sephster** [comment]
Ah I see. When you send an access token to your resource server, it should be validated using the function `validateAuthenticatedRequest()`.

This function checks if the access token has expired or been revoked. It is hadn't, it parses the JWT, and returns the original server request with the scopes, user ID, client ID, access token ID attached. Once you have this, you can query the server request to get the original scopes and deal with them how you want.

See the implementation of the [BearerTokenValidator](https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationValidators/BearerTokenValidator.php) for more details.

**Comment by Sephster** [comment]
Did this help @enesyurtlu?

**Comment by enesyurtlu** [comment]
Yes, I am sorry for being late to write. But I tried just now. Thank you so much.

**Comment by enesyurtlu** [comment]
My mistake was trying to get "getAttribute('auth_scope')". Now it works with "getAttribute('auth_scopes')" :)

**Comment by Sephster** [comment]
Awesome. Glad you got going again! Hope everything else goes ok
