### ISSUE TITLE
Writing key to file even if it exists

### ISSUE THREAD

**Issue by kpn13** [thephpleague/oauth2-server#833]
Hi,

In the saveKeyToFile method form the CryptKey class, the key is always wrote into the temporary key file even if it is unchanged.

https://github.com/thephpleague/oauth2-server/blob/57ca83a8baadd5b5a6c1d82da7d261089e55585c/src/CryptKey.php#L71-L86

Would it not be better if we skip the file_put_contents() if the file already exists for performances improvement ? Because it file exists before the "touch()" function call, it means the key is the same.

Am I wrong ?

Best regards.

**Comment by alexbilbie** [comment]
Valid point 👍

**Comment by Sephster** [comment]
Merged PR in as of commit 3999c41
