### ISSUE TITLE
CryptKey constructor won't accept strings with windows based line endings as a valid key

### ISSUE THREAD

**Issue by tdondich** [thephpleague/oauth2-server#835]
When passing in a string to CryptKey constructor which contains contents of a key file (instead of a path), CryptKey will fail stating Key path file://<contents of string> does not exist or is not readable

This is because if the file has dos line endings, the preg_match will not match correctly.

Replacing CryptKey::RSA_KEY_PATTERN from
```
/^(-----BEGIN (RSA )?(PUBLIC|PRIVATE) KEY-----\n)(.|\n)+(-----END (RSA )?(PUBLIC|PRIVATE) KEY-----)$/
```
to

```
/^(-----BEGIN (RSA )?(PUBLIC|PRIVATE) KEY-----[\r\n])(.|\n)+(-----END (RSA )?(PUBLIC|PRIVATE) KEY-----)[\r\n]$/
```

Will properly match both unix and dos line endings when matching for a proper key pattern.

**Comment by Sephster** [comment]
Hi @tdondich - thanks for raising this. We've had a PR submitted to fix this issue which is currently uner review. It is PR #805. I will close this issue for now as it is best to track in the raised PR. I've contacted the author of the PR to see if he has time to address the comments raised. Thanks for notifying us about this
