### ISSUE TITLE
implode(self::SCOPE_DELIMITER_STRING, $oldRefreshToken['scopes']))

### ISSUE THREAD

**Issue by samiboukadida** [thephpleague/oauth2-server#838]
Class League\OAuth2\Server\Grant\RefreshTokenGrant:
line 50;

$oldRefreshToken['scopes'] is not an array

**Comment by samiboukadida** [comment]
i have to add this line (before line 50)
$oldRefreshTokenScopes = explode(' ', $oldRefreshToken['scopes']);

perhaps i do make a mistake in using this package, could you confirm me. Thanks.

**Comment by tominek** [comment]
Hello can you please describe the issue more? Maybe include whole method. I am currently struggling on the same part of the code: 

**RefreshTokenGrant:55**
```
if (in_array($scope->getIdentifier(), $oldRefreshToken['scopes']) === false) {
    throw OAuthServerException::invalidScope($scope->getIdentifier());
}
```
My issue is that scope identifier `'basic'` is being searched in array of arrays
```
array(2) {
  [0]=>
  array(2) {
    ["id"]=>
    string(5) "basic"
    ["description"]=>
    string(23) "Basic details about you"
  }
  [1]=>
  array(2) {
    ["id"]=>
    string(5) "email"
    ["description"]=>
    string(18) "Your email address"
  }
}
```

Maybe we are dealing with the same issue.

**Comment by Sephster** [comment]
Thanks for reporting this guys. I will aim to take a closer look at this on Tuesday evening. Apologies for any inconvenience caused.

**Comment by tominek** [comment]
Hello @Sephster , so I have investigated more and found the issue. I implemented jsonSerialize() method in Scope entity like this:
```
public function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'description' => $this->description
        ];
    }
```
as I wanted to also use description for the scope, but I have not realized that it would not work within the scope comparison in RefreshTokenGrant class.

So leaving the method like in the example code works, kinda my bad, but it is not very intuitive.
```
public function jsonSerialize()
    {
        return $this->id;
    }
```
So my issue is solved, lets wait for @samiboukadida :-)

**Comment by Sephster** [comment]
Thanks for clarifying @tominek and glad you solved your issue. @samiboukadida, could you confirm what is being pass in `$oldRefreshToken['scopes'] ` if it is not an array? Many thanks

**Comment by Sephster** [comment]
As an aside @tominek - we are currently looking at alternative methods to surface Scope IDs so we don't rely on `jsonSerialize` as it is too easy to make mistakes with implementation. @samiboukadida, because this issue has sat idle for a few months, I'm going to close it, but if you do have further information, please get back in touch and we can look at this further. Many thanks
