### ISSUE TITLE
Learning oauth2-server more detail

### ISSUE THREAD

**Issue by amidia** [thephpleague/oauth2-server#841]
Hi All,
i just learn about oauth2 and stuff. 
and now i want to try to implement oauth2-server for my project.
and i want to code the right way using this library by theleague.
is there any github project using this oauth2-server so i can learn from. 
i really want to learn and understanding this particular library, but it seem i got lost the flow.
i have not implement the persistent repository yet.
i try client_credential grant, i can get token reply from the route.
but that's it.
i have not successfully secure my api endpoint.
please can anyone guide me how to use this library 
or at least point me to the right way. or some tutorial (more detail than oauth2.thephpleague.com) 
i'm sorry if my question is trivial.
thanks

**Comment by Sephster** [comment]
Hi @amidia. Thanks for taking an interest in the server. Have you had a look at the [examples ](https://github.com/thephpleague/oauth2-server/tree/master/examples)provided in this repository? They serve as a good starting point for seeing how an implementation might be accomplished so I would recommend have a look through them to get you going.

**Comment by amidia** [comment]
hi @Sephster yes i have. not all the grant thou. i successfully tried client_credentials and password grants. but still can't make a head or tail of it. maybe i'll try with another frameworks to learn and hopely with the time i can absorbs the idea behind it.
thanks anyway.

**Comment by Sephster** [comment]
If you have a specific grant you are struggling to implement, please let me know and I will be happy to try and guide you through the process.

**Comment by alexbilbie** [comment]
@amidia take a look at https://alexbilbie.com/guide-to-oauth-2-grants/ it might help
