### ISSUE TITLE
Incomplete interfaces?

### ISSUE THREAD

**Issue by delboy1978uk** [thephpleague/oauth2-server#843]
Quick question:
I'm going through the examples and currently looking at the client repository.

```
        $clients = [
            'myawesomeapp' => [
                'secret'          => password_hash('abc123', PASSWORD_BCRYPT),
                'name'            => 'My Awesome App',
                'redirect_uri'    => 'http://foo/bar',
                'is_confidential' => true,
            ],
        ];
```
In my case I'm fetching via Doctrine, but anyway. I implemented the ClientEntityInterface for my Client Entity, but the interface only mentions name and redirect URI.

Obviously a client should have a secret, so I have added that to my entity, but shouldn't this be defined in the interface? It's needed!

Also, what is `is_confidential`? Is this also required? And when would it be false?

**Comment by delboy1978uk** [comment]
Ok, I've had a look again at the specs here https://www.oauth.com/oauth2-servers/definitions/ so now I understand. But again, shouldn't these be in the interface?

**Comment by alexbilbie** [comment]
Not all implementations of grants have clients that have either a secret or are confidential.

The interfaces are kept purposely small to reduce conflict with implementation entities (such as Doctrine entities).

I hope that helps
