### ISSUE TITLE
Question: where to check token expiration

### ISSUE THREAD

**Issue by jacobweber** [thephpleague/oauth2-server#858]
I'm trying to implement the entities and repositories. It's not clear to me where to check the token's getExpiryDateTime() field, to make sure it hasn't expired. Do I do this in the is*TokenRevoked() methods?

**Comment by Sephster** [comment]
Hello @jacobweber - The _tokenEntityInterface_ and _refreshTokenEntityInterface_ both require `getExpiryDateTime()` methods to be implemented.

This function is called by the server to retrieve the expiry date for an access token to package up and send back to the client in an http response. As long as you have implemented the function, the package should use the function correctly.

For example, the _BearerTokenResponse_ uses this method when generating an HTTP resonse:

https://github.com/thephpleague/oauth2-server/blob/28e1418f64a114a066eda23c5846353f30399aaf/src/ResponseTypes/BearerTokenResponse.php#L25-L32

The _Implicit Grant_ also uses it for its redirect response:

https://github.com/thephpleague/oauth2-server/blob/28e1418f64a114a066eda23c5846353f30399aaf/src/Grant/ImplicitGrant.php#L210-L224

As long as you implement the function correctly in any entities that require it, you should be good to go. 

The package provides some traits which make this a bit easier for you as they have ready made implementations of these functions should you so wish such as in the _TokenEntityTrait_:

https://github.com/thephpleague/oauth2-server/blob/28e1418f64a114a066eda23c5846353f30399aaf/src/Entities/Traits/TokenEntityTrait.php#L57-L65

When the package receives an access token, it is passed to a validator. By default, this will be the _Bearer Token Validator_ in the form of a JWT. The JWT will be parsed, and the data within it is validated against validation data passed to the validate function. In our case, we just pass the current date time to validate against:

https://github.com/thephpleague/oauth2-server/blob/28e1418f64a114a066eda23c5846353f30399aaf/src/AuthorizationValidators/BearerTokenValidator.php#L67-L78

If you need any further assistance the implementation in the examples is a good place to look. I hope this helps. Cheers

**Comment by jacobweber** [comment]
Thanks! That's very helpful. I didn't realize that it's embedding the expiration time in the token now, using JWT. I was used to the older version where I had to store the expiration time in the database and verify it myself.
