### ISSUE TITLE
getClientEntity doesn't include client secret

### ISSUE THREAD

**Issue by suhaboncukcu** [thephpleague/oauth2-server#859]
I'm trying to implement AuthGrant and having a problem about Client Authentication. 

However I can't get any secret within getclientEntity function. 

I also realized that when validating authorization request the secret is sent as `null` 

`AuthCodeGrant.php` line 216:
```
$client = $this->clientRepository->getClientEntity(
            $clientId,
            $this->getIdentifier(),
            null,
            false
        );
```

When I sniff the request I can see the header sent as `authorization:"Basic base64(client:secret)"`

How can I validate the client secret?

**Comment by Sephster** [comment]
Hi @suhaboncukcu. The function `getClientEntity()` accepts four arguments:

* clientIdentifier
* grantType
* clientSecret
* mustValidateSecret

It is up to you where you store your actual clients information. If they are stored in a DB, you must retrieve the clients from the DB and then compare their hashed client password stored in the database against the client secret you have been provided in the arguments list.

A very simplistic example of this is shown in the examples of this library:

https://github.com/thephpleague/oauth2-server/blob/b8b92e59255ffe586ddd50a3975d7219ca9a8c38/examples/src/Repositories/ClientRepository.php#L22-L42

In the example, we've just created an example client directly in the code but in a production system we would retrieve this from some data store.

I hope this has helped but if you have any further questions please let me know. Cheers and good luck!

**Comment by suhaboncukcu** [comment]
@Sephster Thank you for your kind response. But it got me confused. 

I've already implemented my client repository implementing the interface as below: 

```
public function getClientEntity($clientIdentifier, $grantType, $clientSecret = null, $mustValidateSecret = true)
{
    $className = Configure::read('Oauth2Server.classes.clientValidator');
    $clientValidator = new $className();
    $clientValidator->validate($clientIdentifier, $grantType, $clientSecret);

    return new ClientEntity();
}
```

I plan to handle non-authorized request within the validate function. I have my client stored safely on my database and I can get its id and secret without a problem. However, whenever I try to get `$clientSecret` from this function; I get null. 

So for me; 
`password_verify($clientSecret, $clients[$clientIdentifier]['secret'])` gives false each time because `$clientSecret` param is always `null`. 

Should I overwrite the `AuthCodeGrant.php` to retrieve `$clientSecret` ?

https://github.com/thephpleague/oauth2-server/blob/b8b92e59255ffe586ddd50a3975d7219ca9a8c38/src/Grant/AuthCodeGrant.php#L216-L221

**Comment by suhaboncukcu** [comment]
Hi @Sephster, could you take a look at my explanation? I know it is not good to comment again but I couldn't find any other example for my case. I can fork the repo but I really don't want that since you are amazing and I don't want to miss an update. 

Is there any other platform that I can get an answer about this you can suggest? Stackoverflow has zero responses as well. 

Many thanks

**Comment by suhaboncukcu** [comment]
@mtangoo but I am doing that. _(I think)_

I am using Postman's Oauth 2.0 Authorization screen and sending the client secret. _(When I sniff the request I can read it is correctly sent via header)_

```
class ClientRepository implements ClientRepositoryInterface
{
public function getClientEntity($clientIdentifier, $grantType, $clientSecret = null, $mustValidateSecret = true)
    {
     
        var_dump($clientSecret); die(); // <<<< this is null


        return new ClientEntity();
    }
}
```

But even though I've implemented the ClientRepositoryInterface,   getClientEntity function doesn't get the client secret. I understand that this function should be called with four parameters including `$clientSecret` and `$mustValidateSecret` . However, I'm not the one calling this function. `AuthCodeGrant.php` already calls this function and sends parameters as 

https://github.com/thephpleague/oauth2-server/blob/b8b92e59255ffe586ddd50a3975d7219ca9a8c38/src/Grant/AuthCodeGrant.php#L216-L221

Since `AuthGrant` sends `$clientSecret` parameter as null, how can I validate the client? 


I hope this is a better explanation

**Comment by mtangoo** [comment]
which version are you using? 
I will test when am at machine with oauth2 code. Last time I checked it was working fine.

**Comment by mtangoo** [comment]
> I hope this is a better explanation

Yeah, they are far better ;)

**Comment by suhaboncukcu** [comment]
@mtangoo no need. I checked the source code again and days after I now realized that this function is called twice. Once sending the `clientSecret` as null. Then with the proper `clientSecret` So the example @Sephster shared actually includes the line below:

https://github.com/thephpleague/oauth2-server/blob/b8b92e59255ffe586ddd50a3975d7219ca9a8c38/examples/src/Repositories/ClientRepository.php#L36-L37

It looks like only when `$mustValidateSecret` is true; I should check for the `$clientSecret`and validate. Otherwise I shouldn't even check for the `$clientSecret` and just return void or false. I was trying to validate client for all the requests. 

Many thanks to you all. Now I can proceed with my mini project which _I hope_ will help some others.

**Comment by Sephster** [comment]
Sorry for the delayed response. It looks like you've arrived at the solution yourself which is excellent. As you'd noted, the package checks a client secret in the function `validateClient` which is in the _AbstractGrant_. This function extracts the `client_secret` for the request passed to it. In the auth code grant's case, we don't check this when requesting authorisation but can check it when requesting an access token.

I wish you luck in your project!
