### ISSUE TITLE
New realease

### ISSUE THREAD

**Issue by Zaszczyk** [thephpleague/oauth2-server#872]
Hi, could you make a new release? I would like to use this feature in my project: https://github.com/thephpleague/oauth2-server/pull/860 :)

**Comment by Sephster** [comment]
Hi @Zaszczyk - we are moving towards a new release soon but are awaiting some other tasks being finalised before release. I expect this will be within the week. 

In the meantime, you can always grab `dev-master` which should work fine but I wouldn't recommend this as if you forget, you might upgrade later to an unstable version.
