### ISSUE TITLE
Cannot access this package via composer

### ISSUE THREAD

**Issue by nealoke** [thephpleague/oauth2-server#875]
I just installed this package with `composer require league/oauth2-server` which worked as normal. When trying to use the class via the `autoload.php` provided by `composer` I always get an error. I'm not sure where I'm going wrong...

**Folder structure**
```
src
	- authorize.php

vendor
	- autoload.php
	- ... packages 

composer.json
composer.lock
```

**`authorize.php`**
```
require_once __DIR__ . '/../vendor/autoload.php';
$clientRepository = new ClientRepository();
```

**Error generated**
`Fatal error: Class 'ClientRepository' not found in C:\xampp\htdocs\wizer\packages\auth\src\authorize.php on line 5`

**Comment by simonhamp** [comment]
Hi @nealoke. I don't think this is an issue with the package or Composer.

What class is `ClientRepository` that you're trying to load? There's no such class in this package. There's a `ClientEntityInterface`...

Even so, you would still need to reference class names absolutely or alias them, e.g.:

```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use \League\OAuth2\Server\ClientRepositoryInterface;

class ClientRepository implements ClientRepositoryInterface {}

// OR

require_once __DIR__ . '/../vendor/autoload.php';

class ClientRepository implements \League\OAuth2\Server\ClientRepositoryInterface {}
```

Hope this helps.

**Comment by Sephster** [comment]
Can you post what your _authorize.php_ file looks like? This isn't a file from the package and it looks like the issue is from this file.

**Comment by nealoke** [comment]
@simonhamp indeed, that was where the issue is... I must say the documentation is not as handy to start with. I might do a PR to change that :) Thanks for helping!
