### ISSUE TITLE
Error in codeigniter integration

### ISSUE THREAD

**Issue by vivek-1874596** [thephpleague/oauth2-server#877]
I have imported library in my codeigniter project using composer in application folder
```
{
    "require": {
        "league/oauth2-server": "^7.0",
        "zetacomponents/database": "1.4.6"
    }
}
```
Also I have changed composer_autoload to TRUE in config file. 

`$config['composer_autoload'] = TRUE;`

But when I try to create instance of classess. It gives me error class "ClientRepository" not found.

```
$clientRepository = new ClientRepository(); // instance of ClientRepositoryInterface
$scopeRepository = new ScopeRepository(); // instance of ScopeRepositoryInterface
$accessTokenRepository = new AccessTokenRepository(); // instance of AccessTokenRepositoryInterface
// Path to public and private keys
$privateKey = APPPATH . 'third_party/vendor/private.key';
$encryptionKey = 'lxZFUEsBCJ2Yb14IF2ygAHI5N4+ZAUXXaSeeJm6+twsUmIen';        

// Setup the authorization server
$server = new \League\OAuth2\Server\AuthorizationServer(
          $clientRepository, 
          $accessTokenRepository, 
          $scopeRepository, 
          $privateKey, 
          $encryptionKey
        );

// Enable the client credentials grant on the server
$server->enableGrantType(
          new \League\OAuth2\Server\Grant\ClientCredentialsGrant(), new \DateInterval('PT1H')
 );
```

Please assist me!

**Comment by simonhamp** [comment]
https://github.com/thephpleague/oauth2-server/issues/72#issuecomment-374123182

**Comment by simonhamp** [comment]
As mentioned in the linked comment, you will need to write the various repository classes yourself, implementing the appropriate interface for each.

These repositories should contain your application's logic for storing the various OAuth2 entities (clients, scopes, tokens etc). It's kept abstract to allow for ultimate flexibility in how you choose to store these entities.

The [examples](https://github.com/thephpleague/oauth2-server/tree/7.0.0/examples) may help you get started.

I'm going to close this issue. Please feel free to open another issue if you're having any further trouble with your setup.
