### ISSUE TITLE
Adding support for Client scopes

### ISSUE THREAD

**Issue by leroy0211** [thephpleague/oauth2-server#886]
It would be nice to also limit Clients to specific scopes. I'm not sure if it's part of the Oauth2 Spec though. 

For example you might have 3 scopes `read`, `write` and `delete`. 

In most cases, every client may request the `read` scope. But not all clients may request the `write` or `delete` scopes. Especially when using the client credentials grant.

**Comment by simonhamp** [comment]
@leroy0211 This is left up to your implementation. The logic for achieving this shouldn't be too complicated, but it is very dependent on your specific circumstances as it won't be needed/wanted in all implementations.

Having said that, if you do come up with an implementation that you feel is quite generic and can be integrated without adding any extra setup on behalf of other implementors, if you can share it, please feel free to submit a PR :)

**Comment by Sephster** [comment]
The finalizeScope method is probably best used for this purpose. It will modify the requested scopes by the client so would be perfect for this. As @simonhamp  says, this is an implementation detail so would be unlikely to be included in the core library
