### ISSUE TITLE
Count Number of Failed Login Attempts

### ISSUE THREAD

**Issue by ricky2k7** [thephpleague/oauth2-server#888]
Hi,

I'm using Laravel Passport (that is built on top of oauth2-server) to manage API authentications. 
I would like to create a login attempt mechanism to lock a user after a predefined number os times. How can i accomplish this with oauth2-server? Are there any events triggered when a user login fails? How can i accomplish such task?

Cheers.

**Comment by Sephster** [comment]
Hey. You are probably wanting to use the event emitters. Details about them can be found [here](https://oauth2.thephpleague.com/authorization-server/events/). Hope that helps!
