### ISSUE TITLE
generateHttpResponse cannot write to response stream

### ISSUE THREAD

**Issue by galab-devision-bg** [thephpleague/oauth2-server#891]
Hello guys, I have an issue using the library, I have configured it and have implemented all necessary checks. I am using the yii2 framework. When I get to the method **generateHttpResponse** in **BearerTokenResponse.php** and I var_dump($responseParams);die; I get all the data I need. but after this line: 

`$response->getBody()->write(json_encode($responseParams));`

I get empty stream in the response: 

```
object(GuzzleHttp\Psr7\Response)#430 (6) {
  ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=>
  string(2) "OK"
  ["statusCode":"GuzzleHttp\Psr7\Response":private]=>
  int(200)
  ["headers":"GuzzleHttp\Psr7\Response":private]=>
  array(3) {
    ["pragma"]=>
    array(1) {
      [0]=>
      string(8) "no-cache"
    }
    ["cache-control"]=>
    array(1) {
      [0]=>
      string(8) "no-store"
    }
    ["content-type"]=>
    array(1) {
      [0]=>
      string(31) "application/json; charset=UTF-8"
    }
  }
  ["headerNames":"GuzzleHttp\Psr7\Response":private]=>
  array(3) {
    ["pragma"]=>
    string(6) "pragma"
    ["cache-control"]=>
    string(13) "cache-control"
    ["content-type"]=>
    string(12) "content-type"
  }
  ["protocol":"GuzzleHttp\Psr7\Response":private]=>
  string(3) "1.1"
  ["stream":"GuzzleHttp\Psr7\Response":private]=>
  object(GuzzleHttp\Psr7\Stream)#424 (6) {
    ["size":"GuzzleHttp\Psr7\Stream":private]=>
    NULL
    ["seekable":"GuzzleHttp\Psr7\Stream":private]=>
    bool(false)
    ["readable":"GuzzleHttp\Psr7\Stream":private]=>
    bool(false)
    ["writable":"GuzzleHttp\Psr7\Stream":private]=>
    bool(false)
    ["uri":"GuzzleHttp\Psr7\Stream":private]=>
    NULL
    ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=>
    array(0) {
    }
  }
}
```

**Comment by Sephster** [comment]
`$response->getBody()` returns an instance of the StreamInterface. I would check this to see if it is seekable and writable using the following calls:

```
$response->getBody()->isSeekable();
$response->getBody()->isWritable();
```

That would be my first port of call to ensure there is nothing funky going on with the stream. Good luck and please let us know how you get on

**Comment by galab-devision-bg** [comment]
@Sephster Sorry for the delayed answer I was not able to test that earilier. Both isSeekable and isWritable return true.

**Comment by simonhamp** [comment]
@galab-devision-bg can you isolate the `json_encode($responseParameters)` part to see what the output of that is please?

**Comment by galab-devision-bg** [comment]
@simonhamp Yes :) It returns the correctly generated data. 

`"{"token_type":"Bearer","expires_in":2592000,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImM3MTYxYmFiYTVlODczMjYxNTVkNmI3ODg3MWNmN2I3NDI1YmY3ZTVlMTYzYTgyOWIzZTAzMDQ2YWU4MzE1YTI4YTNkZTNjMDU2NGQyOTRjIn0.eyJhdWQiOiIxIiwianRpIjoiYzcxNjFiYWJhNWU4NzMyNjE1NWQ2Yjc4ODcxY2Y3Yjc0MjViZjdlNWUxNjNhODI5YjNlMDMwNDZhZTgzMTVhMjhhM2RlM2MwNTY0ZDI5NGMiLCJpYXQiOjE1MjQ0NzExNzIsIm5iZiI6MTUyNDQ3MTE3MiwiZXhwIjoxNTI3MDYzMTcyLCJzdWIiOiIxIiwic2NvcGVzIjpbe30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se30se31dfQ.F1QUhYImb_pNiBwpSyh1Z002vFRKO9krPkIhnlJYeCtT_GFHSplZxV3o7jgl8UIQxsLCAcnDBMWPuk5xIxcFMw7ca0om_miuYK0qhHp-7_RGYHMlYJN1ln77xzCSH3l241FitctyVl-7Up9peUCYOmth2GVR8EIaGj70sD4B3boYjTAmYV1KNpzlxtMqVurSwf1_uAIVb-0Uid8LJlklzKU4n4WVmPtcdp8ZKxX3WmoEMGQgFRuRCO1pZKkcaLwBGqg-KU8zU90YptMsVhDvIMS_fdDHcKleqeECMx7CKocycjoVwtvazZxK6InblunEEoSrbmkvJe5bIgdUzmXzaw","refresh_token":"def502006be9916a5d6a0ca17b84a156a367f5afe1aaa89f93a6048fee8819256a17d06d2e8114004bc20b57bc516da076228cbcd0d2b61bc614867bc4dcfa7c0bd571b487e8708855890e2f23f3ddb9b2899aece167707cafed8ebf9a021fdb2140ac086038d9b3de6ed9f14ddfa710d7423c23a0d58561c5566cb60dda1f338f89165cf2bd724dc1a3cdeaf5267410909e414a179ed64159e9c18ba2d714525659baac112e2aaca3b9bbac887161ea503d021b4639aed2d2bf063263e19dd5fbb8d88d8fd0ec4a0134009a8c3ae7cfdc1a134e7bf98c5f16197fbfa930ba8b8a36090f7fea585e12c51890eef6ed35f37aa45993acc10c87ed376014c1020ddefb4c18911b5e4745484b1b3245cbd426e47166e3d7f0f30e9b0dee6738d4889c23f07b6e4af106382b456f5818da1aeafcf1ac52bd332dd31f0049fb01a8832eff7e4ff9ded4f2ae88ba78d9e296f23240d7c3a805fc66483cab8bef6b3b9485614d2d2ce76b97ae512d3d5b2362e6fb9f7cb4873bc716c8d2bc15c0b69e32d398b9a81f7bd23c9b48d1788dab07ec349fefbf1db07cfa781f1a5f07414c21c253306b648a781d043745b366b7a94ae85bd6429144fb714fad09942a3ae197f00853c71b8b4754ecf2bae569347052c4fa0bb80472b0eb9f2edc3cacff5cdeae21532fba7b207233b3db84023e57bdf8a28966e82bc9a0c1e1643771c9dd6a61281bf9a8df2abd6970c98574cfae276f8117b9a91c6c815c5b00e15950561edd46ece8e327498bfb45c8acf94aa25db84d0bd92e3d82c31742092585ac08df73f88db2847aa9b5dc4c3363918433afbe28824ca713d252e8197365e4376312f00a0c5fb183cbabe2dbbc6c0601abb3455effa6bca402b3ff959df362f5588e83f72c020e799f8fc61313d61714c521cbc4d27c7aa361e3b400ba2736f2a8fd39289587cac515a9690055118f68d9d4ba10b1ba1bc787a094c7225389301e97cbf5f40b7eaf9736f620013db96224f90324afb2f1a3f09372397b"}"`

**Comment by simonhamp** [comment]
I understand, but I can't see the problem being in the `generateHttpResponse()` method.

In `generateHttpResponse()`, please add a `var_dump` before the `return`:

```php
$response->getBody()->write(json_encode($responseParams));

var_dump($response);

return $response;
```

Please let us know what the var_dump result is here.

**Comment by galab-devision-bg** [comment]
The result of it is in the first post that is the GuzzleHttp\Psr7\Response object.

**Comment by simonhamp** [comment]
So can you change that to `var_dump($response->getBody()->getContents());` and let us know what you see?

**Comment by galab-devision-bg** [comment]
It returns null

**Comment by Sephster** [comment]
Hmmm, this is really strange. Can you try the following?

```
$responseParams = array_merge($this->getExtraParams($this->accessToken), $responseParams);

// Lets find out the response params (which you have stated are present
var_dump($responseParams);

// Check the response BEFORE we set the headers
var_dump($response);

$response = $response
    ->withStatus(200)
    ->withHeader('pragma', 'no-cache')
    ->withHeader('cache-control', 'no-store')
    ->withHeader('content-type', 'application/json; charset=UTF-8');

// Check the response AFTER we have set the headers
var_dump($response);

$response->getBody()->write(json_encode($responseParams));

// Check what we are writing to the body
var_dump(json_encode($responseParams));

// Check the response AFTER we have set the body
var_dump($response);

return $response;
```

That's a lot of var dumping but it should give a better idea of what is happening. If this doesn't turn up anything, I think we'd need to see the full codebase to progress this

**Comment by Sephster** [comment]
@galab-devision-bg did you try the above? How did you get on?

**Comment by Sephster** [comment]
@galab-devision-bg I'm closing this issue as we haven't heard from you in a while. If you would like to progress this further, please get back to us and we can reopen this. Cheers

**Comment by guich2507** [comment]
I encounter exactely the same problem. Do you know how it was solved for him ?

**Comment by Sephster** [comment]
We don't. If you could provide some var_dumps as listed above it might give us a better insight into the issue. Any help would be appreciated

**Comment by guich2507** [comment]
Hello, thanks for your quickness.
Of course i can, but i do not have the same code.
Can you please say me in the bearertokenresponse where i should take var_dump ?
class BearerTokenResponse extends AbstractResponseType
{
    /**
     * {@inheritdoc}
     */
    public function generateHttpResponse(ResponseInterface $response)
    {
        $expireDateTime = $this->accessToken->getExpiryDateTime()->getTimestamp();

        $responseParams = [
            'token_type'   => 'Bearer',
            'expires_in'   => $expireDateTime - \time(),
            'access_token' => (string) $this->accessToken,
        ];

        if ($this->refreshToken instanceof RefreshTokenEntityInterface) {
            $refreshTokenPayload = \json_encode([
                'client_id'        => $this->accessToken->getClient()->getIdentifier(),
                'refresh_token_id' => $this->refreshToken->getIdentifier(),
                'access_token_id'  => $this->accessToken->getIdentifier(),
                'scopes'           => $this->accessToken->getScopes(),
                'user_id'          => $this->accessToken->getUserIdentifier(),
                'expire_time'      => $this->refreshToken->getExpiryDateTime()->getTimestamp(),
            ]);

            if ($refreshTokenPayload === false) {
                throw new LogicException('Error encountered JSON encoding the refresh token payload');
            }

            $responseParams['refresh_token'] = $this->encrypt($refreshTokenPayload);
        }

        $responseParams = \json_encode(\array_merge($this->getExtraParams($this->accessToken), $responseParams));

        if ($responseParams === false) {
            throw new LogicException('Error encountered JSON encoding response parameters');
        }

        $response = $response
            ->withStatus(200)
            ->withHeader('pragma', 'no-cache')
            ->withHeader('cache-control', 'no-store')
            ->withHeader('content-type', 'application/json; charset=UTF-8');

        $response->getBody()->write($responseParams);

        return $response;
    }

    /**
     * Add custom fields to your Bearer Token response here, then override
     * AuthorizationServer::getResponseType() to pull in your version of
     * this class rather than the default.
     *
     * @param AccessTokenEntityInterface $accessToken
     *
     * @return array
     */
    protected function getExtraParams(AccessTokenEntityInterface $accessToken)
    {
        return [];
    }
}

**Comment by guich2507** [comment]
1 -- var_dump($responseParams);
        $responseParams = \json_encode(\array_merge($this->getExtraParams($this->accessToken), $responseParams));
      2 -- var_dump($responseParams);
        if ($responseParams === false) {
            throw new LogicException('Error encountered JSON encoding response parameters');
        }
      3 -- var_dump($response);
        $response = $response
            ->withStatus(200)
            ->withHeader('pragma', 'no-cache')
            ->withHeader('cache-control', 'no-store')
            ->withHeader('content-type', 'application/json; charset=UTF-8');

        $response->getBody()->write($responseParams);
      4 -- var_dump($responseParams);

      5 -- var_dump($response);


1 ==> string(1559) "array(4) {
  ["token_type"]=>
  string(6) "Bearer"
  ["expires_in"]=>
  int(3600)
  ["access_token"]=>
  string(642) "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJmcm9udF9zdG9ja3dlYiIsImp0aSI6ImI5YmE2OGMxNDNmZjEwOTRmNGU0NzA1NjliMzBmNDUzYjZlMTE5MWIxODg5ODRiNTFkMmYyMjBlZjA0NDI3NTEzMjBiY2M2OWI5MmM3ZGViIiwiaWF0IjoxNjE0Mjk5ODExLCJuYmYiOjE2MTQyOTk4MTEsImV4cCI6MTYxNDMwMzQxMSwic3ViIjoiZGVtbyIsInNjb3BlcyI6WyJlbWFpbCJdfQ.FGVur7U6hyrzyloOVNYnZ9eHmgTvWc5ewLgEMBEYqsXDZcKYAfHyH1NpVt2XH8Tyd0PE47DwixlxZD60qXV8D4Bb5DowERNYRxFTqcitQ7Kry8S2rHCNbXxaO8iEC_C7IM2Mvp2soTjWiydrKdo9LBtk6AXndGbjiwrDr8bQE03Mfsb6teDzbIQ-_0c3wnllwLPOJEPWV6rvdndHYWIUycFAbJ9EyTa-7kCdpZXi0fZpG4Oh7sApaW0w9D5ULVHFaOR3FCG2A-KDWwolU8YE8WBdTdZprZz8Jn1ZacMHLpA-i9rQzCyPju8-lwL0ynlyM8DzqUXFhiEBdw8fmoQkUQ"
  ["refresh_token"]=>
  string(756) "def50200278d4841c93c76fa47a744fb09abfa319485c1333881f9ac917de5eff4c91aad54da257ba55499622142ffb51d6376820fb950d2ad4fed6efe437f750f4ab430bcdc10832b8cb4d5b1726e48eec11a0b61bbe7648ac5f834384375da183887199af3a6a9c214d30301ef89d4d6c1b7bf4d9e0a8f1a5b8139e40543d8ab1808f0f880e7edf90af231e9329a820fb4f1a25eea7fea4aa57fe65c546e89fb828cdc0e84bc23da06d22d7b1fafc342fed98b077296cd52732d61cae26e50521fbe9d68f52844d5d371bd7a724faa38896f4f15607ccae2934216357bfdd191ff571b8ed867f62d14044391454c9b1131da19511ec4cfca33aaeba2b8a07f8ba10df97cee6cd701ec1e8fe75fa4c97adb679bd3c86c631b9339154dc6642d5cfcf460163c1efbac8a95551c335e5a1893fe42f3b9eeee43521d574ab0d60321355a392a5de36e48d61774daf69e4c7f49bdac6a21b8b40b4590966c0774ee0c6f42ba7f63c87026fbb57409e89a24929707536e8a848b5331"
}

2 ==> {"token_type":"Bearer","expires_in":3600,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJmcm9udF9zdG9ja3dlYiIsImp0aSI6ImQ3ZTU2NTJhZDgyM2IyNjFiOWJmMTg0MzhjMjc2NzM5NjI2NDI5NDg2OTVhYmU0NDdlMDY0MTEyNGE4NzI4Yzc2ZTMxOTQzNWUwYTZhNDVmIiwiaWF0IjoxNjE0Mjk5ODUxLCJuYmYiOjE2MTQyOTk4NTEsImV4cCI6MTYxNDMwMzQ1MSwic3ViIjoiZGVtbyIsInNjb3BlcyI6WyJlbWFpbCJdfQ.CvSuMZ6LJkp_BeqKA20W-RWjbW_RwsK4FDo0DrlPnvKDLbNkgSvVV3lEalrlFU9JhZkKeJWo73RqNXGja3SNIMl05-CdSpVyZtZO3aB5fJipQPry1xTW3F7DMBUJ2NUdBmM8lbcxD8IJ9S96QADQMj6467D3Oqrs3MBhIKrU6jmE3hw-Vx6DUJhA2MuSD0NlU80GMTVaxRaYMidqC4EJDeJwW4wXqXjZbZBx2SrWFpLoqpc3v1rgNzPQfy2ObL-Eai2pmC8XPc2VFU8urT_C5OGmb2Yk37TPBeWxawGUbmDJvWX8VxTgpQslXu1I-FaMYy_OJ9VwUMlf0g-wTNFuRQ","refresh_token":"def50200d78d382a3e4fb6a62147d7dd14a7d55ef6f8c99af3ffb87fcc0473eb4a942eff777754543d758fa0cda930d309fb7148b5c5e225974254af2e391ec9f3ec132871d469bb49dc9a8c31eb6c5157630b53f0f495ed2fc76b2fb4f7730795159957b078adc8ae5d29887e278e802efd1ca1ff7fc641d328419a60f4a026ec90f4167a7c1607a0f6ae43aa3f970472d4746820463e727582cecca9117c88a9348891ef8d5a1862c2db8eed724e9d2748069160b5b058ced3e05b6828a7b3ad81112976be30caa82c04c126be2a2176f18eb841227c3bcf23e0cf35834d974be33c9db94e72e09842aeae39d9641b9332ecfcdbbbb81510afe66f0a1bf3f23f88be9d86233a9b54d168a2aa99e821656a8552e304ee7ce4a81f808202462ef74271db592a7e2dcddb12f24ee08706e87281d69bcdeba3e8934872ac461feefe01c343299cd4792831621bfa8bf68a2dd63d0de77cef0427d190ea35913f4f93c1d683c22a0b0b4dd6775025de8bbce7683853bc401e804b53"}

3 ==> string(449) "object(GuzzleHttp\Psr7\Response)#50 (6) {
  ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=>
  string(2) "OK"
  ["statusCode":"GuzzleHttp\Psr7\Response":private]=>
  int(200)
  ["headers":"GuzzleHttp\Psr7\Response":private]=>
  array(0) {
  }
  ["headerNames":"GuzzleHttp\Psr7\Response":private]=>
  array(0) {
  }
  ["protocol":"GuzzleHttp\Psr7\Response":private]=>
  string(3) "1.1"
  ["stream":"GuzzleHttp\Psr7\Response":private]=>
  NULL
}

4 ==> {"token_type":"Bearer","expires_in":3600,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJmcm9udF9zdG9ja3dlYiIsImp0aSI6ImYxNTg0NmU1YTNjMzBjMDRkMThjNGFiYzdiYTlkYjE5ZDljYmEyZGZlZGFjY2EyZWY2NzExMTk3MmFiOWZhZjcyYjUxYTFiMWE4MzU4YTY0IiwiaWF0IjoxNjE0Mjk5OTE1LCJuYmYiOjE2MTQyOTk5MTUsImV4cCI6MTYxNDMwMzUxNSwic3ViIjoiZGVtbyIsInNjb3BlcyI6WyJlbWFpbCJdfQ.Z6qP6FOKL9jxOZuRocQPedCPgKUqwxoCIacgkYaffERZ5JxTQ3b-XXNRtQ_81Bdu3lBdoqH4RqZctY3V3ooR1jynA-cFZo83SM-lPLwc9hqinuLzW_3XYO_1kAp2ehEOuhTTexJpbcw41344LZKC_LUS71fIz_2QyvZqKl5NI_7mrsyagfOwsnA1o1Wfz0A2qfhx7Chg1xzc_jC3v83CN4jrwu2d3WOMbHWQNO_fQCTC-Xwf2OLp-8VnPJRIxIFjYkJmBOEdrYbRacq_LCDlto-RlWu8UbKU_S8K2b6hpOfwGnDetI8GBvptbp5FH9QV3T85_QctWziUuwIAiSeLVg","refresh_token":"def50200efbba003d0fd6afc7f10bdf63a941145e96f90c5f5bc515d9e0d7126bf7ca1fdfb729d93f621c99ec3402d4eb915226e8288d16307f94abffa3b5f4d147632d465cc3bdc70336075b01ae092afd3a5c1a132b93f48263424959244d450680222a7a6836254aa0212724ab9562c6002d648516e5b93db840a5dda81f2e42694b3c90fd14948d401d15e144337367d22da900b430df805da5ce9749b83ca056ab8b0f9f32c82a389fe97ac9c24b8083181b1dc57019e27f84728fe9c9ca9742b5e4c446fb413ea08f876c11e53912d32494efe3bca1271305ead6e2074305adb9c2a2c78fbc64d3cdddf19b6b71569263cda2ecc9c1d0f8349e5bc387d4bad5451bdcb32d340d00a73f367c169c80d1c075b949bf6fbb22e7370d4b1d3edab3b218a72c5e026cd9415d3834aa0906a193e48623fd3ee6501f426669f3365d235d305f2922af3bf7f65d80d1cd7d2918dac99a9f3ed52de4909be8c02eb9fb892382dc8871998802a7801f18059a20b39fc65c592cf9a85"}

5 ==> string(1399) "object(GuzzleHttp\Psr7\Response)#74 (6) {
  ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=>
  string(2) "OK"
  ["statusCode":"GuzzleHttp\Psr7\Response":private]=>
  int(200)
  ["headers":"GuzzleHttp\Psr7\Response":private]=>
  array(3) {
    ["pragma"]=>
    array(1) {
      [0]=>
      string(8) "no-cache"
    }
    ["cache-control"]=>
    array(1) {
      [0]=>
      string(8) "no-store"
    }
    ["content-type"]=>
    array(1) {
      [0]=>
      string(31) "application/json; charset=UTF-8"
    }
  }
  ["headerNames":"GuzzleHttp\Psr7\Response":private]=>
  array(3) {
    ["pragma"]=>
    string(6) "pragma"
    ["cache-control"]=>
    string(13) "cache-control"
    ["content-type"]=>
    string(12) "content-type"
  }
  ["protocol":"GuzzleHttp\Psr7\Response":private]=>
  string(3) "1.1"
  ["stream":"GuzzleHttp\Psr7\Response":private]=>
  object(GuzzleHttp\Psr7\Stream)#67 (7) {
    ["stream":"GuzzleHttp\Psr7\Stream":private]=>
    resource(9) of type (stream)
    ["size":"GuzzleHttp\Psr7\Stream":private]=>
    NULL
    ["seekable":"GuzzleHttp\Psr7\Stream":private]=>
    bool(true)
    ["readable":"GuzzleHttp\Psr7\Stream":private]=>
    bool(true)
    ["writable":"GuzzleHttp\Psr7\Stream":private]=>
    bool(true)
    ["uri":"GuzzleHttp\Psr7\Stream":private]=>
    string(10) "php://temp"
    ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=>
    array(0) {
    }
  }
}

I hope it is enough
