### ISSUE TITLE
Wordpress Support

### ISSUE THREAD

**Issue by jpmelnik** [thephpleague/oauth2-server#898]
Do you have an example with Wordpress REST Api?

Thanks

**Comment by Sephster** [comment]
I'm not aware of a WordPress integration. I was searching for one the other week but didn't find any that use this library. Hopefully someone from the community might know of a good example

**Comment by Sephster** [comment]
@jpmelnik I'm going to close this issue due to a lack of activity. I'm not aware of any WP plugin but if someone is, please feel free to comment here.

**Comment by andrewmclagan** [comment]
We will be working on an implementation starting ASAP. 

https://github.com/wp-headless

The intention is to integrate it into the wp-headless ecosystem that is being developed. Javascript client and react data fetching bindings. For a fully supported headless CMS environment.
