### ISSUE TITLE
If public key belong to incorrect user/group or it's file Permissions is 000, system won't give help tips

### ISSUE THREAD

**Issue by caseylau** [thephpleague/oauth2-server#900]
https://github.com/thephpleague/oauth2-server/blob/master/src/CryptKey.php#L53
```
       if ($keyPermissionsCheck === true) {
            // Verify the permissions of the key
            $keyPathPerms = decoct(fileperms($keyPath) & 0777);
            if (in_array($keyPathPerms, ['400', '440', '600', '660'], true) === false) {
                trigger_error(sprintf(
                    'Key file "%s" permissions are not correct, recommend changing to 600 or 660 instead of %s',
                    $keyPath,
                    $keyPathPerms
                ), E_USER_NOTICE);
            }
        }
```
We are using drupal's module [simple_oauth](https://www.drupal.org/project/simple_oauth) which depends on this repo. 
We find if public key(sites/config/certificates/ssopublic.key) belong to incorrect user/group or it's file Permissions is 000, system won't give help tips.  Above is the relevant code.

**Comment by Sephster** [comment]
`trigger_error()` should be used in conjunction with an error handler which will surface the error for you. You can register an error handler using the function `set_error_handler()`. 

Unfortunately, I don't know enough about Drupal to advise on how error handling is used in that application. 

You'd mentioned you don't get an error when the permission is set to 000. Does this also occur when set to 777 for example, which is similarly not allowed? I suspect you won't see an error if the permissions are set to 777, in which case, I believe this is an issue with the error handling in Drupal/simple_oauth/your setup.

If you could let me know about the 777 permission, we can progress from there. Thanks

**Comment by caseylau** [comment]
@Sephster Very thanks for the info.  
If I set it to 777, I will get the error message in every drupal page.
![image](https://user-images.githubusercontent.com/20714821/39999063-906c1d94-57ba-11e8-8e11-1a348926a42c.png)
If I set it to 000, I won't got the error.  
**Wrong user/group** don't have tips too, can this be fixed in this repo?

**Comment by caseylau** [comment]
I debug it just now.  
```
        if (!file_exists($keyPath) || !is_readable($keyPath)) {
            throw new \LogicException(sprintf('Key path "%s" does not exist or is not readable', $keyPath));
        }
```
When permission is 000 or wrong user/group will trigger above error, but this error don't display in drupal page, Maybe we should fix it in [simple_oauth](https://www.drupal.org/project/simple_oauth)

**Comment by Sephster** [comment]
No problem @caseylau. It looks like this is an issue with _simple_oauth_ so I will close this issue. If this turns out to not be the case, please get back in touch and we can look into this further.
