### ISSUE TITLE
I want to separate resource services from authorization services

### ISSUE THREAD

**Issue by acodercat** [thephpleague/oauth2-server#906]
I want to separate resource services from authorization services

**Comment by Sephster** [comment]
The server already does this by providing an auth server class and a resource server class. Please can you state your question and I will try to help as best as possible.

**Comment by acodercat** [comment]
Where is the resource class?thx

**Comment by Sephster** [comment]
It is in the _src_ folder called _ResourceServer_.

**Comment by acodercat** [comment]
thanks

**Comment by Sephster** [comment]
Closing as I believe this is resolved.
