### ISSUE TITLE
verifying Token with custom logic for handling clients validity

### ISSUE THREAD

**Issue by mtangoo** [thephpleague/oauth2-server#907]
Hi,
I'm facing this requirement to occasionally verify a token using a custom logic. To (over)simplify it it goes like
1. User logs in client X in his machine
2. User want to user client Y on same machine

client X and Y are from same developer so they can decrypt the same config file and get access token.
Now before client Y admits user, it must verify a token silently. In the server, I want to check using custom code. How can I go about the verification (which repo/classes should I look into?).

Sorry if there is something that is straight forward. If anything is not clear, I would be happy to clarify.

Cheers!

**Comment by Sephster** [comment]
Sorry @mtangoo but I'm not following the example here. It is this bit which I'm struggling with:

> Now before client Y admits user, it must verify a token silently.

Which token are you talking about here? The access token? I don't think a client would have the ability to verify this as this would usually be done by the resource server. 

If you could provide a bit more background I will try to help as best I can.

**Comment by mtangoo** [comment]
Hi @sephster,
Sorry for not being clear. 

The flow is, app X gets access token by Auth Code for example. But app Y by same dev in same machine as X Should not require to take user thru login (given that user have previously approved X and Y for same scopes) 

So Y needs only to verify access token  aqcuired by X and if valid it will continue using it.

Y will send the token somehow to Oauth server to verify the token and hence my question on how to do it properly with this library. 

If am not clear let me know

**Comment by mtangoo** [comment]
Note that X and Y are two different services accessing resources from different servers

**Comment by simonhamp** [comment]
You shouldn't attempt to get the *user* to pass their token around between apps as this is really insecure and one of the main reasons for OAuth's existence in the first place.

**Ideally the user never sees their token.**

But there are potentially a few ways to tackle your problem:

### Shared Client Credentials
One approach is to set the OAuth Client ID & Secret to be the same for both X and Y.

This is kinda naughty though as it means you've got two apps pretending to be one (from the OAuth service's perspective) and could be a pain down the line.

Also, this might require the OAuth service to support multiple callback URLs, so this might not even be a possibility.

I'm guessing you're in control of the OAuth server too? Where does it fit into this whole picture?

### Implicit Token Sharing
If both X and Y are going to stay co-located, then there's no reason why a single token couldn't be used by both apps (as long as that makes legal and moral sense for the user, of course).

For example, you could store the user's current access token in `$_SESSION` and have both apps look at the same session store and session cookie. Or in a shared database record that is accessed via a session cookie.

This may be more challenging from the client side, depending on how your apps are distributed.

For example, if X and Y are web apps that run on completely different domain names (e.g. xapp.com and yapp.com) you would need to make sure the cookie you use to identify the user with can work across both domains.

But it would save a few extra round trips to the OAuth server and arguably won't require any extra validating.

---
Honestly, I don't really like either of these methods as they're kind of insecure and they create interdependencies that could be the cause of headaches and sloppiness which may make things harder for you and/or your users later on - e.g. still logged into X, not logged into Y. Or, "we forgot to add a logout". Or, sessions living longer than tokens resulting in users logged in to app but API unable to call that API.

Ideally you'd use a more normalised approach: have X and Y each being a separate Client of the OAuth-protected services. This has many benefits (for users and devs), but mainly if a user logs in via App X and switch to App Y within a reasonable amount of time, they might only be presented with an auth approval when redirected to the OAuth service, not a login screen.

The caveats though:
- this really only works if everything is web-based,
- the user is using the same browser to use both X and Y, and
- the OAuth service stores a fairly reasonable session cookie in the user's browser.

**Comment by mtangoo** [comment]
Thanks @simonhamp for great piece of advice. I think it have enough of problems to be avoided completely without much advantages. I'll think another way out that will keep Oauth intact
