### ISSUE TITLE
AbstractGrant::issueAccessToken adds scopes twice 

### ISSUE THREAD

**Issue by Erikvv** [thephpleague/oauth2-server#909]
https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AbstractGrant.php#L360

```php
$accessToken = $this->accessTokenRepository->getNewToken($client, $scopes, $userIdentifier);
...
foreach ($scopes as $scope) {
    $accessToken->addScope($scope);
}
```

I gues the user code not supposed to add them in ->getNewToken()? But why give those parameters then?

This could be documented in the docblock of AccessTokenRepositoryInterface::getNewToken

**Comment by Sephster** [comment]
Thanks @Erikvv - there is a bit of repetition here with the client and userIDs as well. I think this will probably need to be tidied up and released in version 8. I will try to get this actioned before the end of the weekend. I've made a start on it in the PR here

**Comment by Sephster** [comment]
Closing as now merged into the version 8 branch
