### ISSUE TITLE
Are there any schema examples? repositories implementation examples with mysql backend?

### ISSUE THREAD

**Issue by loganto** [thephpleague/oauth2-server#911]
Are there any schema examples? repositories implementation examples with mysql backend?

I think I get what I need to do to setup the provider, but it would really really help if I could see some examples.

**Comment by Sephster** [comment]
There are no official schema examples as yet. This is something that is repeatedly asked for though so we might add this in the future. There is already an open issue for a MySQL Schema.

In the meantime, one user of the package did [provide his own schema](https://github.com/thephpleague/oauth2-server/issues/794#issuecomment-339110212) for people to reference which might be worth taking a look at.

Sorry that there is nothing more concrete at this time

**Comment by simonhamp** [comment]
#794 working on this soon :)

**Comment by loganto** [comment]
@Sephster im a little confused by the schema that as provided by sergeyklay: http://vpaste.net/lQmK1   

What's the use case would there be for these tables?
client_grants, client_scopes ?        
user_grants, user_scopes?  
grants & grant_scopes ?
  
Like i'm trying to think where would thee be useful in my app and I just cant... are those supposedly should be used for ACL?

**Comment by Sephster** [comment]
Sergey would probably be best placed to answer but I am presuming the following:

* Grants are for storing which grants are active on the server
* Grant scopes are for associating scopes with given grants (perhaps he doesn't want all scopes to be applicable to all grants)

* Client Grants must be specifying which grants are permissible/enabled to particular clients
* Similarly I'm guessing there is some kind of permissions built in to Sergey's implementation for restricting scopes to certain clients

* Use grants must be either restricting or simply listing the grants a user is using via a client
* Similar for user scopes. He is either restricting or just listing which scopes a user is using

In all honesty if I was implementing this I wouldn't bother too much with the user tables. This is all optional and specific to Sergey's implementation of course. The server is sufficiently flexible to allow many different ways to implement.

If you don't have use for restricting grants/scopes to clients/users, don't implement these tables.
