### ISSUE TITLE
Why do we need getName() in ClientEntityInterface?

### ISSUE THREAD

**Issue by JasonTheAdams** [thephpleague/oauth2-server#930]
I've been working on building out OAuth in vanilla PHP for a week or so now using this library. I've been deep diving into the library code to try and understand the usage of the interfaces and such required for the purpose of trying to understand the necessary MySQL table structures.

One puzzling method is `ClientEntityInterface::getName()`. Simply enough, it wants the client name. What's strange, though, is that outside of unit testing it doesn't appear that the method is ever actually used. Seen here: https://github.com/thephpleague/oauth2-server/blob/master/src/Entities/ClientEntityInterface.php#L26

I could just leave the method empty in my entity classes, but it makes me nervous in case it's planned on ever being used.

Can someone speak into the purpose of this? It seems like an unnecessary requirement.

Thanks!

**Comment by Sephster** [comment]
It is actually used in the client trait which provides a ready made implementation for some of the functions provided by the `ClientEntityTrait` but I guess this isn't a real _use_ so I see your point.

I can't speak as to why this was added in historically. The main reason I can think for having such a function is that when a client redirects the user to the authorisation end point, the client only provides its ID. 

Typically we would want to let the user know which application is requiring access and the scopes they are requesting. The client ID wouldn't mean anything to an end user so we would need to get the client's name to display to the end user. I presume this is the main use case for the function.

As the function isn't used in the library directly, I think it is a fair assertion that it perhaps shouldn't have been included, and left up to the implementer whether they wanted to use this but I don't think it warrants removing as it is a minor point and all clients should have names which can be retrieved via this method if need be.

The _name _ of the client is strictly required by the OAuth 2 spec but most implementations require it for easy identification.

**Comment by JasonTheAdams** [comment]
Thanks for your thoughts, @Sephster! That makes sense. It doesn't have any "functional" purpose for this library, but I agree that it's a good idea to have it if it's part of the spec. The implementing developers can decide if and how to utilize the name further.

I'm going to close this as I think it should definitely stay since it's part of the spec.
