### ISSUE TITLE
decode jwt

### ISSUE THREAD

**Issue by faravinicius** [thephpleague/oauth2-server#947]
How can I decode the received JWT in Bearer ?

**Comment by docxplusgmoon** [comment]
Example code:
`$accessTokenRepository = new AccessTokenRepository();
        $bearerTokenValidator  = new BearerTokenValidator($accessTokenRepository);

        $publicKeyPath = $this->config->public_key_path;

        $bearerTokenValidator->setPublicKey(new CryptKey($publicKeyPath, null, false));

        $request = $bearerTokenValidator->validateAuthorization(ServerRequest::fromGlobals());

        print_r($request->getAttributes());`

**Comment by faravinicius** [comment]
Thanks, @docxplusgmoon!

**Comment by faravinicius** [comment]
Today I was able to finalize an implementation and it is giving an error. Call to undefined method Zend\Diactoros\ServerRequest::fromGlobals().

Help me ?

**Comment by docxplusgmoon** [comment]
@faravinicius ServerRequest must be instance of GuzzleHttp\Psr7\ServerRequest. Add `use GuzzleHttp\Psr7\ServerRequest` on head your class
