### ISSUE TITLE
Why you use global Request object instead scalar parameters in classes?

### ISSUE THREAD

**Issue by docxplusgmoon** [thephpleague/oauth2-server#948]
Hi. All classes use global Request object for extracting tokens or client data. Because of this classes not reusable. We want add our custom logic in creating or validating tokens. But more methods require global Request object. I think, all income parameters (tokens, client_id, client_secret etc.) must be assign by client code. Example src/Grant/PasswordGrant.php. Code is not support SOLID principles.

Sorry for my english)

**Comment by Sephster** [comment]
Closing this issue as have not heard back from @docxplusgmoon. If this is still an issue, please comment on this ticket with a clarification of the problem and I will look into this further. Thank you
