### ISSUE TITLE
How can add a custom token generation for codeigniter

### ISSUE THREAD

**Issue by gopalvenu033** [thephpleague/oauth2-server#951]
I have an ionic app with CodeIgniter as backend. I need to add a custom authentication like an automatic token generation from server side and its verification in client side for each request. Can anyone show me the path?

**Comment by Sephster** [comment]
Hi @gopalvenu033 - thanks for raising an issue. I think your best route would be to check the [documentation](https://oauth2.thephpleague.com/) and reference the [examples](https://github.com/thephpleague/oauth2-server/tree/master/examples) to get going. Failing that, I would post your question on StackOverflow to get some assistance.

I'm happy to answer specific questions but generalised questions such as this will take too long to resolve. I hope the resources I've listed above can help but if you do have any specific questions, please feel free to reopen an issue.
