### ISSUE TITLE
invalid_credentials is not spec-compliant

### ISSUE THREAD

**Issue by brandonfarber** [thephpleague/oauth2-server#955]
When using the Resource Owner Password Credentials Grant type, if an invalid username+password combination is supplied the server returns an "invalid_credentials" error code response.

https://github.com/thephpleague/oauth2-server/blob/master/src/Exception/OAuthServerException.php#L160

This is not, however, spec-compliant and any consumers interacting with the server may not handle this appropriately as a result. According to the specifications, an incorrect username+password combination should still return an invalid_grant error code response.

https://tools.ietf.org/html/rfc6749#section-5.2

I would recommend for the widest-ranging support to adjust the error code returned here. The error message you supply is already sufficiently clear to assist in determining the underlying problem.

**Comment by Sephster** [comment]
I could have sworn this had previously been reported but I can find no reference to it and it hasn't been resolved for version 8. As such, I will leave this open and look to fix it for the next major release. Thank you for reporting this to us!

**Comment by Sephster** [comment]
I knew this was ringing a bell. It is related to pull request #803. I will try and get it pushed through in the morning. Thanks
