### ISSUE TITLE
In the 8.0.0 branch the AuthCodeGrant does not accept client_id and client_secret through HTTP Basic Authentication

### ISSUE THREAD

**Issue by Devristo** [thephpleague/oauth2-server#961]
First of all thanks for this great library! I have been playing around with the 8.0.0 branch because we need the `isConfidential` / PKCE functionality. However we stumbled upon a regression: Clients can no longer authenticate themselves using HTTP Basic authentication. 

This seem to have happened in https://github.com/thephpleague/oauth2-server/pull/938. More specifically: The `$this->validateClient()` on https://github.com/thephpleague/oauth2-server/pull/938/files#diff-4390e0360afea418f1505565796e2fb9L73 was checking for HTTP Basic Auth  but it has been moved down the method.

A fix would be very welcome. Although we work around this for now in our middleware by setting client_id and client_secret in the request when we find them through HTTP Basic auth.

**Comment by Sephster** [comment]
Hi @Devristo - thanks for getting in touch and thanks for the kind words regarding the library.

Is your code calling the `validateClient()` function at all? There was a change in the 8.0.0 branch where clients must now identify themselves as confidential. If they aren't confidential, then no client validation takes place as the client cannot be trusted to keep its credentials secret.

**Comment by Devristo** [comment]
In this case I am not using the PKCE flow but a confidential client. However the 8.0.0 branch changed the way the AuthCodeGrant is implemented.

`src/Grant/AuthCodeGrant.php`
![image](https://user-images.githubusercontent.com/1564257/48115647-e8318800-e263-11e8-91bd-c8fd1e359bab.png)

Previously the `validateClient` call would check the request params AND the headers using `getBasicAuthCredentials`. However now the `respondToAccessTokenRequest` only checks the request params and will fail if the client is using HTTP Basic authentication.

If you want I could create an  test that would succeed on 7.x and fail on 8.x to illustrate the issue?

**Comment by Sephster** [comment]
Ahh I think I see. I presume it is issuing an _invalid request_ exception because you aren't passing a client ID in as a request parameter, correct? 

I will look at getting a fix sorted for this soon and double checking everything. Thanks for reporting this.

**Comment by Devristo** [comment]
Exactly! Thanks for picking this up

**Comment by Sephster** [comment]
Closing as issue now resolved by PR #978
