### ISSUE TITLE
Support nonce for Authorization Code and Implicit Grant

### ISSUE THREAD

**Issue by m0ark** [thephpleague/oauth2-server#962]
Currently I have to integrate full [OpenId Connect Core](https://openid.net/specs/openid-connect-core-1_0.html) spec, so I came across https://github.com/steverhoades/oauth2-openid-connect-server to this library. 

OIDC Implicit Flow requires a `nonce` to be included in the id_token issued. (see [3.2.2.1.](https://openid.net/specs/openid-connect-core-1_0.html))

In OIDC Authorization Code Grant the request can contain a nonce and in this case it has to be included in the id_token aswell (see [3.1.2.1.](https://openid.net/specs/openid-connect-core-1_0.html)).

For OAuth2 handling `nonce`s is only ever mentioned in a security advisory (mentioned in #634), but for OpenId Connect handling is mandatory. Since OpenId Connect is just an extension of OAuth2 i think `nonce`s should be handled by the latter.

**Comment by Sephster** [comment]
We aren't supporting OpenId Connect at present but do plan to do so in the future. I don't believe including a nonce is required in any of the RFC's we currently support so don't think this will be added in until full support for OpenId Connect is.

**Comment by MichaelKubovic** [comment]
Hi @m0ark, how did you deal with the missing nonce?

**Comment by lordrhodos** [comment]
@m0ark I am interested in this as well. Hit the same issue.

**Comment by ThaDaVos** [comment]
Any ETA when the official OpenID connect is coming? I am running into the same issue that the `nonce` is missing - figured out one can easily add it inside https://github.com/steverhoades/oauth2-openid-connect-server `IdTokenResponse` using a `->withClaim('nonce', '<VALUE>')` inside the overriden `getBuilder` method - but struggling to get the `nonce` all the way through so it's accessible there

**Comment by Sephster** [comment]
No plans to add into the next major so likely after that. Steve's repo is the best option for now 👍

**Comment by ThaDaVos** [comment]
Sadly it doesn't handle the `nonce` part (I am already using it) - but trying to make it spec compliant - any hint on how one uses the new `AuthorizationRequestInterface` introduced with https://github.com/thephpleague/oauth2-server/pull/1110 ?

I can't find any docs of it but seems to be able to solve the issue

**Comment by ThaDaVos** [comment]
Nvm... V9 isn't even out yet....

**Comment by ThaDaVos** [comment]
I added a comment in https://github.com/steverhoades/oauth2-openid-connect-server/issues/47 - how I did it today succesfully
