### ISSUE TITLE
Security Issues Checking

### ISSUE THREAD

**Issue by jay-shah-personal** [thephpleague/oauth2-server#964]
Is this library prevents such vulnerabilities ?

By modifying **alg** value in **jwt token's header** to pass verification of token in all type of grants liek client, password grant etc.

https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by Sephster** [comment]
I believe so. For JWT we use lcobucci/jwt. This vulnerability was fixed in version 3.0 and we are now using the 3.2 version.

As noted in the blog post, we also specify the algorithm to use when were are verifying the JWT.
