### ISSUE TITLE
is there anyway to translate response messsage?

### ISSUE THREAD

**Issue by alukaa** [thephpleague/oauth2-server#972]
like the title said, all the response message are english, if i want these messages to another language,how do i do ,or is there some feature i can use, thx

**Comment by Sephster** [comment]
There is no official way at this time. Issue #747 is tracking this but has not been worked on yet. Sorry that there isn't a resolution for you at the moment

**Comment by alukaa** [comment]
so owners of this project consider to add this feature or not, i think it's important. for us we can understand what happened, but if we notice these response message to user, they may can not understand what happened. hope your guys to think a little about this, thx
