### ISSUE TITLE
Dangerously incorrect documentation (re: public/private keys)

### ISSUE THREAD

**Issue by krozinov** [thephpleague/oauth2-server#974]
Hi team,

There is a critical mistake in the wording on the Installation page (https://oauth2.thephpleague.com/installation/) under the section "Generating public and private keys"

It says:
> The public/private key pair is used to sign and verify JWTs transmitted. The Authorization Server possesses the public key to sign tokens and the Resource Server possesses the corresponding private key to verify the signatures. To generate the private key run this command on the terminal

It should say:
> The public/private key pair is used to sign and verify JWTs transmitted. The Authorization Server possesses the **private** key to sign tokens and the Resource Server possesses the corresponding **public** key to verify the signatures. To generate the private key run this command on the terminal

The current documentation is dangerously wrong - instructing users to commit a potentially serious security issue.

**Comment by Sephster** [comment]
Merged. Thanks for spotting
