### ISSUE TITLE
Timeline for v8.0 release?

### ISSUE THREAD

**Issue by krozinov** [thephpleague/oauth2-server#975]
Not an issue, just curious if there is a timeline for the release of v8.0.0 and what changes are to be expected?

I saw a ticket that said that support for OpenID Connect is scheduled to be included in v8.0.0?

Thank you!

**Comment by Sephster** [comment]
No definitive timescale on version 8. I've added a number of features I want to see added to version 8 in the version 8 milestone. We are about 50% of the way there at the moment, but more features might be added.
