### ISSUE TITLE
What should be instantiated for each step on the server? |documentation|

### ISSUE THREAD

**Issue by itay-moav** [thephpleague/oauth2-server#980]
Kudos for the quality of the code of this lib. 

In the setup section, under Authorization Code Grant, it can be interpreted that for each of the three requests (first redirect, user is authenticated and token request) You instantiate the following objects:
```
\League\OAuth2\Server\AuthorizationServer  
\League\OAuth2\Server\Grant\AuthCodeGrant  
```
And re-configure the TTL
`$grant->setRefreshTokenTTL(new \DateInterval('P1M'));  `
and  

```
$server->enableGrantType(
    $grant,
    new \DateInterval('PT1H') // access tokens will expire after 1 hour
);
```

I am new to this, so I might missunderstand,  
Shouldn't the grant class be instantiated and setup only after user is authenticated and server returns the auth token?
  
Should the access token be setup/created only when the user requests for that token?

**Comment by mtangoo** [comment]
which grant do you want to be available?

**Comment by itay-moav** [comment]
AuthCodeGrant

**Comment by itay-moav** [comment]
going through the code I figured this
