### ISSUE TITLE
Feature request: event or callback when access token about to be refreshed

### ISSUE THREAD

**Issue by jacobweber** [thephpleague/oauth2-server#984]
In my app, when someone tries to refresh the access token, I'd like to perform some checks in my app, like making sure the user isn't temporarily disabled.

If the checks fail, I'd like to prevent the access token from being refreshed, but also prevent the refresh token from being revoked. So the checks should happen after the refresh token is validated, but before the old tokens are revoked.

Is this something you'd consider adding? Otherwise I can just add it in my fork.

This is what I added to `RefreshTokenGrant->respondToAccessTokenRequest()`, at [line 62](https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/RefreshTokenGrant.php#L62). I also added a new `RefreshTokenEvent` class, which just extends `RequestEvent` and adds an extra parameter. The old refresh token array is needed so the app can know the user and client IDs.
```
$event = $this->getEmitter()->emit(new RefreshTokenEvent(RefreshTokenEvent::REFRESH_TOKEN_REFRESHING, $request, $oldRefreshToken));
if ($event->isPropagationStopped()) {
    throw OAuthServerException::accessDenied();
}

// Expire old tokens
```

This way my app can call `$event->stopPropagation()` if it needs to deny access. It doesn't look like the `access_denied` error is expected from this endpoint, according to the [OAuth spec](https://tools.ietf.org/html/rfc6749#section-5.2), but the other codes didn't seem appropriate.

**Comment by Sephster** [comment]
I don't think this is something we would add in as it strays away from normal conventions somewhat. It is important to remember that it is the client that has access on behalf of the user. I think linking the two so closely is probably not a good idea. If the user is suspended in an application, client access should probably be revoked.

**Comment by jacobweber** [comment]
Fair enough, thanks.
