### ISSUE TITLE
Incorrect login password error management with optimus - heimdal

### ISSUE THREAD

**Issue by christophemassin** [thephpleague/oauth2-server#989]
Hello, 

I got an api, with optimus heimdal installed on it ( https://packagist.org/packages/optimus/heimdal ) and a fresh laravel 5.7 

I ve add your package on it, to deal with the oauth2 part. However, when i try to log with a bad credential, i got 

{
    "error": "invalid_credentials",
    "message": "The user credentials were incorrect."
} 

But i would like to get 

{
    "status": "error",
    "code": 0,
    "message": "",
    "exception": "" 
}

using the formatter of this project, to be able to report them in sentry later on. But it's not possible, cause in : AuthorizationServerMiddleware you do : 

```
  /**
     * @param ServerRequestInterface $request
     * @param ResponseInterface      $response
     * @param callable               $next
     *
     * @return ResponseInterface
     */
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next)
    {
        try {
            $response = $this->server->respondToAccessTokenRequest($request, $response);
        } catch (OAuthServerException $exception) {
            return $exception->generateHttpResponse($response);
            // @codeCoverageIgnoreStart
        } catch (Exception $exception) {
            return (new OAuthServerException($exception->getMessage(), 0, 'unknown_error', 500))
                ->generateHttpResponse($response);
            // @codeCoverageIgnoreEnd
        }

        // Pass the request and response on to the next responder in the chain
        return $next($request, $response);
    }
```

dealing with the http response yourself. Is it possible to have a change in the way of dealing with the error, ( would be useful for sentry for example ) or have a way to overload your code in the package ? ( i try to override the code by adding in middleware 

 \League\OAuth2\Server\Middleware\AuthorizationServerMiddleware::class => \App\Http\Middleware\AuthorizationServerMiddleware::class, 

in the Http\Kernel file , but it does not work :/ 

Thanks ^^

**Comment by Sephster** [comment]
Hi @christophemassin - Sorry for the delayed response, I was on holiday. I'm sorry but I'm not familiar with the Heimdal package. I think the easiest way would be to replace the AuthorizationServerMiddleware with your own implementation but it is hard for me to comment without knowing the full workflow.

I would recommend this question is asked on either Reddit/Laracasts/StackOverflow or raised as an issue on the Heimdal package as people more familiar with this scenario would be better placed to assist you. 

Many thanks.
