### ISSUE TITLE
How to deal with native app social login

### ISSUE THREAD

**Issue by ghostika** [thephpleague/oauth2-server#990]
I started to integrate the library, what was fairly straight forward, but there is a part where I'm not sure, how to proceed.
I also have a mobile app, where I would like to authenticate my user.
Using Facebook in the browser is not a problem (when I'm authenticating myself in the browser) bot on the phone I want to give the opportunity for the user to use the native Facebook app. Then the facebook app would return an access token, what my server can check, but how should I implement this in the normal OAuth2 flow? Or is this not fit in at all?

**Comment by Sephster** [comment]
Hi @ghostika - Sorry, I'm not sure what you mean. This server can only consume and issue access tokens generated by itself. From your initial comments, it looks like you are trying to do something with an access token issued by Facebook. Is this correct?

**Comment by Sephster** [comment]
Sorry @ghostika I'm not sure I'm following still. My confusion is stemming from the need to login to Facebook and then authenticate with the OAuth 2 server. I think this question might be better served on StackOverflow as I'm unclear what you are trying to achieve and don't have much familiarity with Facebook's API offerings. Sorry I can't be of further assistance.
