### ISSUE TITLE
Setting up resource server monitoring for symfony 4.x

### ISSUE THREAD

**Issue by brandinchiu** [thephpleague/oauth2-server#994]
I'm not sure if this is the most appropriate place to ask this, but I'd love some clarity on how to implement the resource server monitoring for a Symfony 4.x application.

I'm loosely familiar with Symfony middleware, but feel like I am missing something obvious.

Specifically, this part: 
`new \League\OAuth2\Server\Middleware\ResourceServerMiddleware($server);`

I'm not sure where I would be expected to put this in a way that would automatically work. 

I'd appreciate any assistance, thanks!

**Comment by Sephster** [comment]
Sorry @brandinchiu but I'm not familiar with Symfony 4 so wouldn't be able to assist here. I think this question would be better suited to StackOverflow/Reddit etc. Sorry I can't be of any help
