### ISSUE TITLE
Make UserEntityInterface Api more compatible with AccessTokenEntityInterface

### ISSUE THREAD

**Issue by vidalvasconcelos** [thephpleague/oauth2-server#998]
I implementing an package for Zend Expressive and noticed a possible improvement in UserEntityInterface API.

The **AccessTokenEntityInterface** extends **TokenInterface**, this interface require a **setUserIdentifier** method but UserEntityInterface not have a **setIdentifier**, for simple use, this does not cause any problem. but will have great value to improve the isolation these entities.

<img width="400" alt="screenshot 2019-02-20 16 36 24" src="https://user-images.githubusercontent.com/10285080/53119213-b3ed8900-352d-11e9-982c-56af7cd7e97c.png">

<img width="300" alt="screenshot 2019-02-20 16 37 44" src="https://user-images.githubusercontent.com/10285080/53119312-f020e980-352d-11e9-9d1e-a59bdf430ff0.png">

**Comment by Sephster** [comment]
At the moment, I can't see a use case for this change. The `UserEntityInterface` is a representation for a user entity which is stored in the DB. Typically the ID of the user would be set when the record is retrieved from the DB and the implementing object is created.

I can't think of a scenario where we would subsequently update the ID or create the entity without knowing the ID in advance and setting it later.

I'm sure there will be some use cases but I don't think they're that common and I'm struggling to think of one I've come across of late. 

I appreciate why it appears odd having a getter without a setter, and that this doesn't match other interfaces. Happy to review this if any users state a clear use case where they need a setter to modify the ID but at the moment I think we will leave this as is.

Thank you very much for getting in touch regarding this. Hope you have a great weekend.
