### ISSUE TITLE
Security question/issue: how is client_credentials grant restricted to confidential clients?

### ISSUE THREAD

**Issue by jacobweber** [thephpleague/oauth2-server#999]
If you're using the `client_credentials` grant, you [MUST use a confidential client](https://tools.ietf.org/html/rfc6749#section-4.4) with a secret; otherwise anyone can get client-level credentials (right?).

But I don't think there's anything built into oauth2-server that validates this, and there's nothing in the [included example](https://github.com/thephpleague/oauth2-server/blob/master/examples/src/Repositories/ClientRepository.php).

So if I run the example, but add a non-confidential client to getClientEntity:
```
        $clients = [
            'mynotsoawesomeapp' => [
                'secret'          => password_hash('123abc', PASSWORD_BCRYPT),
                'name'            => 'My Not-So Awesome App',
                'redirect_uri'    => 'http://foo/bar',
                'is_confidential' => false,
            ],
```
I can make the client-credentials request with an incorrect or missing `client_secret`, and it will grant an access token.

This seems bad. Or am I missing something? I know I could check `grantType` myself here, along with `is_confidential`. But this should probably be documented.

The documentation for [`ClientEntityInterface->getClientEntity`](https://oauth2.thephpleague.com/client-repository-interface/) just says:

> If the client is confidential (i.e. is capable of securely storing a secret) and $mustValidateSecret === true then the secret must be validated.

But it doesn't tell you what to do if the client isn't confidential.

**Comment by Sephster** [comment]
The `is_confidential` flag is just an example implementation you could use to flag your clients as confidential. In the latest version of the server, we don't currently support specifying whether the client is confidential or public. This is left up to you.

In an upcoming version we will support the ability to flag a client as private or public. For now though, the implementer should just ensure they never let a public client use this grant. How they achieve this is outside the scope of the current version of this library.
